packages:
  - "!**/_**/**"
  - apps/*
  - packages/*

autoInstallPeers: true

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - "@nestjs/core"
  - "@openapitools/openapi-generator-cli"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - nx

strictPeerDependencies: false
