// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: obiente/cloud/databases/v1/database_service.proto

package databasesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/obiente/cloud/apps/shared/proto/obiente/cloud/databases/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "obiente.cloud.databases.v1.DatabaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceListDatabasesProcedure is the fully-qualified name of the DatabaseService's
	// ListDatabases RPC.
	DatabaseServiceListDatabasesProcedure = "/obiente.cloud.databases.v1.DatabaseService/ListDatabases"
	// DatabaseServiceCreateDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// CreateDatabase RPC.
	DatabaseServiceCreateDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/CreateDatabase"
	// DatabaseServiceGetDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabase RPC.
	DatabaseServiceGetDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetDatabase"
	// DatabaseServiceUpdateDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// UpdateDatabase RPC.
	DatabaseServiceUpdateDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/UpdateDatabase"
	// DatabaseServiceDeleteDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// DeleteDatabase RPC.
	DatabaseServiceDeleteDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/DeleteDatabase"
	// DatabaseServiceStartDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// StartDatabase RPC.
	DatabaseServiceStartDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/StartDatabase"
	// DatabaseServiceStopDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// StopDatabase RPC.
	DatabaseServiceStopDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/StopDatabase"
	// DatabaseServiceSleepDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// SleepDatabase RPC.
	DatabaseServiceSleepDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/SleepDatabase"
	// DatabaseServiceRestartDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// RestartDatabase RPC.
	DatabaseServiceRestartDatabaseProcedure = "/obiente.cloud.databases.v1.DatabaseService/RestartDatabase"
	// DatabaseServiceStreamDatabaseStatusProcedure is the fully-qualified name of the DatabaseService's
	// StreamDatabaseStatus RPC.
	DatabaseServiceStreamDatabaseStatusProcedure = "/obiente.cloud.databases.v1.DatabaseService/StreamDatabaseStatus"
	// DatabaseServiceGetDatabaseConnectionInfoProcedure is the fully-qualified name of the
	// DatabaseService's GetDatabaseConnectionInfo RPC.
	DatabaseServiceGetDatabaseConnectionInfoProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetDatabaseConnectionInfo"
	// DatabaseServiceResetDatabasePasswordProcedure is the fully-qualified name of the
	// DatabaseService's ResetDatabasePassword RPC.
	DatabaseServiceResetDatabasePasswordProcedure = "/obiente.cloud.databases.v1.DatabaseService/ResetDatabasePassword"
	// DatabaseServiceGetDatabaseSchemaProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabaseSchema RPC.
	DatabaseServiceGetDatabaseSchemaProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetDatabaseSchema"
	// DatabaseServiceListTablesProcedure is the fully-qualified name of the DatabaseService's
	// ListTables RPC.
	DatabaseServiceListTablesProcedure = "/obiente.cloud.databases.v1.DatabaseService/ListTables"
	// DatabaseServiceGetTableStructureProcedure is the fully-qualified name of the DatabaseService's
	// GetTableStructure RPC.
	DatabaseServiceGetTableStructureProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetTableStructure"
	// DatabaseServiceExecuteQueryProcedure is the fully-qualified name of the DatabaseService's
	// ExecuteQuery RPC.
	DatabaseServiceExecuteQueryProcedure = "/obiente.cloud.databases.v1.DatabaseService/ExecuteQuery"
	// DatabaseServiceStreamQueryProcedure is the fully-qualified name of the DatabaseService's
	// StreamQuery RPC.
	DatabaseServiceStreamQueryProcedure = "/obiente.cloud.databases.v1.DatabaseService/StreamQuery"
	// DatabaseServiceGetTableDataProcedure is the fully-qualified name of the DatabaseService's
	// GetTableData RPC.
	DatabaseServiceGetTableDataProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetTableData"
	// DatabaseServiceUpdateTableRowProcedure is the fully-qualified name of the DatabaseService's
	// UpdateTableRow RPC.
	DatabaseServiceUpdateTableRowProcedure = "/obiente.cloud.databases.v1.DatabaseService/UpdateTableRow"
	// DatabaseServiceInsertTableRowProcedure is the fully-qualified name of the DatabaseService's
	// InsertTableRow RPC.
	DatabaseServiceInsertTableRowProcedure = "/obiente.cloud.databases.v1.DatabaseService/InsertTableRow"
	// DatabaseServiceDeleteTableRowsProcedure is the fully-qualified name of the DatabaseService's
	// DeleteTableRows RPC.
	DatabaseServiceDeleteTableRowsProcedure = "/obiente.cloud.databases.v1.DatabaseService/DeleteTableRows"
	// DatabaseServiceListBackupsProcedure is the fully-qualified name of the DatabaseService's
	// ListBackups RPC.
	DatabaseServiceListBackupsProcedure = "/obiente.cloud.databases.v1.DatabaseService/ListBackups"
	// DatabaseServiceCreateBackupProcedure is the fully-qualified name of the DatabaseService's
	// CreateBackup RPC.
	DatabaseServiceCreateBackupProcedure = "/obiente.cloud.databases.v1.DatabaseService/CreateBackup"
	// DatabaseServiceGetBackupProcedure is the fully-qualified name of the DatabaseService's GetBackup
	// RPC.
	DatabaseServiceGetBackupProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetBackup"
	// DatabaseServiceDeleteBackupProcedure is the fully-qualified name of the DatabaseService's
	// DeleteBackup RPC.
	DatabaseServiceDeleteBackupProcedure = "/obiente.cloud.databases.v1.DatabaseService/DeleteBackup"
	// DatabaseServiceRestoreBackupProcedure is the fully-qualified name of the DatabaseService's
	// RestoreBackup RPC.
	DatabaseServiceRestoreBackupProcedure = "/obiente.cloud.databases.v1.DatabaseService/RestoreBackup"
	// DatabaseServiceGetDatabaseMetricsProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabaseMetrics RPC.
	DatabaseServiceGetDatabaseMetricsProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetDatabaseMetrics"
	// DatabaseServiceStreamDatabaseMetricsProcedure is the fully-qualified name of the
	// DatabaseService's StreamDatabaseMetrics RPC.
	DatabaseServiceStreamDatabaseMetricsProcedure = "/obiente.cloud.databases.v1.DatabaseService/StreamDatabaseMetrics"
	// DatabaseServiceListDatabaseSizesProcedure is the fully-qualified name of the DatabaseService's
	// ListDatabaseSizes RPC.
	DatabaseServiceListDatabaseSizesProcedure = "/obiente.cloud.databases.v1.DatabaseService/ListDatabaseSizes"
	// DatabaseServiceGetDatabaseUsageProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabaseUsage RPC.
	DatabaseServiceGetDatabaseUsageProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetDatabaseUsage"
	// DatabaseServiceCreateTableProcedure is the fully-qualified name of the DatabaseService's
	// CreateTable RPC.
	DatabaseServiceCreateTableProcedure = "/obiente.cloud.databases.v1.DatabaseService/CreateTable"
	// DatabaseServiceAlterTableProcedure is the fully-qualified name of the DatabaseService's
	// AlterTable RPC.
	DatabaseServiceAlterTableProcedure = "/obiente.cloud.databases.v1.DatabaseService/AlterTable"
	// DatabaseServiceDropTableProcedure is the fully-qualified name of the DatabaseService's DropTable
	// RPC.
	DatabaseServiceDropTableProcedure = "/obiente.cloud.databases.v1.DatabaseService/DropTable"
	// DatabaseServiceRenameTableProcedure is the fully-qualified name of the DatabaseService's
	// RenameTable RPC.
	DatabaseServiceRenameTableProcedure = "/obiente.cloud.databases.v1.DatabaseService/RenameTable"
	// DatabaseServiceTruncateTableProcedure is the fully-qualified name of the DatabaseService's
	// TruncateTable RPC.
	DatabaseServiceTruncateTableProcedure = "/obiente.cloud.databases.v1.DatabaseService/TruncateTable"
	// DatabaseServiceCreateIndexProcedure is the fully-qualified name of the DatabaseService's
	// CreateIndex RPC.
	DatabaseServiceCreateIndexProcedure = "/obiente.cloud.databases.v1.DatabaseService/CreateIndex"
	// DatabaseServiceDropIndexProcedure is the fully-qualified name of the DatabaseService's DropIndex
	// RPC.
	DatabaseServiceDropIndexProcedure = "/obiente.cloud.databases.v1.DatabaseService/DropIndex"
	// DatabaseServiceGetTableDDLProcedure is the fully-qualified name of the DatabaseService's
	// GetTableDDL RPC.
	DatabaseServiceGetTableDDLProcedure = "/obiente.cloud.databases.v1.DatabaseService/GetTableDDL"
)

// DatabaseServiceClient is a client for the obiente.cloud.databases.v1.DatabaseService service.
type DatabaseServiceClient interface {
	// List organization databases
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// Create new database instance
	CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error)
	// Get database instance details
	GetDatabase(context.Context, *connect.Request[v1.GetDatabaseRequest]) (*connect.Response[v1.GetDatabaseResponse], error)
	// Update database instance configuration
	UpdateDatabase(context.Context, *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error)
	// Delete database instance
	DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error)
	// Start a stopped database instance
	StartDatabase(context.Context, *connect.Request[v1.StartDatabaseRequest]) (*connect.Response[v1.StartDatabaseResponse], error)
	// Stop a running database instance
	StopDatabase(context.Context, *connect.Request[v1.StopDatabaseRequest]) (*connect.Response[v1.StopDatabaseResponse], error)
	// Put a database to sleep (auto-wakes on connection)
	SleepDatabase(context.Context, *connect.Request[v1.SleepDatabaseRequest]) (*connect.Response[v1.SleepDatabaseResponse], error)
	// Restart a database instance
	RestartDatabase(context.Context, *connect.Request[v1.RestartDatabaseRequest]) (*connect.Response[v1.RestartDatabaseResponse], error)
	// Stream database status updates
	StreamDatabaseStatus(context.Context, *connect.Request[v1.StreamDatabaseStatusRequest]) (*connect.ServerStreamForClient[v1.DatabaseStatusUpdate], error)
	// Get database connection info (credentials, connection strings)
	GetDatabaseConnectionInfo(context.Context, *connect.Request[v1.GetDatabaseConnectionInfoRequest]) (*connect.Response[v1.GetDatabaseConnectionInfoResponse], error)
	// Reset database password
	ResetDatabasePassword(context.Context, *connect.Request[v1.ResetDatabasePasswordRequest]) (*connect.Response[v1.ResetDatabasePasswordResponse], error)
	// Database introspection - get schema information
	GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.GetDatabaseSchemaResponse], error)
	// List tables in a database
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// Get table structure/details
	GetTableStructure(context.Context, *connect.Request[v1.GetTableStructureRequest]) (*connect.Response[v1.GetTableStructureResponse], error)
	// Execute query on database
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	// Stream query results (for large result sets)
	StreamQuery(context.Context, *connect.Request[v1.StreamQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResultRow], error)
	// Table data browsing and editing
	GetTableData(context.Context, *connect.Request[v1.GetTableDataRequest]) (*connect.Response[v1.GetTableDataResponse], error)
	UpdateTableRow(context.Context, *connect.Request[v1.UpdateTableRowRequest]) (*connect.Response[v1.UpdateTableRowResponse], error)
	InsertTableRow(context.Context, *connect.Request[v1.InsertTableRowRequest]) (*connect.Response[v1.InsertTableRowResponse], error)
	DeleteTableRows(context.Context, *connect.Request[v1.DeleteTableRowsRequest]) (*connect.Response[v1.DeleteTableRowsResponse], error)
	// Backup management
	ListBackups(context.Context, *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResponse], error)
	CreateBackup(context.Context, *connect.Request[v1.CreateBackupRequest]) (*connect.Response[v1.CreateBackupResponse], error)
	GetBackup(context.Context, *connect.Request[v1.GetBackupRequest]) (*connect.Response[v1.GetBackupResponse], error)
	DeleteBackup(context.Context, *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResponse], error)
	RestoreBackup(context.Context, *connect.Request[v1.RestoreBackupRequest]) (*connect.Response[v1.RestoreBackupResponse], error)
	// Get database metrics
	GetDatabaseMetrics(context.Context, *connect.Request[v1.GetDatabaseMetricsRequest]) (*connect.Response[v1.GetDatabaseMetricsResponse], error)
	// Stream real-time database metrics
	StreamDatabaseMetrics(context.Context, *connect.Request[v1.StreamDatabaseMetricsRequest]) (*connect.ServerStreamForClient[v1.DatabaseMetric], error)
	// Get available database sizes/pricing
	ListDatabaseSizes(context.Context, *connect.Request[v1.ListDatabaseSizesRequest]) (*connect.Response[v1.ListDatabaseSizesResponse], error)
	// Get database usage and billing information
	GetDatabaseUsage(context.Context, *connect.Request[v1.GetDatabaseUsageRequest]) (*connect.Response[v1.GetDatabaseUsageResponse], error)
	// Schema DDL operations
	CreateTable(context.Context, *connect.Request[v1.CreateTableRequest]) (*connect.Response[v1.CreateTableResponse], error)
	AlterTable(context.Context, *connect.Request[v1.AlterTableRequest]) (*connect.Response[v1.AlterTableResponse], error)
	DropTable(context.Context, *connect.Request[v1.DropTableRequest]) (*connect.Response[v1.DropTableResponse], error)
	RenameTable(context.Context, *connect.Request[v1.RenameTableRequest]) (*connect.Response[v1.RenameTableResponse], error)
	TruncateTable(context.Context, *connect.Request[v1.TruncateTableRequest]) (*connect.Response[v1.TruncateTableResponse], error)
	// Index management
	CreateIndex(context.Context, *connect.Request[v1.CreateIndexRequest]) (*connect.Response[v1.CreateIndexResponse], error)
	DropIndex(context.Context, *connect.Request[v1.DropIndexRequest]) (*connect.Response[v1.DropIndexResponse], error)
	// Get DDL statement for a table
	GetTableDDL(context.Context, *connect.Request[v1.GetTableDDLRequest]) (*connect.Response[v1.GetTableDDLResponse], error)
}

// NewDatabaseServiceClient constructs a client for the obiente.cloud.databases.v1.DatabaseService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := v1.File_obiente_cloud_databases_v1_database_service_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		listDatabases: connect.NewClient[v1.ListDatabasesRequest, v1.ListDatabasesResponse](
			httpClient,
			baseURL+DatabaseServiceListDatabasesProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListDatabases")),
			connect.WithClientOptions(opts...),
		),
		createDatabase: connect.NewClient[v1.CreateDatabaseRequest, v1.CreateDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceCreateDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateDatabase")),
			connect.WithClientOptions(opts...),
		),
		getDatabase: connect.NewClient[v1.GetDatabaseRequest, v1.GetDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabase")),
			connect.WithClientOptions(opts...),
		),
		updateDatabase: connect.NewClient[v1.UpdateDatabaseRequest, v1.UpdateDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceUpdateDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("UpdateDatabase")),
			connect.WithClientOptions(opts...),
		),
		deleteDatabase: connect.NewClient[v1.DeleteDatabaseRequest, v1.DeleteDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceDeleteDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DeleteDatabase")),
			connect.WithClientOptions(opts...),
		),
		startDatabase: connect.NewClient[v1.StartDatabaseRequest, v1.StartDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceStartDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("StartDatabase")),
			connect.WithClientOptions(opts...),
		),
		stopDatabase: connect.NewClient[v1.StopDatabaseRequest, v1.StopDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceStopDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("StopDatabase")),
			connect.WithClientOptions(opts...),
		),
		sleepDatabase: connect.NewClient[v1.SleepDatabaseRequest, v1.SleepDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceSleepDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("SleepDatabase")),
			connect.WithClientOptions(opts...),
		),
		restartDatabase: connect.NewClient[v1.RestartDatabaseRequest, v1.RestartDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceRestartDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("RestartDatabase")),
			connect.WithClientOptions(opts...),
		),
		streamDatabaseStatus: connect.NewClient[v1.StreamDatabaseStatusRequest, v1.DatabaseStatusUpdate](
			httpClient,
			baseURL+DatabaseServiceStreamDatabaseStatusProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("StreamDatabaseStatus")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseConnectionInfo: connect.NewClient[v1.GetDatabaseConnectionInfoRequest, v1.GetDatabaseConnectionInfoResponse](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseConnectionInfoProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseConnectionInfo")),
			connect.WithClientOptions(opts...),
		),
		resetDatabasePassword: connect.NewClient[v1.ResetDatabasePasswordRequest, v1.ResetDatabasePasswordResponse](
			httpClient,
			baseURL+DatabaseServiceResetDatabasePasswordProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ResetDatabasePassword")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseSchema: connect.NewClient[v1.GetDatabaseSchemaRequest, v1.GetDatabaseSchemaResponse](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseSchemaProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseSchema")),
			connect.WithClientOptions(opts...),
		),
		listTables: connect.NewClient[v1.ListTablesRequest, v1.ListTablesResponse](
			httpClient,
			baseURL+DatabaseServiceListTablesProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListTables")),
			connect.WithClientOptions(opts...),
		),
		getTableStructure: connect.NewClient[v1.GetTableStructureRequest, v1.GetTableStructureResponse](
			httpClient,
			baseURL+DatabaseServiceGetTableStructureProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetTableStructure")),
			connect.WithClientOptions(opts...),
		),
		executeQuery: connect.NewClient[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse](
			httpClient,
			baseURL+DatabaseServiceExecuteQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ExecuteQuery")),
			connect.WithClientOptions(opts...),
		),
		streamQuery: connect.NewClient[v1.StreamQueryRequest, v1.QueryResultRow](
			httpClient,
			baseURL+DatabaseServiceStreamQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("StreamQuery")),
			connect.WithClientOptions(opts...),
		),
		getTableData: connect.NewClient[v1.GetTableDataRequest, v1.GetTableDataResponse](
			httpClient,
			baseURL+DatabaseServiceGetTableDataProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetTableData")),
			connect.WithClientOptions(opts...),
		),
		updateTableRow: connect.NewClient[v1.UpdateTableRowRequest, v1.UpdateTableRowResponse](
			httpClient,
			baseURL+DatabaseServiceUpdateTableRowProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("UpdateTableRow")),
			connect.WithClientOptions(opts...),
		),
		insertTableRow: connect.NewClient[v1.InsertTableRowRequest, v1.InsertTableRowResponse](
			httpClient,
			baseURL+DatabaseServiceInsertTableRowProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("InsertTableRow")),
			connect.WithClientOptions(opts...),
		),
		deleteTableRows: connect.NewClient[v1.DeleteTableRowsRequest, v1.DeleteTableRowsResponse](
			httpClient,
			baseURL+DatabaseServiceDeleteTableRowsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DeleteTableRows")),
			connect.WithClientOptions(opts...),
		),
		listBackups: connect.NewClient[v1.ListBackupsRequest, v1.ListBackupsResponse](
			httpClient,
			baseURL+DatabaseServiceListBackupsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListBackups")),
			connect.WithClientOptions(opts...),
		),
		createBackup: connect.NewClient[v1.CreateBackupRequest, v1.CreateBackupResponse](
			httpClient,
			baseURL+DatabaseServiceCreateBackupProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateBackup")),
			connect.WithClientOptions(opts...),
		),
		getBackup: connect.NewClient[v1.GetBackupRequest, v1.GetBackupResponse](
			httpClient,
			baseURL+DatabaseServiceGetBackupProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetBackup")),
			connect.WithClientOptions(opts...),
		),
		deleteBackup: connect.NewClient[v1.DeleteBackupRequest, v1.DeleteBackupResponse](
			httpClient,
			baseURL+DatabaseServiceDeleteBackupProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DeleteBackup")),
			connect.WithClientOptions(opts...),
		),
		restoreBackup: connect.NewClient[v1.RestoreBackupRequest, v1.RestoreBackupResponse](
			httpClient,
			baseURL+DatabaseServiceRestoreBackupProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("RestoreBackup")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseMetrics: connect.NewClient[v1.GetDatabaseMetricsRequest, v1.GetDatabaseMetricsResponse](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseMetricsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseMetrics")),
			connect.WithClientOptions(opts...),
		),
		streamDatabaseMetrics: connect.NewClient[v1.StreamDatabaseMetricsRequest, v1.DatabaseMetric](
			httpClient,
			baseURL+DatabaseServiceStreamDatabaseMetricsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("StreamDatabaseMetrics")),
			connect.WithClientOptions(opts...),
		),
		listDatabaseSizes: connect.NewClient[v1.ListDatabaseSizesRequest, v1.ListDatabaseSizesResponse](
			httpClient,
			baseURL+DatabaseServiceListDatabaseSizesProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListDatabaseSizes")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseUsage: connect.NewClient[v1.GetDatabaseUsageRequest, v1.GetDatabaseUsageResponse](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseUsageProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseUsage")),
			connect.WithClientOptions(opts...),
		),
		createTable: connect.NewClient[v1.CreateTableRequest, v1.CreateTableResponse](
			httpClient,
			baseURL+DatabaseServiceCreateTableProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateTable")),
			connect.WithClientOptions(opts...),
		),
		alterTable: connect.NewClient[v1.AlterTableRequest, v1.AlterTableResponse](
			httpClient,
			baseURL+DatabaseServiceAlterTableProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("AlterTable")),
			connect.WithClientOptions(opts...),
		),
		dropTable: connect.NewClient[v1.DropTableRequest, v1.DropTableResponse](
			httpClient,
			baseURL+DatabaseServiceDropTableProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DropTable")),
			connect.WithClientOptions(opts...),
		),
		renameTable: connect.NewClient[v1.RenameTableRequest, v1.RenameTableResponse](
			httpClient,
			baseURL+DatabaseServiceRenameTableProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("RenameTable")),
			connect.WithClientOptions(opts...),
		),
		truncateTable: connect.NewClient[v1.TruncateTableRequest, v1.TruncateTableResponse](
			httpClient,
			baseURL+DatabaseServiceTruncateTableProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TruncateTable")),
			connect.WithClientOptions(opts...),
		),
		createIndex: connect.NewClient[v1.CreateIndexRequest, v1.CreateIndexResponse](
			httpClient,
			baseURL+DatabaseServiceCreateIndexProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateIndex")),
			connect.WithClientOptions(opts...),
		),
		dropIndex: connect.NewClient[v1.DropIndexRequest, v1.DropIndexResponse](
			httpClient,
			baseURL+DatabaseServiceDropIndexProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DropIndex")),
			connect.WithClientOptions(opts...),
		),
		getTableDDL: connect.NewClient[v1.GetTableDDLRequest, v1.GetTableDDLResponse](
			httpClient,
			baseURL+DatabaseServiceGetTableDDLProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetTableDDL")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	listDatabases             *connect.Client[v1.ListDatabasesRequest, v1.ListDatabasesResponse]
	createDatabase            *connect.Client[v1.CreateDatabaseRequest, v1.CreateDatabaseResponse]
	getDatabase               *connect.Client[v1.GetDatabaseRequest, v1.GetDatabaseResponse]
	updateDatabase            *connect.Client[v1.UpdateDatabaseRequest, v1.UpdateDatabaseResponse]
	deleteDatabase            *connect.Client[v1.DeleteDatabaseRequest, v1.DeleteDatabaseResponse]
	startDatabase             *connect.Client[v1.StartDatabaseRequest, v1.StartDatabaseResponse]
	stopDatabase              *connect.Client[v1.StopDatabaseRequest, v1.StopDatabaseResponse]
	sleepDatabase             *connect.Client[v1.SleepDatabaseRequest, v1.SleepDatabaseResponse]
	restartDatabase           *connect.Client[v1.RestartDatabaseRequest, v1.RestartDatabaseResponse]
	streamDatabaseStatus      *connect.Client[v1.StreamDatabaseStatusRequest, v1.DatabaseStatusUpdate]
	getDatabaseConnectionInfo *connect.Client[v1.GetDatabaseConnectionInfoRequest, v1.GetDatabaseConnectionInfoResponse]
	resetDatabasePassword     *connect.Client[v1.ResetDatabasePasswordRequest, v1.ResetDatabasePasswordResponse]
	getDatabaseSchema         *connect.Client[v1.GetDatabaseSchemaRequest, v1.GetDatabaseSchemaResponse]
	listTables                *connect.Client[v1.ListTablesRequest, v1.ListTablesResponse]
	getTableStructure         *connect.Client[v1.GetTableStructureRequest, v1.GetTableStructureResponse]
	executeQuery              *connect.Client[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse]
	streamQuery               *connect.Client[v1.StreamQueryRequest, v1.QueryResultRow]
	getTableData              *connect.Client[v1.GetTableDataRequest, v1.GetTableDataResponse]
	updateTableRow            *connect.Client[v1.UpdateTableRowRequest, v1.UpdateTableRowResponse]
	insertTableRow            *connect.Client[v1.InsertTableRowRequest, v1.InsertTableRowResponse]
	deleteTableRows           *connect.Client[v1.DeleteTableRowsRequest, v1.DeleteTableRowsResponse]
	listBackups               *connect.Client[v1.ListBackupsRequest, v1.ListBackupsResponse]
	createBackup              *connect.Client[v1.CreateBackupRequest, v1.CreateBackupResponse]
	getBackup                 *connect.Client[v1.GetBackupRequest, v1.GetBackupResponse]
	deleteBackup              *connect.Client[v1.DeleteBackupRequest, v1.DeleteBackupResponse]
	restoreBackup             *connect.Client[v1.RestoreBackupRequest, v1.RestoreBackupResponse]
	getDatabaseMetrics        *connect.Client[v1.GetDatabaseMetricsRequest, v1.GetDatabaseMetricsResponse]
	streamDatabaseMetrics     *connect.Client[v1.StreamDatabaseMetricsRequest, v1.DatabaseMetric]
	listDatabaseSizes         *connect.Client[v1.ListDatabaseSizesRequest, v1.ListDatabaseSizesResponse]
	getDatabaseUsage          *connect.Client[v1.GetDatabaseUsageRequest, v1.GetDatabaseUsageResponse]
	createTable               *connect.Client[v1.CreateTableRequest, v1.CreateTableResponse]
	alterTable                *connect.Client[v1.AlterTableRequest, v1.AlterTableResponse]
	dropTable                 *connect.Client[v1.DropTableRequest, v1.DropTableResponse]
	renameTable               *connect.Client[v1.RenameTableRequest, v1.RenameTableResponse]
	truncateTable             *connect.Client[v1.TruncateTableRequest, v1.TruncateTableResponse]
	createIndex               *connect.Client[v1.CreateIndexRequest, v1.CreateIndexResponse]
	dropIndex                 *connect.Client[v1.DropIndexRequest, v1.DropIndexResponse]
	getTableDDL               *connect.Client[v1.GetTableDDLRequest, v1.GetTableDDLResponse]
}

// ListDatabases calls obiente.cloud.databases.v1.DatabaseService.ListDatabases.
func (c *databaseServiceClient) ListDatabases(ctx context.Context, req *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return c.listDatabases.CallUnary(ctx, req)
}

// CreateDatabase calls obiente.cloud.databases.v1.DatabaseService.CreateDatabase.
func (c *databaseServiceClient) CreateDatabase(ctx context.Context, req *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error) {
	return c.createDatabase.CallUnary(ctx, req)
}

// GetDatabase calls obiente.cloud.databases.v1.DatabaseService.GetDatabase.
func (c *databaseServiceClient) GetDatabase(ctx context.Context, req *connect.Request[v1.GetDatabaseRequest]) (*connect.Response[v1.GetDatabaseResponse], error) {
	return c.getDatabase.CallUnary(ctx, req)
}

// UpdateDatabase calls obiente.cloud.databases.v1.DatabaseService.UpdateDatabase.
func (c *databaseServiceClient) UpdateDatabase(ctx context.Context, req *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error) {
	return c.updateDatabase.CallUnary(ctx, req)
}

// DeleteDatabase calls obiente.cloud.databases.v1.DatabaseService.DeleteDatabase.
func (c *databaseServiceClient) DeleteDatabase(ctx context.Context, req *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error) {
	return c.deleteDatabase.CallUnary(ctx, req)
}

// StartDatabase calls obiente.cloud.databases.v1.DatabaseService.StartDatabase.
func (c *databaseServiceClient) StartDatabase(ctx context.Context, req *connect.Request[v1.StartDatabaseRequest]) (*connect.Response[v1.StartDatabaseResponse], error) {
	return c.startDatabase.CallUnary(ctx, req)
}

// StopDatabase calls obiente.cloud.databases.v1.DatabaseService.StopDatabase.
func (c *databaseServiceClient) StopDatabase(ctx context.Context, req *connect.Request[v1.StopDatabaseRequest]) (*connect.Response[v1.StopDatabaseResponse], error) {
	return c.stopDatabase.CallUnary(ctx, req)
}

// SleepDatabase calls obiente.cloud.databases.v1.DatabaseService.SleepDatabase.
func (c *databaseServiceClient) SleepDatabase(ctx context.Context, req *connect.Request[v1.SleepDatabaseRequest]) (*connect.Response[v1.SleepDatabaseResponse], error) {
	return c.sleepDatabase.CallUnary(ctx, req)
}

// RestartDatabase calls obiente.cloud.databases.v1.DatabaseService.RestartDatabase.
func (c *databaseServiceClient) RestartDatabase(ctx context.Context, req *connect.Request[v1.RestartDatabaseRequest]) (*connect.Response[v1.RestartDatabaseResponse], error) {
	return c.restartDatabase.CallUnary(ctx, req)
}

// StreamDatabaseStatus calls obiente.cloud.databases.v1.DatabaseService.StreamDatabaseStatus.
func (c *databaseServiceClient) StreamDatabaseStatus(ctx context.Context, req *connect.Request[v1.StreamDatabaseStatusRequest]) (*connect.ServerStreamForClient[v1.DatabaseStatusUpdate], error) {
	return c.streamDatabaseStatus.CallServerStream(ctx, req)
}

// GetDatabaseConnectionInfo calls
// obiente.cloud.databases.v1.DatabaseService.GetDatabaseConnectionInfo.
func (c *databaseServiceClient) GetDatabaseConnectionInfo(ctx context.Context, req *connect.Request[v1.GetDatabaseConnectionInfoRequest]) (*connect.Response[v1.GetDatabaseConnectionInfoResponse], error) {
	return c.getDatabaseConnectionInfo.CallUnary(ctx, req)
}

// ResetDatabasePassword calls obiente.cloud.databases.v1.DatabaseService.ResetDatabasePassword.
func (c *databaseServiceClient) ResetDatabasePassword(ctx context.Context, req *connect.Request[v1.ResetDatabasePasswordRequest]) (*connect.Response[v1.ResetDatabasePasswordResponse], error) {
	return c.resetDatabasePassword.CallUnary(ctx, req)
}

// GetDatabaseSchema calls obiente.cloud.databases.v1.DatabaseService.GetDatabaseSchema.
func (c *databaseServiceClient) GetDatabaseSchema(ctx context.Context, req *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.GetDatabaseSchemaResponse], error) {
	return c.getDatabaseSchema.CallUnary(ctx, req)
}

// ListTables calls obiente.cloud.databases.v1.DatabaseService.ListTables.
func (c *databaseServiceClient) ListTables(ctx context.Context, req *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return c.listTables.CallUnary(ctx, req)
}

// GetTableStructure calls obiente.cloud.databases.v1.DatabaseService.GetTableStructure.
func (c *databaseServiceClient) GetTableStructure(ctx context.Context, req *connect.Request[v1.GetTableStructureRequest]) (*connect.Response[v1.GetTableStructureResponse], error) {
	return c.getTableStructure.CallUnary(ctx, req)
}

// ExecuteQuery calls obiente.cloud.databases.v1.DatabaseService.ExecuteQuery.
func (c *databaseServiceClient) ExecuteQuery(ctx context.Context, req *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return c.executeQuery.CallUnary(ctx, req)
}

// StreamQuery calls obiente.cloud.databases.v1.DatabaseService.StreamQuery.
func (c *databaseServiceClient) StreamQuery(ctx context.Context, req *connect.Request[v1.StreamQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResultRow], error) {
	return c.streamQuery.CallServerStream(ctx, req)
}

// GetTableData calls obiente.cloud.databases.v1.DatabaseService.GetTableData.
func (c *databaseServiceClient) GetTableData(ctx context.Context, req *connect.Request[v1.GetTableDataRequest]) (*connect.Response[v1.GetTableDataResponse], error) {
	return c.getTableData.CallUnary(ctx, req)
}

// UpdateTableRow calls obiente.cloud.databases.v1.DatabaseService.UpdateTableRow.
func (c *databaseServiceClient) UpdateTableRow(ctx context.Context, req *connect.Request[v1.UpdateTableRowRequest]) (*connect.Response[v1.UpdateTableRowResponse], error) {
	return c.updateTableRow.CallUnary(ctx, req)
}

// InsertTableRow calls obiente.cloud.databases.v1.DatabaseService.InsertTableRow.
func (c *databaseServiceClient) InsertTableRow(ctx context.Context, req *connect.Request[v1.InsertTableRowRequest]) (*connect.Response[v1.InsertTableRowResponse], error) {
	return c.insertTableRow.CallUnary(ctx, req)
}

// DeleteTableRows calls obiente.cloud.databases.v1.DatabaseService.DeleteTableRows.
func (c *databaseServiceClient) DeleteTableRows(ctx context.Context, req *connect.Request[v1.DeleteTableRowsRequest]) (*connect.Response[v1.DeleteTableRowsResponse], error) {
	return c.deleteTableRows.CallUnary(ctx, req)
}

// ListBackups calls obiente.cloud.databases.v1.DatabaseService.ListBackups.
func (c *databaseServiceClient) ListBackups(ctx context.Context, req *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResponse], error) {
	return c.listBackups.CallUnary(ctx, req)
}

// CreateBackup calls obiente.cloud.databases.v1.DatabaseService.CreateBackup.
func (c *databaseServiceClient) CreateBackup(ctx context.Context, req *connect.Request[v1.CreateBackupRequest]) (*connect.Response[v1.CreateBackupResponse], error) {
	return c.createBackup.CallUnary(ctx, req)
}

// GetBackup calls obiente.cloud.databases.v1.DatabaseService.GetBackup.
func (c *databaseServiceClient) GetBackup(ctx context.Context, req *connect.Request[v1.GetBackupRequest]) (*connect.Response[v1.GetBackupResponse], error) {
	return c.getBackup.CallUnary(ctx, req)
}

// DeleteBackup calls obiente.cloud.databases.v1.DatabaseService.DeleteBackup.
func (c *databaseServiceClient) DeleteBackup(ctx context.Context, req *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResponse], error) {
	return c.deleteBackup.CallUnary(ctx, req)
}

// RestoreBackup calls obiente.cloud.databases.v1.DatabaseService.RestoreBackup.
func (c *databaseServiceClient) RestoreBackup(ctx context.Context, req *connect.Request[v1.RestoreBackupRequest]) (*connect.Response[v1.RestoreBackupResponse], error) {
	return c.restoreBackup.CallUnary(ctx, req)
}

// GetDatabaseMetrics calls obiente.cloud.databases.v1.DatabaseService.GetDatabaseMetrics.
func (c *databaseServiceClient) GetDatabaseMetrics(ctx context.Context, req *connect.Request[v1.GetDatabaseMetricsRequest]) (*connect.Response[v1.GetDatabaseMetricsResponse], error) {
	return c.getDatabaseMetrics.CallUnary(ctx, req)
}

// StreamDatabaseMetrics calls obiente.cloud.databases.v1.DatabaseService.StreamDatabaseMetrics.
func (c *databaseServiceClient) StreamDatabaseMetrics(ctx context.Context, req *connect.Request[v1.StreamDatabaseMetricsRequest]) (*connect.ServerStreamForClient[v1.DatabaseMetric], error) {
	return c.streamDatabaseMetrics.CallServerStream(ctx, req)
}

// ListDatabaseSizes calls obiente.cloud.databases.v1.DatabaseService.ListDatabaseSizes.
func (c *databaseServiceClient) ListDatabaseSizes(ctx context.Context, req *connect.Request[v1.ListDatabaseSizesRequest]) (*connect.Response[v1.ListDatabaseSizesResponse], error) {
	return c.listDatabaseSizes.CallUnary(ctx, req)
}

// GetDatabaseUsage calls obiente.cloud.databases.v1.DatabaseService.GetDatabaseUsage.
func (c *databaseServiceClient) GetDatabaseUsage(ctx context.Context, req *connect.Request[v1.GetDatabaseUsageRequest]) (*connect.Response[v1.GetDatabaseUsageResponse], error) {
	return c.getDatabaseUsage.CallUnary(ctx, req)
}

// CreateTable calls obiente.cloud.databases.v1.DatabaseService.CreateTable.
func (c *databaseServiceClient) CreateTable(ctx context.Context, req *connect.Request[v1.CreateTableRequest]) (*connect.Response[v1.CreateTableResponse], error) {
	return c.createTable.CallUnary(ctx, req)
}

// AlterTable calls obiente.cloud.databases.v1.DatabaseService.AlterTable.
func (c *databaseServiceClient) AlterTable(ctx context.Context, req *connect.Request[v1.AlterTableRequest]) (*connect.Response[v1.AlterTableResponse], error) {
	return c.alterTable.CallUnary(ctx, req)
}

// DropTable calls obiente.cloud.databases.v1.DatabaseService.DropTable.
func (c *databaseServiceClient) DropTable(ctx context.Context, req *connect.Request[v1.DropTableRequest]) (*connect.Response[v1.DropTableResponse], error) {
	return c.dropTable.CallUnary(ctx, req)
}

// RenameTable calls obiente.cloud.databases.v1.DatabaseService.RenameTable.
func (c *databaseServiceClient) RenameTable(ctx context.Context, req *connect.Request[v1.RenameTableRequest]) (*connect.Response[v1.RenameTableResponse], error) {
	return c.renameTable.CallUnary(ctx, req)
}

// TruncateTable calls obiente.cloud.databases.v1.DatabaseService.TruncateTable.
func (c *databaseServiceClient) TruncateTable(ctx context.Context, req *connect.Request[v1.TruncateTableRequest]) (*connect.Response[v1.TruncateTableResponse], error) {
	return c.truncateTable.CallUnary(ctx, req)
}

// CreateIndex calls obiente.cloud.databases.v1.DatabaseService.CreateIndex.
func (c *databaseServiceClient) CreateIndex(ctx context.Context, req *connect.Request[v1.CreateIndexRequest]) (*connect.Response[v1.CreateIndexResponse], error) {
	return c.createIndex.CallUnary(ctx, req)
}

// DropIndex calls obiente.cloud.databases.v1.DatabaseService.DropIndex.
func (c *databaseServiceClient) DropIndex(ctx context.Context, req *connect.Request[v1.DropIndexRequest]) (*connect.Response[v1.DropIndexResponse], error) {
	return c.dropIndex.CallUnary(ctx, req)
}

// GetTableDDL calls obiente.cloud.databases.v1.DatabaseService.GetTableDDL.
func (c *databaseServiceClient) GetTableDDL(ctx context.Context, req *connect.Request[v1.GetTableDDLRequest]) (*connect.Response[v1.GetTableDDLResponse], error) {
	return c.getTableDDL.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the obiente.cloud.databases.v1.DatabaseService
// service.
type DatabaseServiceHandler interface {
	// List organization databases
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// Create new database instance
	CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error)
	// Get database instance details
	GetDatabase(context.Context, *connect.Request[v1.GetDatabaseRequest]) (*connect.Response[v1.GetDatabaseResponse], error)
	// Update database instance configuration
	UpdateDatabase(context.Context, *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error)
	// Delete database instance
	DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error)
	// Start a stopped database instance
	StartDatabase(context.Context, *connect.Request[v1.StartDatabaseRequest]) (*connect.Response[v1.StartDatabaseResponse], error)
	// Stop a running database instance
	StopDatabase(context.Context, *connect.Request[v1.StopDatabaseRequest]) (*connect.Response[v1.StopDatabaseResponse], error)
	// Put a database to sleep (auto-wakes on connection)
	SleepDatabase(context.Context, *connect.Request[v1.SleepDatabaseRequest]) (*connect.Response[v1.SleepDatabaseResponse], error)
	// Restart a database instance
	RestartDatabase(context.Context, *connect.Request[v1.RestartDatabaseRequest]) (*connect.Response[v1.RestartDatabaseResponse], error)
	// Stream database status updates
	StreamDatabaseStatus(context.Context, *connect.Request[v1.StreamDatabaseStatusRequest], *connect.ServerStream[v1.DatabaseStatusUpdate]) error
	// Get database connection info (credentials, connection strings)
	GetDatabaseConnectionInfo(context.Context, *connect.Request[v1.GetDatabaseConnectionInfoRequest]) (*connect.Response[v1.GetDatabaseConnectionInfoResponse], error)
	// Reset database password
	ResetDatabasePassword(context.Context, *connect.Request[v1.ResetDatabasePasswordRequest]) (*connect.Response[v1.ResetDatabasePasswordResponse], error)
	// Database introspection - get schema information
	GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.GetDatabaseSchemaResponse], error)
	// List tables in a database
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// Get table structure/details
	GetTableStructure(context.Context, *connect.Request[v1.GetTableStructureRequest]) (*connect.Response[v1.GetTableStructureResponse], error)
	// Execute query on database
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	// Stream query results (for large result sets)
	StreamQuery(context.Context, *connect.Request[v1.StreamQueryRequest], *connect.ServerStream[v1.QueryResultRow]) error
	// Table data browsing and editing
	GetTableData(context.Context, *connect.Request[v1.GetTableDataRequest]) (*connect.Response[v1.GetTableDataResponse], error)
	UpdateTableRow(context.Context, *connect.Request[v1.UpdateTableRowRequest]) (*connect.Response[v1.UpdateTableRowResponse], error)
	InsertTableRow(context.Context, *connect.Request[v1.InsertTableRowRequest]) (*connect.Response[v1.InsertTableRowResponse], error)
	DeleteTableRows(context.Context, *connect.Request[v1.DeleteTableRowsRequest]) (*connect.Response[v1.DeleteTableRowsResponse], error)
	// Backup management
	ListBackups(context.Context, *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResponse], error)
	CreateBackup(context.Context, *connect.Request[v1.CreateBackupRequest]) (*connect.Response[v1.CreateBackupResponse], error)
	GetBackup(context.Context, *connect.Request[v1.GetBackupRequest]) (*connect.Response[v1.GetBackupResponse], error)
	DeleteBackup(context.Context, *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResponse], error)
	RestoreBackup(context.Context, *connect.Request[v1.RestoreBackupRequest]) (*connect.Response[v1.RestoreBackupResponse], error)
	// Get database metrics
	GetDatabaseMetrics(context.Context, *connect.Request[v1.GetDatabaseMetricsRequest]) (*connect.Response[v1.GetDatabaseMetricsResponse], error)
	// Stream real-time database metrics
	StreamDatabaseMetrics(context.Context, *connect.Request[v1.StreamDatabaseMetricsRequest], *connect.ServerStream[v1.DatabaseMetric]) error
	// Get available database sizes/pricing
	ListDatabaseSizes(context.Context, *connect.Request[v1.ListDatabaseSizesRequest]) (*connect.Response[v1.ListDatabaseSizesResponse], error)
	// Get database usage and billing information
	GetDatabaseUsage(context.Context, *connect.Request[v1.GetDatabaseUsageRequest]) (*connect.Response[v1.GetDatabaseUsageResponse], error)
	// Schema DDL operations
	CreateTable(context.Context, *connect.Request[v1.CreateTableRequest]) (*connect.Response[v1.CreateTableResponse], error)
	AlterTable(context.Context, *connect.Request[v1.AlterTableRequest]) (*connect.Response[v1.AlterTableResponse], error)
	DropTable(context.Context, *connect.Request[v1.DropTableRequest]) (*connect.Response[v1.DropTableResponse], error)
	RenameTable(context.Context, *connect.Request[v1.RenameTableRequest]) (*connect.Response[v1.RenameTableResponse], error)
	TruncateTable(context.Context, *connect.Request[v1.TruncateTableRequest]) (*connect.Response[v1.TruncateTableResponse], error)
	// Index management
	CreateIndex(context.Context, *connect.Request[v1.CreateIndexRequest]) (*connect.Response[v1.CreateIndexResponse], error)
	DropIndex(context.Context, *connect.Request[v1.DropIndexRequest]) (*connect.Response[v1.DropIndexResponse], error)
	// Get DDL statement for a table
	GetTableDDL(context.Context, *connect.Request[v1.GetTableDDLRequest]) (*connect.Response[v1.GetTableDDLResponse], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := v1.File_obiente_cloud_databases_v1_database_service_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceListDatabasesHandler := connect.NewUnaryHandler(
		DatabaseServiceListDatabasesProcedure,
		svc.ListDatabases,
		connect.WithSchema(databaseServiceMethods.ByName("ListDatabases")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCreateDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateDatabaseProcedure,
		svc.CreateDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("CreateDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseProcedure,
		svc.GetDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceUpdateDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceUpdateDatabaseProcedure,
		svc.UpdateDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("UpdateDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDeleteDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceDeleteDatabaseProcedure,
		svc.DeleteDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("DeleteDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceStartDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceStartDatabaseProcedure,
		svc.StartDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("StartDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceStopDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceStopDatabaseProcedure,
		svc.StopDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("StopDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceSleepDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceSleepDatabaseProcedure,
		svc.SleepDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("SleepDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRestartDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceRestartDatabaseProcedure,
		svc.RestartDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("RestartDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceStreamDatabaseStatusHandler := connect.NewServerStreamHandler(
		DatabaseServiceStreamDatabaseStatusProcedure,
		svc.StreamDatabaseStatus,
		connect.WithSchema(databaseServiceMethods.ByName("StreamDatabaseStatus")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseConnectionInfoHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseConnectionInfoProcedure,
		svc.GetDatabaseConnectionInfo,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseConnectionInfo")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceResetDatabasePasswordHandler := connect.NewUnaryHandler(
		DatabaseServiceResetDatabasePasswordProcedure,
		svc.ResetDatabasePassword,
		connect.WithSchema(databaseServiceMethods.ByName("ResetDatabasePassword")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseSchemaHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseSchemaProcedure,
		svc.GetDatabaseSchema,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseSchema")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListTablesHandler := connect.NewUnaryHandler(
		DatabaseServiceListTablesProcedure,
		svc.ListTables,
		connect.WithSchema(databaseServiceMethods.ByName("ListTables")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetTableStructureHandler := connect.NewUnaryHandler(
		DatabaseServiceGetTableStructureProcedure,
		svc.GetTableStructure,
		connect.WithSchema(databaseServiceMethods.ByName("GetTableStructure")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExecuteQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceExecuteQueryProcedure,
		svc.ExecuteQuery,
		connect.WithSchema(databaseServiceMethods.ByName("ExecuteQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceStreamQueryHandler := connect.NewServerStreamHandler(
		DatabaseServiceStreamQueryProcedure,
		svc.StreamQuery,
		connect.WithSchema(databaseServiceMethods.ByName("StreamQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetTableDataHandler := connect.NewUnaryHandler(
		DatabaseServiceGetTableDataProcedure,
		svc.GetTableData,
		connect.WithSchema(databaseServiceMethods.ByName("GetTableData")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceUpdateTableRowHandler := connect.NewUnaryHandler(
		DatabaseServiceUpdateTableRowProcedure,
		svc.UpdateTableRow,
		connect.WithSchema(databaseServiceMethods.ByName("UpdateTableRow")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceInsertTableRowHandler := connect.NewUnaryHandler(
		DatabaseServiceInsertTableRowProcedure,
		svc.InsertTableRow,
		connect.WithSchema(databaseServiceMethods.ByName("InsertTableRow")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDeleteTableRowsHandler := connect.NewUnaryHandler(
		DatabaseServiceDeleteTableRowsProcedure,
		svc.DeleteTableRows,
		connect.WithSchema(databaseServiceMethods.ByName("DeleteTableRows")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListBackupsHandler := connect.NewUnaryHandler(
		DatabaseServiceListBackupsProcedure,
		svc.ListBackups,
		connect.WithSchema(databaseServiceMethods.ByName("ListBackups")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCreateBackupHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateBackupProcedure,
		svc.CreateBackup,
		connect.WithSchema(databaseServiceMethods.ByName("CreateBackup")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetBackupHandler := connect.NewUnaryHandler(
		DatabaseServiceGetBackupProcedure,
		svc.GetBackup,
		connect.WithSchema(databaseServiceMethods.ByName("GetBackup")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDeleteBackupHandler := connect.NewUnaryHandler(
		DatabaseServiceDeleteBackupProcedure,
		svc.DeleteBackup,
		connect.WithSchema(databaseServiceMethods.ByName("DeleteBackup")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRestoreBackupHandler := connect.NewUnaryHandler(
		DatabaseServiceRestoreBackupProcedure,
		svc.RestoreBackup,
		connect.WithSchema(databaseServiceMethods.ByName("RestoreBackup")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseMetricsHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseMetricsProcedure,
		svc.GetDatabaseMetrics,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceStreamDatabaseMetricsHandler := connect.NewServerStreamHandler(
		DatabaseServiceStreamDatabaseMetricsProcedure,
		svc.StreamDatabaseMetrics,
		connect.WithSchema(databaseServiceMethods.ByName("StreamDatabaseMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListDatabaseSizesHandler := connect.NewUnaryHandler(
		DatabaseServiceListDatabaseSizesProcedure,
		svc.ListDatabaseSizes,
		connect.WithSchema(databaseServiceMethods.ByName("ListDatabaseSizes")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseUsageHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseUsageProcedure,
		svc.GetDatabaseUsage,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseUsage")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCreateTableHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateTableProcedure,
		svc.CreateTable,
		connect.WithSchema(databaseServiceMethods.ByName("CreateTable")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceAlterTableHandler := connect.NewUnaryHandler(
		DatabaseServiceAlterTableProcedure,
		svc.AlterTable,
		connect.WithSchema(databaseServiceMethods.ByName("AlterTable")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDropTableHandler := connect.NewUnaryHandler(
		DatabaseServiceDropTableProcedure,
		svc.DropTable,
		connect.WithSchema(databaseServiceMethods.ByName("DropTable")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRenameTableHandler := connect.NewUnaryHandler(
		DatabaseServiceRenameTableProcedure,
		svc.RenameTable,
		connect.WithSchema(databaseServiceMethods.ByName("RenameTable")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTruncateTableHandler := connect.NewUnaryHandler(
		DatabaseServiceTruncateTableProcedure,
		svc.TruncateTable,
		connect.WithSchema(databaseServiceMethods.ByName("TruncateTable")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCreateIndexHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateIndexProcedure,
		svc.CreateIndex,
		connect.WithSchema(databaseServiceMethods.ByName("CreateIndex")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDropIndexHandler := connect.NewUnaryHandler(
		DatabaseServiceDropIndexProcedure,
		svc.DropIndex,
		connect.WithSchema(databaseServiceMethods.ByName("DropIndex")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetTableDDLHandler := connect.NewUnaryHandler(
		DatabaseServiceGetTableDDLProcedure,
		svc.GetTableDDL,
		connect.WithSchema(databaseServiceMethods.ByName("GetTableDDL")),
		connect.WithHandlerOptions(opts...),
	)
	return "/obiente.cloud.databases.v1.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceListDatabasesProcedure:
			databaseServiceListDatabasesHandler.ServeHTTP(w, r)
		case DatabaseServiceCreateDatabaseProcedure:
			databaseServiceCreateDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseProcedure:
			databaseServiceGetDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceUpdateDatabaseProcedure:
			databaseServiceUpdateDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceDeleteDatabaseProcedure:
			databaseServiceDeleteDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceStartDatabaseProcedure:
			databaseServiceStartDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceStopDatabaseProcedure:
			databaseServiceStopDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceSleepDatabaseProcedure:
			databaseServiceSleepDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceRestartDatabaseProcedure:
			databaseServiceRestartDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceStreamDatabaseStatusProcedure:
			databaseServiceStreamDatabaseStatusHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseConnectionInfoProcedure:
			databaseServiceGetDatabaseConnectionInfoHandler.ServeHTTP(w, r)
		case DatabaseServiceResetDatabasePasswordProcedure:
			databaseServiceResetDatabasePasswordHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseSchemaProcedure:
			databaseServiceGetDatabaseSchemaHandler.ServeHTTP(w, r)
		case DatabaseServiceListTablesProcedure:
			databaseServiceListTablesHandler.ServeHTTP(w, r)
		case DatabaseServiceGetTableStructureProcedure:
			databaseServiceGetTableStructureHandler.ServeHTTP(w, r)
		case DatabaseServiceExecuteQueryProcedure:
			databaseServiceExecuteQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceStreamQueryProcedure:
			databaseServiceStreamQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceGetTableDataProcedure:
			databaseServiceGetTableDataHandler.ServeHTTP(w, r)
		case DatabaseServiceUpdateTableRowProcedure:
			databaseServiceUpdateTableRowHandler.ServeHTTP(w, r)
		case DatabaseServiceInsertTableRowProcedure:
			databaseServiceInsertTableRowHandler.ServeHTTP(w, r)
		case DatabaseServiceDeleteTableRowsProcedure:
			databaseServiceDeleteTableRowsHandler.ServeHTTP(w, r)
		case DatabaseServiceListBackupsProcedure:
			databaseServiceListBackupsHandler.ServeHTTP(w, r)
		case DatabaseServiceCreateBackupProcedure:
			databaseServiceCreateBackupHandler.ServeHTTP(w, r)
		case DatabaseServiceGetBackupProcedure:
			databaseServiceGetBackupHandler.ServeHTTP(w, r)
		case DatabaseServiceDeleteBackupProcedure:
			databaseServiceDeleteBackupHandler.ServeHTTP(w, r)
		case DatabaseServiceRestoreBackupProcedure:
			databaseServiceRestoreBackupHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseMetricsProcedure:
			databaseServiceGetDatabaseMetricsHandler.ServeHTTP(w, r)
		case DatabaseServiceStreamDatabaseMetricsProcedure:
			databaseServiceStreamDatabaseMetricsHandler.ServeHTTP(w, r)
		case DatabaseServiceListDatabaseSizesProcedure:
			databaseServiceListDatabaseSizesHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseUsageProcedure:
			databaseServiceGetDatabaseUsageHandler.ServeHTTP(w, r)
		case DatabaseServiceCreateTableProcedure:
			databaseServiceCreateTableHandler.ServeHTTP(w, r)
		case DatabaseServiceAlterTableProcedure:
			databaseServiceAlterTableHandler.ServeHTTP(w, r)
		case DatabaseServiceDropTableProcedure:
			databaseServiceDropTableHandler.ServeHTTP(w, r)
		case DatabaseServiceRenameTableProcedure:
			databaseServiceRenameTableHandler.ServeHTTP(w, r)
		case DatabaseServiceTruncateTableProcedure:
			databaseServiceTruncateTableHandler.ServeHTTP(w, r)
		case DatabaseServiceCreateIndexProcedure:
			databaseServiceCreateIndexHandler.ServeHTTP(w, r)
		case DatabaseServiceDropIndexProcedure:
			databaseServiceDropIndexHandler.ServeHTTP(w, r)
		case DatabaseServiceGetTableDDLProcedure:
			databaseServiceGetTableDDLHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.ListDatabases is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.CreateDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabase(context.Context, *connect.Request[v1.GetDatabaseRequest]) (*connect.Response[v1.GetDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) UpdateDatabase(context.Context, *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.UpdateDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.DeleteDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) StartDatabase(context.Context, *connect.Request[v1.StartDatabaseRequest]) (*connect.Response[v1.StartDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.StartDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) StopDatabase(context.Context, *connect.Request[v1.StopDatabaseRequest]) (*connect.Response[v1.StopDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.StopDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) SleepDatabase(context.Context, *connect.Request[v1.SleepDatabaseRequest]) (*connect.Response[v1.SleepDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.SleepDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) RestartDatabase(context.Context, *connect.Request[v1.RestartDatabaseRequest]) (*connect.Response[v1.RestartDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.RestartDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) StreamDatabaseStatus(context.Context, *connect.Request[v1.StreamDatabaseStatusRequest], *connect.ServerStream[v1.DatabaseStatusUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.StreamDatabaseStatus is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabaseConnectionInfo(context.Context, *connect.Request[v1.GetDatabaseConnectionInfoRequest]) (*connect.Response[v1.GetDatabaseConnectionInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetDatabaseConnectionInfo is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ResetDatabasePassword(context.Context, *connect.Request[v1.ResetDatabasePasswordRequest]) (*connect.Response[v1.ResetDatabasePasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.ResetDatabasePassword is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.GetDatabaseSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetDatabaseSchema is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.ListTables is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetTableStructure(context.Context, *connect.Request[v1.GetTableStructureRequest]) (*connect.Response[v1.GetTableStructureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetTableStructure is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.ExecuteQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) StreamQuery(context.Context, *connect.Request[v1.StreamQueryRequest], *connect.ServerStream[v1.QueryResultRow]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.StreamQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetTableData(context.Context, *connect.Request[v1.GetTableDataRequest]) (*connect.Response[v1.GetTableDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetTableData is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) UpdateTableRow(context.Context, *connect.Request[v1.UpdateTableRowRequest]) (*connect.Response[v1.UpdateTableRowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.UpdateTableRow is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) InsertTableRow(context.Context, *connect.Request[v1.InsertTableRowRequest]) (*connect.Response[v1.InsertTableRowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.InsertTableRow is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DeleteTableRows(context.Context, *connect.Request[v1.DeleteTableRowsRequest]) (*connect.Response[v1.DeleteTableRowsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.DeleteTableRows is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListBackups(context.Context, *connect.Request[v1.ListBackupsRequest]) (*connect.Response[v1.ListBackupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.ListBackups is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CreateBackup(context.Context, *connect.Request[v1.CreateBackupRequest]) (*connect.Response[v1.CreateBackupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.CreateBackup is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetBackup(context.Context, *connect.Request[v1.GetBackupRequest]) (*connect.Response[v1.GetBackupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetBackup is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DeleteBackup(context.Context, *connect.Request[v1.DeleteBackupRequest]) (*connect.Response[v1.DeleteBackupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.DeleteBackup is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) RestoreBackup(context.Context, *connect.Request[v1.RestoreBackupRequest]) (*connect.Response[v1.RestoreBackupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.RestoreBackup is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabaseMetrics(context.Context, *connect.Request[v1.GetDatabaseMetricsRequest]) (*connect.Response[v1.GetDatabaseMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetDatabaseMetrics is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) StreamDatabaseMetrics(context.Context, *connect.Request[v1.StreamDatabaseMetricsRequest], *connect.ServerStream[v1.DatabaseMetric]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.StreamDatabaseMetrics is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListDatabaseSizes(context.Context, *connect.Request[v1.ListDatabaseSizesRequest]) (*connect.Response[v1.ListDatabaseSizesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.ListDatabaseSizes is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabaseUsage(context.Context, *connect.Request[v1.GetDatabaseUsageRequest]) (*connect.Response[v1.GetDatabaseUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetDatabaseUsage is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CreateTable(context.Context, *connect.Request[v1.CreateTableRequest]) (*connect.Response[v1.CreateTableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.CreateTable is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) AlterTable(context.Context, *connect.Request[v1.AlterTableRequest]) (*connect.Response[v1.AlterTableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.AlterTable is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DropTable(context.Context, *connect.Request[v1.DropTableRequest]) (*connect.Response[v1.DropTableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.DropTable is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) RenameTable(context.Context, *connect.Request[v1.RenameTableRequest]) (*connect.Response[v1.RenameTableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.RenameTable is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TruncateTable(context.Context, *connect.Request[v1.TruncateTableRequest]) (*connect.Response[v1.TruncateTableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.TruncateTable is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CreateIndex(context.Context, *connect.Request[v1.CreateIndexRequest]) (*connect.Response[v1.CreateIndexResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.CreateIndex is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DropIndex(context.Context, *connect.Request[v1.DropIndexRequest]) (*connect.Response[v1.DropIndexResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.DropIndex is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetTableDDL(context.Context, *connect.Request[v1.GetTableDDLRequest]) (*connect.Response[v1.GetTableDDLResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.databases.v1.DatabaseService.GetTableDDL is not implemented"))
}
