// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: obiente/cloud/vps/v1/vps_config_service.proto

package vpsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/obiente/cloud/apps/shared/proto/obiente/cloud/vps/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VPSConfigServiceName is the fully-qualified name of the VPSConfigService service.
	VPSConfigServiceName = "obiente.cloud.vps.v1.VPSConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VPSConfigServiceGetCloudInitConfigProcedure is the fully-qualified name of the VPSConfigService's
	// GetCloudInitConfig RPC.
	VPSConfigServiceGetCloudInitConfigProcedure = "/obiente.cloud.vps.v1.VPSConfigService/GetCloudInitConfig"
	// VPSConfigServiceUpdateCloudInitConfigProcedure is the fully-qualified name of the
	// VPSConfigService's UpdateCloudInitConfig RPC.
	VPSConfigServiceUpdateCloudInitConfigProcedure = "/obiente.cloud.vps.v1.VPSConfigService/UpdateCloudInitConfig"
	// VPSConfigServiceListVPSUsersProcedure is the fully-qualified name of the VPSConfigService's
	// ListVPSUsers RPC.
	VPSConfigServiceListVPSUsersProcedure = "/obiente.cloud.vps.v1.VPSConfigService/ListVPSUsers"
	// VPSConfigServiceCreateVPSUserProcedure is the fully-qualified name of the VPSConfigService's
	// CreateVPSUser RPC.
	VPSConfigServiceCreateVPSUserProcedure = "/obiente.cloud.vps.v1.VPSConfigService/CreateVPSUser"
	// VPSConfigServiceUpdateVPSUserProcedure is the fully-qualified name of the VPSConfigService's
	// UpdateVPSUser RPC.
	VPSConfigServiceUpdateVPSUserProcedure = "/obiente.cloud.vps.v1.VPSConfigService/UpdateVPSUser"
	// VPSConfigServiceDeleteVPSUserProcedure is the fully-qualified name of the VPSConfigService's
	// DeleteVPSUser RPC.
	VPSConfigServiceDeleteVPSUserProcedure = "/obiente.cloud.vps.v1.VPSConfigService/DeleteVPSUser"
	// VPSConfigServiceSetUserPasswordProcedure is the fully-qualified name of the VPSConfigService's
	// SetUserPassword RPC.
	VPSConfigServiceSetUserPasswordProcedure = "/obiente.cloud.vps.v1.VPSConfigService/SetUserPassword"
	// VPSConfigServiceUpdateUserSSHKeysProcedure is the fully-qualified name of the VPSConfigService's
	// UpdateUserSSHKeys RPC.
	VPSConfigServiceUpdateUserSSHKeysProcedure = "/obiente.cloud.vps.v1.VPSConfigService/UpdateUserSSHKeys"
	// VPSConfigServiceRotateTerminalKeyProcedure is the fully-qualified name of the VPSConfigService's
	// RotateTerminalKey RPC.
	VPSConfigServiceRotateTerminalKeyProcedure = "/obiente.cloud.vps.v1.VPSConfigService/RotateTerminalKey"
	// VPSConfigServiceRemoveTerminalKeyProcedure is the fully-qualified name of the VPSConfigService's
	// RemoveTerminalKey RPC.
	VPSConfigServiceRemoveTerminalKeyProcedure = "/obiente.cloud.vps.v1.VPSConfigService/RemoveTerminalKey"
	// VPSConfigServiceGetTerminalKeyProcedure is the fully-qualified name of the VPSConfigService's
	// GetTerminalKey RPC.
	VPSConfigServiceGetTerminalKeyProcedure = "/obiente.cloud.vps.v1.VPSConfigService/GetTerminalKey"
	// VPSConfigServiceRotateBastionKeyProcedure is the fully-qualified name of the VPSConfigService's
	// RotateBastionKey RPC.
	VPSConfigServiceRotateBastionKeyProcedure = "/obiente.cloud.vps.v1.VPSConfigService/RotateBastionKey"
	// VPSConfigServiceGetBastionKeyProcedure is the fully-qualified name of the VPSConfigService's
	// GetBastionKey RPC.
	VPSConfigServiceGetBastionKeyProcedure = "/obiente.cloud.vps.v1.VPSConfigService/GetBastionKey"
)

// VPSConfigServiceClient is a client for the obiente.cloud.vps.v1.VPSConfigService service.
type VPSConfigServiceClient interface {
	// Get cloud-init configuration for a VPS instance
	GetCloudInitConfig(context.Context, *connect.Request[v1.GetCloudInitConfigRequest]) (*connect.Response[v1.GetCloudInitConfigResponse], error)
	// Update cloud-init configuration for a VPS instance
	UpdateCloudInitConfig(context.Context, *connect.Request[v1.UpdateCloudInitConfigRequest]) (*connect.Response[v1.UpdateCloudInitConfigResponse], error)
	// List users configured for a VPS instance
	ListVPSUsers(context.Context, *connect.Request[v1.ListVPSUsersRequest]) (*connect.Response[v1.ListVPSUsersResponse], error)
	// Create a new user on a VPS instance
	CreateVPSUser(context.Context, *connect.Request[v1.CreateVPSUserRequest]) (*connect.Response[v1.CreateVPSUserResponse], error)
	// Update an existing user on a VPS instance
	UpdateVPSUser(context.Context, *connect.Request[v1.UpdateVPSUserRequest]) (*connect.Response[v1.UpdateVPSUserResponse], error)
	// Delete a user from a VPS instance
	DeleteVPSUser(context.Context, *connect.Request[v1.DeleteVPSUserRequest]) (*connect.Response[v1.DeleteVPSUserResponse], error)
	// Set or reset password for a user
	SetUserPassword(context.Context, *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error)
	// Manage SSH keys for a specific user
	UpdateUserSSHKeys(context.Context, *connect.Request[v1.UpdateUserSSHKeysRequest]) (*connect.Response[v1.UpdateUserSSHKeysResponse], error)
	// Rotate the web terminal SSH key for a VPS instance
	RotateTerminalKey(context.Context, *connect.Request[v1.RotateTerminalKeyRequest]) (*connect.Response[v1.RotateTerminalKeyResponse], error)
	// Remove the web terminal SSH key for a VPS instance
	RemoveTerminalKey(context.Context, *connect.Request[v1.RemoveTerminalKeyRequest]) (*connect.Response[v1.RemoveTerminalKeyResponse], error)
	// Get the web terminal SSH key status for a VPS instance
	GetTerminalKey(context.Context, *connect.Request[v1.GetTerminalKeyRequest]) (*connect.Response[v1.GetTerminalKeyResponse], error)
	// Rotate the bastion SSH key for a VPS instance
	RotateBastionKey(context.Context, *connect.Request[v1.RotateBastionKeyRequest]) (*connect.Response[v1.RotateBastionKeyResponse], error)
	// Get the bastion SSH key status for a VPS instance
	GetBastionKey(context.Context, *connect.Request[v1.GetBastionKeyRequest]) (*connect.Response[v1.GetBastionKeyResponse], error)
}

// NewVPSConfigServiceClient constructs a client for the obiente.cloud.vps.v1.VPSConfigService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVPSConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VPSConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	vPSConfigServiceMethods := v1.File_obiente_cloud_vps_v1_vps_config_service_proto.Services().ByName("VPSConfigService").Methods()
	return &vPSConfigServiceClient{
		getCloudInitConfig: connect.NewClient[v1.GetCloudInitConfigRequest, v1.GetCloudInitConfigResponse](
			httpClient,
			baseURL+VPSConfigServiceGetCloudInitConfigProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("GetCloudInitConfig")),
			connect.WithClientOptions(opts...),
		),
		updateCloudInitConfig: connect.NewClient[v1.UpdateCloudInitConfigRequest, v1.UpdateCloudInitConfigResponse](
			httpClient,
			baseURL+VPSConfigServiceUpdateCloudInitConfigProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("UpdateCloudInitConfig")),
			connect.WithClientOptions(opts...),
		),
		listVPSUsers: connect.NewClient[v1.ListVPSUsersRequest, v1.ListVPSUsersResponse](
			httpClient,
			baseURL+VPSConfigServiceListVPSUsersProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("ListVPSUsers")),
			connect.WithClientOptions(opts...),
		),
		createVPSUser: connect.NewClient[v1.CreateVPSUserRequest, v1.CreateVPSUserResponse](
			httpClient,
			baseURL+VPSConfigServiceCreateVPSUserProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("CreateVPSUser")),
			connect.WithClientOptions(opts...),
		),
		updateVPSUser: connect.NewClient[v1.UpdateVPSUserRequest, v1.UpdateVPSUserResponse](
			httpClient,
			baseURL+VPSConfigServiceUpdateVPSUserProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("UpdateVPSUser")),
			connect.WithClientOptions(opts...),
		),
		deleteVPSUser: connect.NewClient[v1.DeleteVPSUserRequest, v1.DeleteVPSUserResponse](
			httpClient,
			baseURL+VPSConfigServiceDeleteVPSUserProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("DeleteVPSUser")),
			connect.WithClientOptions(opts...),
		),
		setUserPassword: connect.NewClient[v1.SetUserPasswordRequest, v1.SetUserPasswordResponse](
			httpClient,
			baseURL+VPSConfigServiceSetUserPasswordProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("SetUserPassword")),
			connect.WithClientOptions(opts...),
		),
		updateUserSSHKeys: connect.NewClient[v1.UpdateUserSSHKeysRequest, v1.UpdateUserSSHKeysResponse](
			httpClient,
			baseURL+VPSConfigServiceUpdateUserSSHKeysProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("UpdateUserSSHKeys")),
			connect.WithClientOptions(opts...),
		),
		rotateTerminalKey: connect.NewClient[v1.RotateTerminalKeyRequest, v1.RotateTerminalKeyResponse](
			httpClient,
			baseURL+VPSConfigServiceRotateTerminalKeyProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("RotateTerminalKey")),
			connect.WithClientOptions(opts...),
		),
		removeTerminalKey: connect.NewClient[v1.RemoveTerminalKeyRequest, v1.RemoveTerminalKeyResponse](
			httpClient,
			baseURL+VPSConfigServiceRemoveTerminalKeyProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("RemoveTerminalKey")),
			connect.WithClientOptions(opts...),
		),
		getTerminalKey: connect.NewClient[v1.GetTerminalKeyRequest, v1.GetTerminalKeyResponse](
			httpClient,
			baseURL+VPSConfigServiceGetTerminalKeyProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("GetTerminalKey")),
			connect.WithClientOptions(opts...),
		),
		rotateBastionKey: connect.NewClient[v1.RotateBastionKeyRequest, v1.RotateBastionKeyResponse](
			httpClient,
			baseURL+VPSConfigServiceRotateBastionKeyProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("RotateBastionKey")),
			connect.WithClientOptions(opts...),
		),
		getBastionKey: connect.NewClient[v1.GetBastionKeyRequest, v1.GetBastionKeyResponse](
			httpClient,
			baseURL+VPSConfigServiceGetBastionKeyProcedure,
			connect.WithSchema(vPSConfigServiceMethods.ByName("GetBastionKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// vPSConfigServiceClient implements VPSConfigServiceClient.
type vPSConfigServiceClient struct {
	getCloudInitConfig    *connect.Client[v1.GetCloudInitConfigRequest, v1.GetCloudInitConfigResponse]
	updateCloudInitConfig *connect.Client[v1.UpdateCloudInitConfigRequest, v1.UpdateCloudInitConfigResponse]
	listVPSUsers          *connect.Client[v1.ListVPSUsersRequest, v1.ListVPSUsersResponse]
	createVPSUser         *connect.Client[v1.CreateVPSUserRequest, v1.CreateVPSUserResponse]
	updateVPSUser         *connect.Client[v1.UpdateVPSUserRequest, v1.UpdateVPSUserResponse]
	deleteVPSUser         *connect.Client[v1.DeleteVPSUserRequest, v1.DeleteVPSUserResponse]
	setUserPassword       *connect.Client[v1.SetUserPasswordRequest, v1.SetUserPasswordResponse]
	updateUserSSHKeys     *connect.Client[v1.UpdateUserSSHKeysRequest, v1.UpdateUserSSHKeysResponse]
	rotateTerminalKey     *connect.Client[v1.RotateTerminalKeyRequest, v1.RotateTerminalKeyResponse]
	removeTerminalKey     *connect.Client[v1.RemoveTerminalKeyRequest, v1.RemoveTerminalKeyResponse]
	getTerminalKey        *connect.Client[v1.GetTerminalKeyRequest, v1.GetTerminalKeyResponse]
	rotateBastionKey      *connect.Client[v1.RotateBastionKeyRequest, v1.RotateBastionKeyResponse]
	getBastionKey         *connect.Client[v1.GetBastionKeyRequest, v1.GetBastionKeyResponse]
}

// GetCloudInitConfig calls obiente.cloud.vps.v1.VPSConfigService.GetCloudInitConfig.
func (c *vPSConfigServiceClient) GetCloudInitConfig(ctx context.Context, req *connect.Request[v1.GetCloudInitConfigRequest]) (*connect.Response[v1.GetCloudInitConfigResponse], error) {
	return c.getCloudInitConfig.CallUnary(ctx, req)
}

// UpdateCloudInitConfig calls obiente.cloud.vps.v1.VPSConfigService.UpdateCloudInitConfig.
func (c *vPSConfigServiceClient) UpdateCloudInitConfig(ctx context.Context, req *connect.Request[v1.UpdateCloudInitConfigRequest]) (*connect.Response[v1.UpdateCloudInitConfigResponse], error) {
	return c.updateCloudInitConfig.CallUnary(ctx, req)
}

// ListVPSUsers calls obiente.cloud.vps.v1.VPSConfigService.ListVPSUsers.
func (c *vPSConfigServiceClient) ListVPSUsers(ctx context.Context, req *connect.Request[v1.ListVPSUsersRequest]) (*connect.Response[v1.ListVPSUsersResponse], error) {
	return c.listVPSUsers.CallUnary(ctx, req)
}

// CreateVPSUser calls obiente.cloud.vps.v1.VPSConfigService.CreateVPSUser.
func (c *vPSConfigServiceClient) CreateVPSUser(ctx context.Context, req *connect.Request[v1.CreateVPSUserRequest]) (*connect.Response[v1.CreateVPSUserResponse], error) {
	return c.createVPSUser.CallUnary(ctx, req)
}

// UpdateVPSUser calls obiente.cloud.vps.v1.VPSConfigService.UpdateVPSUser.
func (c *vPSConfigServiceClient) UpdateVPSUser(ctx context.Context, req *connect.Request[v1.UpdateVPSUserRequest]) (*connect.Response[v1.UpdateVPSUserResponse], error) {
	return c.updateVPSUser.CallUnary(ctx, req)
}

// DeleteVPSUser calls obiente.cloud.vps.v1.VPSConfigService.DeleteVPSUser.
func (c *vPSConfigServiceClient) DeleteVPSUser(ctx context.Context, req *connect.Request[v1.DeleteVPSUserRequest]) (*connect.Response[v1.DeleteVPSUserResponse], error) {
	return c.deleteVPSUser.CallUnary(ctx, req)
}

// SetUserPassword calls obiente.cloud.vps.v1.VPSConfigService.SetUserPassword.
func (c *vPSConfigServiceClient) SetUserPassword(ctx context.Context, req *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error) {
	return c.setUserPassword.CallUnary(ctx, req)
}

// UpdateUserSSHKeys calls obiente.cloud.vps.v1.VPSConfigService.UpdateUserSSHKeys.
func (c *vPSConfigServiceClient) UpdateUserSSHKeys(ctx context.Context, req *connect.Request[v1.UpdateUserSSHKeysRequest]) (*connect.Response[v1.UpdateUserSSHKeysResponse], error) {
	return c.updateUserSSHKeys.CallUnary(ctx, req)
}

// RotateTerminalKey calls obiente.cloud.vps.v1.VPSConfigService.RotateTerminalKey.
func (c *vPSConfigServiceClient) RotateTerminalKey(ctx context.Context, req *connect.Request[v1.RotateTerminalKeyRequest]) (*connect.Response[v1.RotateTerminalKeyResponse], error) {
	return c.rotateTerminalKey.CallUnary(ctx, req)
}

// RemoveTerminalKey calls obiente.cloud.vps.v1.VPSConfigService.RemoveTerminalKey.
func (c *vPSConfigServiceClient) RemoveTerminalKey(ctx context.Context, req *connect.Request[v1.RemoveTerminalKeyRequest]) (*connect.Response[v1.RemoveTerminalKeyResponse], error) {
	return c.removeTerminalKey.CallUnary(ctx, req)
}

// GetTerminalKey calls obiente.cloud.vps.v1.VPSConfigService.GetTerminalKey.
func (c *vPSConfigServiceClient) GetTerminalKey(ctx context.Context, req *connect.Request[v1.GetTerminalKeyRequest]) (*connect.Response[v1.GetTerminalKeyResponse], error) {
	return c.getTerminalKey.CallUnary(ctx, req)
}

// RotateBastionKey calls obiente.cloud.vps.v1.VPSConfigService.RotateBastionKey.
func (c *vPSConfigServiceClient) RotateBastionKey(ctx context.Context, req *connect.Request[v1.RotateBastionKeyRequest]) (*connect.Response[v1.RotateBastionKeyResponse], error) {
	return c.rotateBastionKey.CallUnary(ctx, req)
}

// GetBastionKey calls obiente.cloud.vps.v1.VPSConfigService.GetBastionKey.
func (c *vPSConfigServiceClient) GetBastionKey(ctx context.Context, req *connect.Request[v1.GetBastionKeyRequest]) (*connect.Response[v1.GetBastionKeyResponse], error) {
	return c.getBastionKey.CallUnary(ctx, req)
}

// VPSConfigServiceHandler is an implementation of the obiente.cloud.vps.v1.VPSConfigService
// service.
type VPSConfigServiceHandler interface {
	// Get cloud-init configuration for a VPS instance
	GetCloudInitConfig(context.Context, *connect.Request[v1.GetCloudInitConfigRequest]) (*connect.Response[v1.GetCloudInitConfigResponse], error)
	// Update cloud-init configuration for a VPS instance
	UpdateCloudInitConfig(context.Context, *connect.Request[v1.UpdateCloudInitConfigRequest]) (*connect.Response[v1.UpdateCloudInitConfigResponse], error)
	// List users configured for a VPS instance
	ListVPSUsers(context.Context, *connect.Request[v1.ListVPSUsersRequest]) (*connect.Response[v1.ListVPSUsersResponse], error)
	// Create a new user on a VPS instance
	CreateVPSUser(context.Context, *connect.Request[v1.CreateVPSUserRequest]) (*connect.Response[v1.CreateVPSUserResponse], error)
	// Update an existing user on a VPS instance
	UpdateVPSUser(context.Context, *connect.Request[v1.UpdateVPSUserRequest]) (*connect.Response[v1.UpdateVPSUserResponse], error)
	// Delete a user from a VPS instance
	DeleteVPSUser(context.Context, *connect.Request[v1.DeleteVPSUserRequest]) (*connect.Response[v1.DeleteVPSUserResponse], error)
	// Set or reset password for a user
	SetUserPassword(context.Context, *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error)
	// Manage SSH keys for a specific user
	UpdateUserSSHKeys(context.Context, *connect.Request[v1.UpdateUserSSHKeysRequest]) (*connect.Response[v1.UpdateUserSSHKeysResponse], error)
	// Rotate the web terminal SSH key for a VPS instance
	RotateTerminalKey(context.Context, *connect.Request[v1.RotateTerminalKeyRequest]) (*connect.Response[v1.RotateTerminalKeyResponse], error)
	// Remove the web terminal SSH key for a VPS instance
	RemoveTerminalKey(context.Context, *connect.Request[v1.RemoveTerminalKeyRequest]) (*connect.Response[v1.RemoveTerminalKeyResponse], error)
	// Get the web terminal SSH key status for a VPS instance
	GetTerminalKey(context.Context, *connect.Request[v1.GetTerminalKeyRequest]) (*connect.Response[v1.GetTerminalKeyResponse], error)
	// Rotate the bastion SSH key for a VPS instance
	RotateBastionKey(context.Context, *connect.Request[v1.RotateBastionKeyRequest]) (*connect.Response[v1.RotateBastionKeyResponse], error)
	// Get the bastion SSH key status for a VPS instance
	GetBastionKey(context.Context, *connect.Request[v1.GetBastionKeyRequest]) (*connect.Response[v1.GetBastionKeyResponse], error)
}

// NewVPSConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVPSConfigServiceHandler(svc VPSConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	vPSConfigServiceMethods := v1.File_obiente_cloud_vps_v1_vps_config_service_proto.Services().ByName("VPSConfigService").Methods()
	vPSConfigServiceGetCloudInitConfigHandler := connect.NewUnaryHandler(
		VPSConfigServiceGetCloudInitConfigProcedure,
		svc.GetCloudInitConfig,
		connect.WithSchema(vPSConfigServiceMethods.ByName("GetCloudInitConfig")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceUpdateCloudInitConfigHandler := connect.NewUnaryHandler(
		VPSConfigServiceUpdateCloudInitConfigProcedure,
		svc.UpdateCloudInitConfig,
		connect.WithSchema(vPSConfigServiceMethods.ByName("UpdateCloudInitConfig")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceListVPSUsersHandler := connect.NewUnaryHandler(
		VPSConfigServiceListVPSUsersProcedure,
		svc.ListVPSUsers,
		connect.WithSchema(vPSConfigServiceMethods.ByName("ListVPSUsers")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceCreateVPSUserHandler := connect.NewUnaryHandler(
		VPSConfigServiceCreateVPSUserProcedure,
		svc.CreateVPSUser,
		connect.WithSchema(vPSConfigServiceMethods.ByName("CreateVPSUser")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceUpdateVPSUserHandler := connect.NewUnaryHandler(
		VPSConfigServiceUpdateVPSUserProcedure,
		svc.UpdateVPSUser,
		connect.WithSchema(vPSConfigServiceMethods.ByName("UpdateVPSUser")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceDeleteVPSUserHandler := connect.NewUnaryHandler(
		VPSConfigServiceDeleteVPSUserProcedure,
		svc.DeleteVPSUser,
		connect.WithSchema(vPSConfigServiceMethods.ByName("DeleteVPSUser")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceSetUserPasswordHandler := connect.NewUnaryHandler(
		VPSConfigServiceSetUserPasswordProcedure,
		svc.SetUserPassword,
		connect.WithSchema(vPSConfigServiceMethods.ByName("SetUserPassword")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceUpdateUserSSHKeysHandler := connect.NewUnaryHandler(
		VPSConfigServiceUpdateUserSSHKeysProcedure,
		svc.UpdateUserSSHKeys,
		connect.WithSchema(vPSConfigServiceMethods.ByName("UpdateUserSSHKeys")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceRotateTerminalKeyHandler := connect.NewUnaryHandler(
		VPSConfigServiceRotateTerminalKeyProcedure,
		svc.RotateTerminalKey,
		connect.WithSchema(vPSConfigServiceMethods.ByName("RotateTerminalKey")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceRemoveTerminalKeyHandler := connect.NewUnaryHandler(
		VPSConfigServiceRemoveTerminalKeyProcedure,
		svc.RemoveTerminalKey,
		connect.WithSchema(vPSConfigServiceMethods.ByName("RemoveTerminalKey")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceGetTerminalKeyHandler := connect.NewUnaryHandler(
		VPSConfigServiceGetTerminalKeyProcedure,
		svc.GetTerminalKey,
		connect.WithSchema(vPSConfigServiceMethods.ByName("GetTerminalKey")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceRotateBastionKeyHandler := connect.NewUnaryHandler(
		VPSConfigServiceRotateBastionKeyProcedure,
		svc.RotateBastionKey,
		connect.WithSchema(vPSConfigServiceMethods.ByName("RotateBastionKey")),
		connect.WithHandlerOptions(opts...),
	)
	vPSConfigServiceGetBastionKeyHandler := connect.NewUnaryHandler(
		VPSConfigServiceGetBastionKeyProcedure,
		svc.GetBastionKey,
		connect.WithSchema(vPSConfigServiceMethods.ByName("GetBastionKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/obiente.cloud.vps.v1.VPSConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VPSConfigServiceGetCloudInitConfigProcedure:
			vPSConfigServiceGetCloudInitConfigHandler.ServeHTTP(w, r)
		case VPSConfigServiceUpdateCloudInitConfigProcedure:
			vPSConfigServiceUpdateCloudInitConfigHandler.ServeHTTP(w, r)
		case VPSConfigServiceListVPSUsersProcedure:
			vPSConfigServiceListVPSUsersHandler.ServeHTTP(w, r)
		case VPSConfigServiceCreateVPSUserProcedure:
			vPSConfigServiceCreateVPSUserHandler.ServeHTTP(w, r)
		case VPSConfigServiceUpdateVPSUserProcedure:
			vPSConfigServiceUpdateVPSUserHandler.ServeHTTP(w, r)
		case VPSConfigServiceDeleteVPSUserProcedure:
			vPSConfigServiceDeleteVPSUserHandler.ServeHTTP(w, r)
		case VPSConfigServiceSetUserPasswordProcedure:
			vPSConfigServiceSetUserPasswordHandler.ServeHTTP(w, r)
		case VPSConfigServiceUpdateUserSSHKeysProcedure:
			vPSConfigServiceUpdateUserSSHKeysHandler.ServeHTTP(w, r)
		case VPSConfigServiceRotateTerminalKeyProcedure:
			vPSConfigServiceRotateTerminalKeyHandler.ServeHTTP(w, r)
		case VPSConfigServiceRemoveTerminalKeyProcedure:
			vPSConfigServiceRemoveTerminalKeyHandler.ServeHTTP(w, r)
		case VPSConfigServiceGetTerminalKeyProcedure:
			vPSConfigServiceGetTerminalKeyHandler.ServeHTTP(w, r)
		case VPSConfigServiceRotateBastionKeyProcedure:
			vPSConfigServiceRotateBastionKeyHandler.ServeHTTP(w, r)
		case VPSConfigServiceGetBastionKeyProcedure:
			vPSConfigServiceGetBastionKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVPSConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVPSConfigServiceHandler struct{}

func (UnimplementedVPSConfigServiceHandler) GetCloudInitConfig(context.Context, *connect.Request[v1.GetCloudInitConfigRequest]) (*connect.Response[v1.GetCloudInitConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.GetCloudInitConfig is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) UpdateCloudInitConfig(context.Context, *connect.Request[v1.UpdateCloudInitConfigRequest]) (*connect.Response[v1.UpdateCloudInitConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.UpdateCloudInitConfig is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) ListVPSUsers(context.Context, *connect.Request[v1.ListVPSUsersRequest]) (*connect.Response[v1.ListVPSUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.ListVPSUsers is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) CreateVPSUser(context.Context, *connect.Request[v1.CreateVPSUserRequest]) (*connect.Response[v1.CreateVPSUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.CreateVPSUser is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) UpdateVPSUser(context.Context, *connect.Request[v1.UpdateVPSUserRequest]) (*connect.Response[v1.UpdateVPSUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.UpdateVPSUser is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) DeleteVPSUser(context.Context, *connect.Request[v1.DeleteVPSUserRequest]) (*connect.Response[v1.DeleteVPSUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.DeleteVPSUser is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) SetUserPassword(context.Context, *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.SetUserPassword is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) UpdateUserSSHKeys(context.Context, *connect.Request[v1.UpdateUserSSHKeysRequest]) (*connect.Response[v1.UpdateUserSSHKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.UpdateUserSSHKeys is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) RotateTerminalKey(context.Context, *connect.Request[v1.RotateTerminalKeyRequest]) (*connect.Response[v1.RotateTerminalKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.RotateTerminalKey is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) RemoveTerminalKey(context.Context, *connect.Request[v1.RemoveTerminalKeyRequest]) (*connect.Response[v1.RemoveTerminalKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.RemoveTerminalKey is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) GetTerminalKey(context.Context, *connect.Request[v1.GetTerminalKeyRequest]) (*connect.Response[v1.GetTerminalKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.GetTerminalKey is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) RotateBastionKey(context.Context, *connect.Request[v1.RotateBastionKeyRequest]) (*connect.Response[v1.RotateBastionKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.RotateBastionKey is not implemented"))
}

func (UnimplementedVPSConfigServiceHandler) GetBastionKey(context.Context, *connect.Request[v1.GetBastionKeyRequest]) (*connect.Response[v1.GetBastionKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.vps.v1.VPSConfigService.GetBastionKey is not implemented"))
}
