// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: obiente/cloud/auth/v1/auth_service.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/obiente/cloud/apps/shared/proto/obiente/cloud/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "obiente.cloud.auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceGetPublicConfigProcedure is the fully-qualified name of the AuthService's
	// GetPublicConfig RPC.
	AuthServiceGetPublicConfigProcedure = "/obiente.cloud.auth.v1.AuthService/GetPublicConfig"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/obiente.cloud.auth.v1.AuthService/Login"
	// AuthServiceGetCurrentUserProcedure is the fully-qualified name of the AuthService's
	// GetCurrentUser RPC.
	AuthServiceGetCurrentUserProcedure = "/obiente.cloud.auth.v1.AuthService/GetCurrentUser"
	// AuthServiceUpdateUserProfileProcedure is the fully-qualified name of the AuthService's
	// UpdateUserProfile RPC.
	AuthServiceUpdateUserProfileProcedure = "/obiente.cloud.auth.v1.AuthService/UpdateUserProfile"
	// AuthServiceConnectOrganizationGitHubAppProcedure is the fully-qualified name of the AuthService's
	// ConnectOrganizationGitHubApp RPC.
	AuthServiceConnectOrganizationGitHubAppProcedure = "/obiente.cloud.auth.v1.AuthService/ConnectOrganizationGitHubApp"
	// AuthServiceDisconnectOrganizationGitHubAppProcedure is the fully-qualified name of the
	// AuthService's DisconnectOrganizationGitHubApp RPC.
	AuthServiceDisconnectOrganizationGitHubAppProcedure = "/obiente.cloud.auth.v1.AuthService/DisconnectOrganizationGitHubApp"
	// AuthServiceListGitHubIntegrationsProcedure is the fully-qualified name of the AuthService's
	// ListGitHubIntegrations RPC.
	AuthServiceListGitHubIntegrationsProcedure = "/obiente.cloud.auth.v1.AuthService/ListGitHubIntegrations"
)

// AuthServiceClient is a client for the obiente.cloud.auth.v1.AuthService service.
type AuthServiceClient interface {
	// Get public configuration (no authentication required)
	GetPublicConfig(context.Context, *connect.Request[v1.GetPublicConfigRequest]) (*connect.Response[v1.GetPublicConfigResponse], error)
	// Login with email and password using service account
	// This endpoint does not require authentication (public)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Get current authenticated user
	GetCurrentUser(context.Context, *connect.Request[v1.GetCurrentUserRequest]) (*connect.Response[v1.GetCurrentUserResponse], error)
	// Update user profile information
	UpdateUserProfile(context.Context, *connect.Request[v1.UpdateUserProfileRequest]) (*connect.Response[v1.UpdateUserProfileResponse], error)
	// Connect GitHub App installation to an Obiente organization/workspace
	ConnectOrganizationGitHubApp(context.Context, *connect.Request[v1.ConnectOrganizationGitHubAppRequest]) (*connect.Response[v1.ConnectOrganizationGitHubAppResponse], error)
	// Disconnect GitHub App installation from an Obiente organization/workspace
	DisconnectOrganizationGitHubApp(context.Context, *connect.Request[v1.DisconnectOrganizationGitHubAppRequest]) (*connect.Response[v1.DisconnectOrganizationGitHubAppResponse], error)
	// List GitHub App integrations available to the user
	ListGitHubIntegrations(context.Context, *connect.Request[v1.ListGitHubIntegrationsRequest]) (*connect.Response[v1.ListGitHubIntegrationsResponse], error)
}

// NewAuthServiceClient constructs a client for the obiente.cloud.auth.v1.AuthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_obiente_cloud_auth_v1_auth_service_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		getPublicConfig: connect.NewClient[v1.GetPublicConfigRequest, v1.GetPublicConfigResponse](
			httpClient,
			baseURL+AuthServiceGetPublicConfigProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetPublicConfig")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		getCurrentUser: connect.NewClient[v1.GetCurrentUserRequest, v1.GetCurrentUserResponse](
			httpClient,
			baseURL+AuthServiceGetCurrentUserProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetCurrentUser")),
			connect.WithClientOptions(opts...),
		),
		updateUserProfile: connect.NewClient[v1.UpdateUserProfileRequest, v1.UpdateUserProfileResponse](
			httpClient,
			baseURL+AuthServiceUpdateUserProfileProcedure,
			connect.WithSchema(authServiceMethods.ByName("UpdateUserProfile")),
			connect.WithClientOptions(opts...),
		),
		connectOrganizationGitHubApp: connect.NewClient[v1.ConnectOrganizationGitHubAppRequest, v1.ConnectOrganizationGitHubAppResponse](
			httpClient,
			baseURL+AuthServiceConnectOrganizationGitHubAppProcedure,
			connect.WithSchema(authServiceMethods.ByName("ConnectOrganizationGitHubApp")),
			connect.WithClientOptions(opts...),
		),
		disconnectOrganizationGitHubApp: connect.NewClient[v1.DisconnectOrganizationGitHubAppRequest, v1.DisconnectOrganizationGitHubAppResponse](
			httpClient,
			baseURL+AuthServiceDisconnectOrganizationGitHubAppProcedure,
			connect.WithSchema(authServiceMethods.ByName("DisconnectOrganizationGitHubApp")),
			connect.WithClientOptions(opts...),
		),
		listGitHubIntegrations: connect.NewClient[v1.ListGitHubIntegrationsRequest, v1.ListGitHubIntegrationsResponse](
			httpClient,
			baseURL+AuthServiceListGitHubIntegrationsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListGitHubIntegrations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	getPublicConfig                 *connect.Client[v1.GetPublicConfigRequest, v1.GetPublicConfigResponse]
	login                           *connect.Client[v1.LoginRequest, v1.LoginResponse]
	getCurrentUser                  *connect.Client[v1.GetCurrentUserRequest, v1.GetCurrentUserResponse]
	updateUserProfile               *connect.Client[v1.UpdateUserProfileRequest, v1.UpdateUserProfileResponse]
	connectOrganizationGitHubApp    *connect.Client[v1.ConnectOrganizationGitHubAppRequest, v1.ConnectOrganizationGitHubAppResponse]
	disconnectOrganizationGitHubApp *connect.Client[v1.DisconnectOrganizationGitHubAppRequest, v1.DisconnectOrganizationGitHubAppResponse]
	listGitHubIntegrations          *connect.Client[v1.ListGitHubIntegrationsRequest, v1.ListGitHubIntegrationsResponse]
}

// GetPublicConfig calls obiente.cloud.auth.v1.AuthService.GetPublicConfig.
func (c *authServiceClient) GetPublicConfig(ctx context.Context, req *connect.Request[v1.GetPublicConfigRequest]) (*connect.Response[v1.GetPublicConfigResponse], error) {
	return c.getPublicConfig.CallUnary(ctx, req)
}

// Login calls obiente.cloud.auth.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// GetCurrentUser calls obiente.cloud.auth.v1.AuthService.GetCurrentUser.
func (c *authServiceClient) GetCurrentUser(ctx context.Context, req *connect.Request[v1.GetCurrentUserRequest]) (*connect.Response[v1.GetCurrentUserResponse], error) {
	return c.getCurrentUser.CallUnary(ctx, req)
}

// UpdateUserProfile calls obiente.cloud.auth.v1.AuthService.UpdateUserProfile.
func (c *authServiceClient) UpdateUserProfile(ctx context.Context, req *connect.Request[v1.UpdateUserProfileRequest]) (*connect.Response[v1.UpdateUserProfileResponse], error) {
	return c.updateUserProfile.CallUnary(ctx, req)
}

// ConnectOrganizationGitHubApp calls
// obiente.cloud.auth.v1.AuthService.ConnectOrganizationGitHubApp.
func (c *authServiceClient) ConnectOrganizationGitHubApp(ctx context.Context, req *connect.Request[v1.ConnectOrganizationGitHubAppRequest]) (*connect.Response[v1.ConnectOrganizationGitHubAppResponse], error) {
	return c.connectOrganizationGitHubApp.CallUnary(ctx, req)
}

// DisconnectOrganizationGitHubApp calls
// obiente.cloud.auth.v1.AuthService.DisconnectOrganizationGitHubApp.
func (c *authServiceClient) DisconnectOrganizationGitHubApp(ctx context.Context, req *connect.Request[v1.DisconnectOrganizationGitHubAppRequest]) (*connect.Response[v1.DisconnectOrganizationGitHubAppResponse], error) {
	return c.disconnectOrganizationGitHubApp.CallUnary(ctx, req)
}

// ListGitHubIntegrations calls obiente.cloud.auth.v1.AuthService.ListGitHubIntegrations.
func (c *authServiceClient) ListGitHubIntegrations(ctx context.Context, req *connect.Request[v1.ListGitHubIntegrationsRequest]) (*connect.Response[v1.ListGitHubIntegrationsResponse], error) {
	return c.listGitHubIntegrations.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the obiente.cloud.auth.v1.AuthService service.
type AuthServiceHandler interface {
	// Get public configuration (no authentication required)
	GetPublicConfig(context.Context, *connect.Request[v1.GetPublicConfigRequest]) (*connect.Response[v1.GetPublicConfigResponse], error)
	// Login with email and password using service account
	// This endpoint does not require authentication (public)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Get current authenticated user
	GetCurrentUser(context.Context, *connect.Request[v1.GetCurrentUserRequest]) (*connect.Response[v1.GetCurrentUserResponse], error)
	// Update user profile information
	UpdateUserProfile(context.Context, *connect.Request[v1.UpdateUserProfileRequest]) (*connect.Response[v1.UpdateUserProfileResponse], error)
	// Connect GitHub App installation to an Obiente organization/workspace
	ConnectOrganizationGitHubApp(context.Context, *connect.Request[v1.ConnectOrganizationGitHubAppRequest]) (*connect.Response[v1.ConnectOrganizationGitHubAppResponse], error)
	// Disconnect GitHub App installation from an Obiente organization/workspace
	DisconnectOrganizationGitHubApp(context.Context, *connect.Request[v1.DisconnectOrganizationGitHubAppRequest]) (*connect.Response[v1.DisconnectOrganizationGitHubAppResponse], error)
	// List GitHub App integrations available to the user
	ListGitHubIntegrations(context.Context, *connect.Request[v1.ListGitHubIntegrationsRequest]) (*connect.Response[v1.ListGitHubIntegrationsResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_obiente_cloud_auth_v1_auth_service_proto.Services().ByName("AuthService").Methods()
	authServiceGetPublicConfigHandler := connect.NewUnaryHandler(
		AuthServiceGetPublicConfigProcedure,
		svc.GetPublicConfig,
		connect.WithSchema(authServiceMethods.ByName("GetPublicConfig")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetCurrentUserHandler := connect.NewUnaryHandler(
		AuthServiceGetCurrentUserProcedure,
		svc.GetCurrentUser,
		connect.WithSchema(authServiceMethods.ByName("GetCurrentUser")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUpdateUserProfileHandler := connect.NewUnaryHandler(
		AuthServiceUpdateUserProfileProcedure,
		svc.UpdateUserProfile,
		connect.WithSchema(authServiceMethods.ByName("UpdateUserProfile")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceConnectOrganizationGitHubAppHandler := connect.NewUnaryHandler(
		AuthServiceConnectOrganizationGitHubAppProcedure,
		svc.ConnectOrganizationGitHubApp,
		connect.WithSchema(authServiceMethods.ByName("ConnectOrganizationGitHubApp")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDisconnectOrganizationGitHubAppHandler := connect.NewUnaryHandler(
		AuthServiceDisconnectOrganizationGitHubAppProcedure,
		svc.DisconnectOrganizationGitHubApp,
		connect.WithSchema(authServiceMethods.ByName("DisconnectOrganizationGitHubApp")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListGitHubIntegrationsHandler := connect.NewUnaryHandler(
		AuthServiceListGitHubIntegrationsProcedure,
		svc.ListGitHubIntegrations,
		connect.WithSchema(authServiceMethods.ByName("ListGitHubIntegrations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/obiente.cloud.auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceGetPublicConfigProcedure:
			authServiceGetPublicConfigHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceGetCurrentUserProcedure:
			authServiceGetCurrentUserHandler.ServeHTTP(w, r)
		case AuthServiceUpdateUserProfileProcedure:
			authServiceUpdateUserProfileHandler.ServeHTTP(w, r)
		case AuthServiceConnectOrganizationGitHubAppProcedure:
			authServiceConnectOrganizationGitHubAppHandler.ServeHTTP(w, r)
		case AuthServiceDisconnectOrganizationGitHubAppProcedure:
			authServiceDisconnectOrganizationGitHubAppHandler.ServeHTTP(w, r)
		case AuthServiceListGitHubIntegrationsProcedure:
			authServiceListGitHubIntegrationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) GetPublicConfig(context.Context, *connect.Request[v1.GetPublicConfigRequest]) (*connect.Response[v1.GetPublicConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.auth.v1.AuthService.GetPublicConfig is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.auth.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetCurrentUser(context.Context, *connect.Request[v1.GetCurrentUserRequest]) (*connect.Response[v1.GetCurrentUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.auth.v1.AuthService.GetCurrentUser is not implemented"))
}

func (UnimplementedAuthServiceHandler) UpdateUserProfile(context.Context, *connect.Request[v1.UpdateUserProfileRequest]) (*connect.Response[v1.UpdateUserProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.auth.v1.AuthService.UpdateUserProfile is not implemented"))
}

func (UnimplementedAuthServiceHandler) ConnectOrganizationGitHubApp(context.Context, *connect.Request[v1.ConnectOrganizationGitHubAppRequest]) (*connect.Response[v1.ConnectOrganizationGitHubAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.auth.v1.AuthService.ConnectOrganizationGitHubApp is not implemented"))
}

func (UnimplementedAuthServiceHandler) DisconnectOrganizationGitHubApp(context.Context, *connect.Request[v1.DisconnectOrganizationGitHubAppRequest]) (*connect.Response[v1.DisconnectOrganizationGitHubAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.auth.v1.AuthService.DisconnectOrganizationGitHubApp is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListGitHubIntegrations(context.Context, *connect.Request[v1.ListGitHubIntegrationsRequest]) (*connect.Response[v1.ListGitHubIntegrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.auth.v1.AuthService.ListGitHubIntegrations is not implemented"))
}
