// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: obiente/cloud/audit/v1/audit_service.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages
type ListAuditLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by organization ID (optional)
	OrganizationId *string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	// Filter by resource type (optional, e.g., "deployment", "organization")
	ResourceType *string `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3,oneof" json:"resource_type,omitempty"`
	// Filter by resource ID (optional)
	ResourceId *string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3,oneof" json:"resource_id,omitempty"`
	// Filter by user ID (optional)
	UserId *string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	// Filter by service name (optional, e.g., "DeploymentService")
	Service *string `protobuf:"bytes,5,opt,name=service,proto3,oneof" json:"service,omitempty"`
	// Filter by action name (optional, e.g., "CreateDeployment")
	Action *string `protobuf:"bytes,6,opt,name=action,proto3,oneof" json:"action,omitempty"`
	// Filter by time range (optional)
	StartTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	// Pagination
	PageSize      *int32  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`    // Default: 50, Max: 1000
	PageToken     *string `protobuf:"bytes,10,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"` // Token from previous response for pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_audit_v1_audit_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuditLogsRequest) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *ListAuditLogsRequest) GetResourceType() string {
	if x != nil && x.ResourceType != nil {
		return *x.ResourceType
	}
	return ""
}

func (x *ListAuditLogsRequest) GetResourceId() string {
	if x != nil && x.ResourceId != nil {
		return *x.ResourceId
	}
	return ""
}

func (x *ListAuditLogsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ListAuditLogsRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *ListAuditLogsRequest) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *ListAuditLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListAuditLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListAuditLogsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListAuditLogsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditLogs     []*AuditLogEntry       `protobuf:"bytes,1,rep,name=audit_logs,json=auditLogs,proto3" json:"audit_logs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // Token for next page, empty if no more pages
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`           // Total number of audit logs matching the filters (before pagination)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_audit_v1_audit_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditLogsResponse) GetAuditLogs() []*AuditLogEntry {
	if x != nil {
		return x.AuditLogs
	}
	return nil
}

func (x *ListAuditLogsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAuditLogsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditLogId    string                 `protobuf:"bytes,1,opt,name=audit_log_id,json=auditLogId,proto3" json:"audit_log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_audit_v1_audit_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditLogRequest) GetAuditLogId() string {
	if x != nil {
		return x.AuditLogId
	}
	return ""
}

type GetAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditLog      *AuditLogEntry         `protobuf:"bytes,1,opt,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogResponse) Reset() {
	*x = GetAuditLogResponse{}
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogResponse) ProtoMessage() {}

func (x *GetAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_audit_v1_audit_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuditLogResponse) GetAuditLog() *AuditLogEntry {
	if x != nil {
		return x.AuditLog
	}
	return nil
}

// AuditLogEntry represents a single audit log entry
type AuditLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName       *string                `protobuf:"bytes,15,opt,name=user_name,json=userName,proto3,oneof" json:"user_name,omitempty"`    // Resolved user name (for display)
	UserEmail      *string                `protobuf:"bytes,16,opt,name=user_email,json=userEmail,proto3,oneof" json:"user_email,omitempty"` // Resolved user email (for display)
	OrganizationId *string                `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	Action         string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                                       // RPC method name (e.g., "CreateDeployment")
	Service        string                 `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`                                     // Service name (e.g., "DeploymentService")
	ResourceType   *string                `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3,oneof" json:"resource_type,omitempty"` // Type of resource affected
	ResourceId     *string                `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3,oneof" json:"resource_id,omitempty"`       // ID of the affected resource
	IpAddress      string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent      string                 `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestData    string                 `protobuf:"bytes,10,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`           // JSON-encoded request data (sanitized)
	ResponseStatus int32                  `protobuf:"varint,11,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"` // HTTP/Connect status code
	ErrorMessage   *string                `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`  // Error message if action failed
	DurationMs     int64                  `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`             // Request duration in milliseconds
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_audit_v1_audit_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuditLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLogEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLogEntry) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *AuditLogEntry) GetUserEmail() string {
	if x != nil && x.UserEmail != nil {
		return *x.UserEmail
	}
	return ""
}

func (x *AuditLogEntry) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *AuditLogEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AuditLogEntry) GetResourceType() string {
	if x != nil && x.ResourceType != nil {
		return *x.ResourceType
	}
	return ""
}

func (x *AuditLogEntry) GetResourceId() string {
	if x != nil && x.ResourceId != nil {
		return *x.ResourceId
	}
	return ""
}

func (x *AuditLogEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditLogEntry) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLogEntry) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

func (x *AuditLogEntry) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *AuditLogEntry) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AuditLogEntry) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AuditLogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_obiente_cloud_audit_v1_audit_service_proto protoreflect.FileDescriptor

const file_obiente_cloud_audit_v1_audit_service_proto_rawDesc = "" +
	"\n" +
	"*obiente/cloud/audit/v1/audit_service.proto\x12\x16obiente.cloud.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x04\n" +
	"\x14ListAuditLogsRequest\x12,\n" +
	"\x0forganization_id\x18\x01 \x01(\tH\x00R\x0eorganizationId\x88\x01\x01\x12(\n" +
	"\rresource_type\x18\x02 \x01(\tH\x01R\fresourceType\x88\x01\x01\x12$\n" +
	"\vresource_id\x18\x03 \x01(\tH\x02R\n" +
	"resourceId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\tH\x03R\x06userId\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\x05 \x01(\tH\x04R\aservice\x88\x01\x01\x12\x1b\n" +
	"\x06action\x18\x06 \x01(\tH\x05R\x06action\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x06R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\aR\aendTime\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\t \x01(\x05H\bR\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\n" +
	" \x01(\tH\tR\tpageToken\x88\x01\x01B\x12\n" +
	"\x10_organization_idB\x10\n" +
	"\x0e_resource_typeB\x0e\n" +
	"\f_resource_idB\n" +
	"\n" +
	"\b_user_idB\n" +
	"\n" +
	"\b_serviceB\t\n" +
	"\a_actionB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_timeB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xa6\x01\n" +
	"\x15ListAuditLogsResponse\x12D\n" +
	"\n" +
	"audit_logs\x18\x01 \x03(\v2%.obiente.cloud.audit.v1.AuditLogEntryR\tauditLogs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\"6\n" +
	"\x12GetAuditLogRequest\x12 \n" +
	"\faudit_log_id\x18\x01 \x01(\tR\n" +
	"auditLogId\"Y\n" +
	"\x13GetAuditLogResponse\x12B\n" +
	"\taudit_log\x18\x01 \x01(\v2%.obiente.cloud.audit.v1.AuditLogEntryR\bauditLog\"\xa3\x05\n" +
	"\rAuditLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\tuser_name\x18\x0f \x01(\tH\x00R\buserName\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_email\x18\x10 \x01(\tH\x01R\tuserEmail\x88\x01\x01\x12,\n" +
	"\x0forganization_id\x18\x03 \x01(\tH\x02R\x0eorganizationId\x88\x01\x01\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x18\n" +
	"\aservice\x18\x05 \x01(\tR\aservice\x12(\n" +
	"\rresource_type\x18\x06 \x01(\tH\x03R\fresourceType\x88\x01\x01\x12$\n" +
	"\vresource_id\x18\a \x01(\tH\x04R\n" +
	"resourceId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x12!\n" +
	"\frequest_data\x18\n" +
	" \x01(\tR\vrequestData\x12'\n" +
	"\x0fresponse_status\x18\v \x01(\x05R\x0eresponseStatus\x12(\n" +
	"\rerror_message\x18\f \x01(\tH\x05R\ferrorMessage\x88\x01\x01\x12\x1f\n" +
	"\vduration_ms\x18\r \x01(\x03R\n" +
	"durationMs\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\f\n" +
	"\n" +
	"_user_nameB\r\n" +
	"\v_user_emailB\x12\n" +
	"\x10_organization_idB\x10\n" +
	"\x0e_resource_typeB\x0e\n" +
	"\f_resource_idB\x10\n" +
	"\x0e_error_message2\xe4\x01\n" +
	"\fAuditService\x12l\n" +
	"\rListAuditLogs\x12,.obiente.cloud.audit.v1.ListAuditLogsRequest\x1a-.obiente.cloud.audit.v1.ListAuditLogsResponse\x12f\n" +
	"\vGetAuditLog\x12*.obiente.cloud.audit.v1.GetAuditLogRequest\x1a+.obiente.cloud.audit.v1.GetAuditLogResponseBKZIgithub.com/obiente/cloud/apps/shared/proto/obiente/cloud/audit/v1;auditv1b\x06proto3"

var (
	file_obiente_cloud_audit_v1_audit_service_proto_rawDescOnce sync.Once
	file_obiente_cloud_audit_v1_audit_service_proto_rawDescData []byte
)

func file_obiente_cloud_audit_v1_audit_service_proto_rawDescGZIP() []byte {
	file_obiente_cloud_audit_v1_audit_service_proto_rawDescOnce.Do(func() {
		file_obiente_cloud_audit_v1_audit_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_obiente_cloud_audit_v1_audit_service_proto_rawDesc), len(file_obiente_cloud_audit_v1_audit_service_proto_rawDesc)))
	})
	return file_obiente_cloud_audit_v1_audit_service_proto_rawDescData
}

var file_obiente_cloud_audit_v1_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_obiente_cloud_audit_v1_audit_service_proto_goTypes = []any{
	(*ListAuditLogsRequest)(nil),  // 0: obiente.cloud.audit.v1.ListAuditLogsRequest
	(*ListAuditLogsResponse)(nil), // 1: obiente.cloud.audit.v1.ListAuditLogsResponse
	(*GetAuditLogRequest)(nil),    // 2: obiente.cloud.audit.v1.GetAuditLogRequest
	(*GetAuditLogResponse)(nil),   // 3: obiente.cloud.audit.v1.GetAuditLogResponse
	(*AuditLogEntry)(nil),         // 4: obiente.cloud.audit.v1.AuditLogEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_obiente_cloud_audit_v1_audit_service_proto_depIdxs = []int32{
	5, // 0: obiente.cloud.audit.v1.ListAuditLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	5, // 1: obiente.cloud.audit.v1.ListAuditLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	4, // 2: obiente.cloud.audit.v1.ListAuditLogsResponse.audit_logs:type_name -> obiente.cloud.audit.v1.AuditLogEntry
	4, // 3: obiente.cloud.audit.v1.GetAuditLogResponse.audit_log:type_name -> obiente.cloud.audit.v1.AuditLogEntry
	5, // 4: obiente.cloud.audit.v1.AuditLogEntry.created_at:type_name -> google.protobuf.Timestamp
	0, // 5: obiente.cloud.audit.v1.AuditService.ListAuditLogs:input_type -> obiente.cloud.audit.v1.ListAuditLogsRequest
	2, // 6: obiente.cloud.audit.v1.AuditService.GetAuditLog:input_type -> obiente.cloud.audit.v1.GetAuditLogRequest
	1, // 7: obiente.cloud.audit.v1.AuditService.ListAuditLogs:output_type -> obiente.cloud.audit.v1.ListAuditLogsResponse
	3, // 8: obiente.cloud.audit.v1.AuditService.GetAuditLog:output_type -> obiente.cloud.audit.v1.GetAuditLogResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_obiente_cloud_audit_v1_audit_service_proto_init() }
func file_obiente_cloud_audit_v1_audit_service_proto_init() {
	if File_obiente_cloud_audit_v1_audit_service_proto != nil {
		return
	}
	file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_obiente_cloud_audit_v1_audit_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obiente_cloud_audit_v1_audit_service_proto_rawDesc), len(file_obiente_cloud_audit_v1_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_obiente_cloud_audit_v1_audit_service_proto_goTypes,
		DependencyIndexes: file_obiente_cloud_audit_v1_audit_service_proto_depIdxs,
		MessageInfos:      file_obiente_cloud_audit_v1_audit_service_proto_msgTypes,
	}.Build()
	File_obiente_cloud_audit_v1_audit_service_proto = out.File
	file_obiente_cloud_audit_v1_audit_service_proto_goTypes = nil
	file_obiente_cloud_audit_v1_audit_service_proto_depIdxs = nil
}
