// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: obiente/cloud/gameservers/v1/game_server_service.proto

package gameserversv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/obiente/cloud/apps/shared/proto/obiente/cloud/gameservers/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GameServerServiceName is the fully-qualified name of the GameServerService service.
	GameServerServiceName = "obiente.cloud.gameservers.v1.GameServerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GameServerServiceListGameServersProcedure is the fully-qualified name of the GameServerService's
	// ListGameServers RPC.
	GameServerServiceListGameServersProcedure = "/obiente.cloud.gameservers.v1.GameServerService/ListGameServers"
	// GameServerServiceCreateGameServerProcedure is the fully-qualified name of the GameServerService's
	// CreateGameServer RPC.
	GameServerServiceCreateGameServerProcedure = "/obiente.cloud.gameservers.v1.GameServerService/CreateGameServer"
	// GameServerServiceGetGameServerProcedure is the fully-qualified name of the GameServerService's
	// GetGameServer RPC.
	GameServerServiceGetGameServerProcedure = "/obiente.cloud.gameservers.v1.GameServerService/GetGameServer"
	// GameServerServiceUpdateGameServerProcedure is the fully-qualified name of the GameServerService's
	// UpdateGameServer RPC.
	GameServerServiceUpdateGameServerProcedure = "/obiente.cloud.gameservers.v1.GameServerService/UpdateGameServer"
	// GameServerServiceDeleteGameServerProcedure is the fully-qualified name of the GameServerService's
	// DeleteGameServer RPC.
	GameServerServiceDeleteGameServerProcedure = "/obiente.cloud.gameservers.v1.GameServerService/DeleteGameServer"
	// GameServerServiceStartGameServerProcedure is the fully-qualified name of the GameServerService's
	// StartGameServer RPC.
	GameServerServiceStartGameServerProcedure = "/obiente.cloud.gameservers.v1.GameServerService/StartGameServer"
	// GameServerServiceStopGameServerProcedure is the fully-qualified name of the GameServerService's
	// StopGameServer RPC.
	GameServerServiceStopGameServerProcedure = "/obiente.cloud.gameservers.v1.GameServerService/StopGameServer"
	// GameServerServiceRestartGameServerProcedure is the fully-qualified name of the
	// GameServerService's RestartGameServer RPC.
	GameServerServiceRestartGameServerProcedure = "/obiente.cloud.gameservers.v1.GameServerService/RestartGameServer"
	// GameServerServiceStreamGameServerStatusProcedure is the fully-qualified name of the
	// GameServerService's StreamGameServerStatus RPC.
	GameServerServiceStreamGameServerStatusProcedure = "/obiente.cloud.gameservers.v1.GameServerService/StreamGameServerStatus"
	// GameServerServiceGetGameServerLogsProcedure is the fully-qualified name of the
	// GameServerService's GetGameServerLogs RPC.
	GameServerServiceGetGameServerLogsProcedure = "/obiente.cloud.gameservers.v1.GameServerService/GetGameServerLogs"
	// GameServerServiceStreamGameServerLogsProcedure is the fully-qualified name of the
	// GameServerService's StreamGameServerLogs RPC.
	GameServerServiceStreamGameServerLogsProcedure = "/obiente.cloud.gameservers.v1.GameServerService/StreamGameServerLogs"
	// GameServerServiceSendGameServerCommandProcedure is the fully-qualified name of the
	// GameServerService's SendGameServerCommand RPC.
	GameServerServiceSendGameServerCommandProcedure = "/obiente.cloud.gameservers.v1.GameServerService/SendGameServerCommand"
	// GameServerServiceGetGameServerMetricsProcedure is the fully-qualified name of the
	// GameServerService's GetGameServerMetrics RPC.
	GameServerServiceGetGameServerMetricsProcedure = "/obiente.cloud.gameservers.v1.GameServerService/GetGameServerMetrics"
	// GameServerServiceStreamGameServerMetricsProcedure is the fully-qualified name of the
	// GameServerService's StreamGameServerMetrics RPC.
	GameServerServiceStreamGameServerMetricsProcedure = "/obiente.cloud.gameservers.v1.GameServerService/StreamGameServerMetrics"
	// GameServerServiceGetGameServerUsageProcedure is the fully-qualified name of the
	// GameServerService's GetGameServerUsage RPC.
	GameServerServiceGetGameServerUsageProcedure = "/obiente.cloud.gameservers.v1.GameServerService/GetGameServerUsage"
	// GameServerServiceListGameServerFilesProcedure is the fully-qualified name of the
	// GameServerService's ListGameServerFiles RPC.
	GameServerServiceListGameServerFilesProcedure = "/obiente.cloud.gameservers.v1.GameServerService/ListGameServerFiles"
	// GameServerServiceGetGameServerFileProcedure is the fully-qualified name of the
	// GameServerService's GetGameServerFile RPC.
	GameServerServiceGetGameServerFileProcedure = "/obiente.cloud.gameservers.v1.GameServerService/GetGameServerFile"
	// GameServerServiceUploadGameServerFilesProcedure is the fully-qualified name of the
	// GameServerService's UploadGameServerFiles RPC.
	GameServerServiceUploadGameServerFilesProcedure = "/obiente.cloud.gameservers.v1.GameServerService/UploadGameServerFiles"
	// GameServerServiceDeleteGameServerEntriesProcedure is the fully-qualified name of the
	// GameServerService's DeleteGameServerEntries RPC.
	GameServerServiceDeleteGameServerEntriesProcedure = "/obiente.cloud.gameservers.v1.GameServerService/DeleteGameServerEntries"
	// GameServerServiceCreateGameServerEntryProcedure is the fully-qualified name of the
	// GameServerService's CreateGameServerEntry RPC.
	GameServerServiceCreateGameServerEntryProcedure = "/obiente.cloud.gameservers.v1.GameServerService/CreateGameServerEntry"
	// GameServerServiceWriteGameServerFileProcedure is the fully-qualified name of the
	// GameServerService's WriteGameServerFile RPC.
	GameServerServiceWriteGameServerFileProcedure = "/obiente.cloud.gameservers.v1.GameServerService/WriteGameServerFile"
	// GameServerServiceRenameGameServerEntryProcedure is the fully-qualified name of the
	// GameServerService's RenameGameServerEntry RPC.
	GameServerServiceRenameGameServerEntryProcedure = "/obiente.cloud.gameservers.v1.GameServerService/RenameGameServerEntry"
)

// GameServerServiceClient is a client for the obiente.cloud.gameservers.v1.GameServerService
// service.
type GameServerServiceClient interface {
	// List organization game servers
	ListGameServers(context.Context, *connect.Request[v1.ListGameServersRequest]) (*connect.Response[v1.ListGameServersResponse], error)
	// Create new game server
	CreateGameServer(context.Context, *connect.Request[v1.CreateGameServerRequest]) (*connect.Response[v1.CreateGameServerResponse], error)
	// Get game server details
	GetGameServer(context.Context, *connect.Request[v1.GetGameServerRequest]) (*connect.Response[v1.GetGameServerResponse], error)
	// Update game server configuration
	UpdateGameServer(context.Context, *connect.Request[v1.UpdateGameServerRequest]) (*connect.Response[v1.UpdateGameServerResponse], error)
	// Delete game server
	DeleteGameServer(context.Context, *connect.Request[v1.DeleteGameServerRequest]) (*connect.Response[v1.DeleteGameServerResponse], error)
	// Start a stopped game server
	StartGameServer(context.Context, *connect.Request[v1.StartGameServerRequest]) (*connect.Response[v1.StartGameServerResponse], error)
	// Stop a running game server
	StopGameServer(context.Context, *connect.Request[v1.StopGameServerRequest]) (*connect.Response[v1.StopGameServerResponse], error)
	// Restart a game server
	RestartGameServer(context.Context, *connect.Request[v1.RestartGameServerRequest]) (*connect.Response[v1.RestartGameServerResponse], error)
	// Stream game server status updates
	StreamGameServerStatus(context.Context, *connect.Request[v1.StreamGameServerStatusRequest]) (*connect.ServerStreamForClient[v1.GameServerStatusUpdate], error)
	// Get game server logs
	GetGameServerLogs(context.Context, *connect.Request[v1.GetGameServerLogsRequest]) (*connect.Response[v1.GetGameServerLogsResponse], error)
	// Stream game server logs (tail/follow)
	StreamGameServerLogs(context.Context, *connect.Request[v1.StreamGameServerLogsRequest]) (*connect.ServerStreamForClient[v1.GameServerLogLine], error)
	// Send a command to a running game server
	SendGameServerCommand(context.Context, *connect.Request[v1.SendGameServerCommandRequest]) (*connect.Response[v1.SendGameServerCommandResponse], error)
	// Get game server metrics (real-time or historical)
	GetGameServerMetrics(context.Context, *connect.Request[v1.GetGameServerMetricsRequest]) (*connect.Response[v1.GetGameServerMetricsResponse], error)
	// Stream real-time game server metrics
	StreamGameServerMetrics(context.Context, *connect.Request[v1.StreamGameServerMetricsRequest]) (*connect.ServerStreamForClient[v1.GameServerMetric], error)
	// Get aggregated usage for a game server
	GetGameServerUsage(context.Context, *connect.Request[v1.GetGameServerUsageRequest]) (*connect.Response[v1.GetGameServerUsageResponse], error)
	// File system operations
	// List files in a game server container or volume
	ListGameServerFiles(context.Context, *connect.Request[v1.ListGameServerFilesRequest]) (*connect.Response[v1.ListGameServerFilesResponse], error)
	// Get file contents from a game server container or volume
	GetGameServerFile(context.Context, *connect.Request[v1.GetGameServerFileRequest]) (*connect.Response[v1.GetGameServerFileResponse], error)
	// Upload files to a game server container or volume
	UploadGameServerFiles(context.Context, *connect.Request[v1.UploadGameServerFilesRequest]) (*connect.Response[v1.UploadGameServerFilesResponse], error)
	// Delete files or directories from a game server
	DeleteGameServerEntries(context.Context, *connect.Request[v1.DeleteGameServerEntriesRequest]) (*connect.Response[v1.DeleteGameServerEntriesResponse], error)
	// Create a file, directory, or symlink in a game server
	CreateGameServerEntry(context.Context, *connect.Request[v1.CreateGameServerEntryRequest]) (*connect.Response[v1.CreateGameServerEntryResponse], error)
	// Write or update file contents in a game server
	WriteGameServerFile(context.Context, *connect.Request[v1.WriteGameServerFileRequest]) (*connect.Response[v1.WriteGameServerFileResponse], error)
	// Rename a file or directory in a game server
	RenameGameServerEntry(context.Context, *connect.Request[v1.RenameGameServerEntryRequest]) (*connect.Response[v1.RenameGameServerEntryResponse], error)
}

// NewGameServerServiceClient constructs a client for the
// obiente.cloud.gameservers.v1.GameServerService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGameServerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GameServerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gameServerServiceMethods := v1.File_obiente_cloud_gameservers_v1_game_server_service_proto.Services().ByName("GameServerService").Methods()
	return &gameServerServiceClient{
		listGameServers: connect.NewClient[v1.ListGameServersRequest, v1.ListGameServersResponse](
			httpClient,
			baseURL+GameServerServiceListGameServersProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("ListGameServers")),
			connect.WithClientOptions(opts...),
		),
		createGameServer: connect.NewClient[v1.CreateGameServerRequest, v1.CreateGameServerResponse](
			httpClient,
			baseURL+GameServerServiceCreateGameServerProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("CreateGameServer")),
			connect.WithClientOptions(opts...),
		),
		getGameServer: connect.NewClient[v1.GetGameServerRequest, v1.GetGameServerResponse](
			httpClient,
			baseURL+GameServerServiceGetGameServerProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("GetGameServer")),
			connect.WithClientOptions(opts...),
		),
		updateGameServer: connect.NewClient[v1.UpdateGameServerRequest, v1.UpdateGameServerResponse](
			httpClient,
			baseURL+GameServerServiceUpdateGameServerProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("UpdateGameServer")),
			connect.WithClientOptions(opts...),
		),
		deleteGameServer: connect.NewClient[v1.DeleteGameServerRequest, v1.DeleteGameServerResponse](
			httpClient,
			baseURL+GameServerServiceDeleteGameServerProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("DeleteGameServer")),
			connect.WithClientOptions(opts...),
		),
		startGameServer: connect.NewClient[v1.StartGameServerRequest, v1.StartGameServerResponse](
			httpClient,
			baseURL+GameServerServiceStartGameServerProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("StartGameServer")),
			connect.WithClientOptions(opts...),
		),
		stopGameServer: connect.NewClient[v1.StopGameServerRequest, v1.StopGameServerResponse](
			httpClient,
			baseURL+GameServerServiceStopGameServerProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("StopGameServer")),
			connect.WithClientOptions(opts...),
		),
		restartGameServer: connect.NewClient[v1.RestartGameServerRequest, v1.RestartGameServerResponse](
			httpClient,
			baseURL+GameServerServiceRestartGameServerProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("RestartGameServer")),
			connect.WithClientOptions(opts...),
		),
		streamGameServerStatus: connect.NewClient[v1.StreamGameServerStatusRequest, v1.GameServerStatusUpdate](
			httpClient,
			baseURL+GameServerServiceStreamGameServerStatusProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("StreamGameServerStatus")),
			connect.WithClientOptions(opts...),
		),
		getGameServerLogs: connect.NewClient[v1.GetGameServerLogsRequest, v1.GetGameServerLogsResponse](
			httpClient,
			baseURL+GameServerServiceGetGameServerLogsProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerLogs")),
			connect.WithClientOptions(opts...),
		),
		streamGameServerLogs: connect.NewClient[v1.StreamGameServerLogsRequest, v1.GameServerLogLine](
			httpClient,
			baseURL+GameServerServiceStreamGameServerLogsProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("StreamGameServerLogs")),
			connect.WithClientOptions(opts...),
		),
		sendGameServerCommand: connect.NewClient[v1.SendGameServerCommandRequest, v1.SendGameServerCommandResponse](
			httpClient,
			baseURL+GameServerServiceSendGameServerCommandProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("SendGameServerCommand")),
			connect.WithClientOptions(opts...),
		),
		getGameServerMetrics: connect.NewClient[v1.GetGameServerMetricsRequest, v1.GetGameServerMetricsResponse](
			httpClient,
			baseURL+GameServerServiceGetGameServerMetricsProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerMetrics")),
			connect.WithClientOptions(opts...),
		),
		streamGameServerMetrics: connect.NewClient[v1.StreamGameServerMetricsRequest, v1.GameServerMetric](
			httpClient,
			baseURL+GameServerServiceStreamGameServerMetricsProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("StreamGameServerMetrics")),
			connect.WithClientOptions(opts...),
		),
		getGameServerUsage: connect.NewClient[v1.GetGameServerUsageRequest, v1.GetGameServerUsageResponse](
			httpClient,
			baseURL+GameServerServiceGetGameServerUsageProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerUsage")),
			connect.WithClientOptions(opts...),
		),
		listGameServerFiles: connect.NewClient[v1.ListGameServerFilesRequest, v1.ListGameServerFilesResponse](
			httpClient,
			baseURL+GameServerServiceListGameServerFilesProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("ListGameServerFiles")),
			connect.WithClientOptions(opts...),
		),
		getGameServerFile: connect.NewClient[v1.GetGameServerFileRequest, v1.GetGameServerFileResponse](
			httpClient,
			baseURL+GameServerServiceGetGameServerFileProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerFile")),
			connect.WithClientOptions(opts...),
		),
		uploadGameServerFiles: connect.NewClient[v1.UploadGameServerFilesRequest, v1.UploadGameServerFilesResponse](
			httpClient,
			baseURL+GameServerServiceUploadGameServerFilesProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("UploadGameServerFiles")),
			connect.WithClientOptions(opts...),
		),
		deleteGameServerEntries: connect.NewClient[v1.DeleteGameServerEntriesRequest, v1.DeleteGameServerEntriesResponse](
			httpClient,
			baseURL+GameServerServiceDeleteGameServerEntriesProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("DeleteGameServerEntries")),
			connect.WithClientOptions(opts...),
		),
		createGameServerEntry: connect.NewClient[v1.CreateGameServerEntryRequest, v1.CreateGameServerEntryResponse](
			httpClient,
			baseURL+GameServerServiceCreateGameServerEntryProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("CreateGameServerEntry")),
			connect.WithClientOptions(opts...),
		),
		writeGameServerFile: connect.NewClient[v1.WriteGameServerFileRequest, v1.WriteGameServerFileResponse](
			httpClient,
			baseURL+GameServerServiceWriteGameServerFileProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("WriteGameServerFile")),
			connect.WithClientOptions(opts...),
		),
		renameGameServerEntry: connect.NewClient[v1.RenameGameServerEntryRequest, v1.RenameGameServerEntryResponse](
			httpClient,
			baseURL+GameServerServiceRenameGameServerEntryProcedure,
			connect.WithSchema(gameServerServiceMethods.ByName("RenameGameServerEntry")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gameServerServiceClient implements GameServerServiceClient.
type gameServerServiceClient struct {
	listGameServers         *connect.Client[v1.ListGameServersRequest, v1.ListGameServersResponse]
	createGameServer        *connect.Client[v1.CreateGameServerRequest, v1.CreateGameServerResponse]
	getGameServer           *connect.Client[v1.GetGameServerRequest, v1.GetGameServerResponse]
	updateGameServer        *connect.Client[v1.UpdateGameServerRequest, v1.UpdateGameServerResponse]
	deleteGameServer        *connect.Client[v1.DeleteGameServerRequest, v1.DeleteGameServerResponse]
	startGameServer         *connect.Client[v1.StartGameServerRequest, v1.StartGameServerResponse]
	stopGameServer          *connect.Client[v1.StopGameServerRequest, v1.StopGameServerResponse]
	restartGameServer       *connect.Client[v1.RestartGameServerRequest, v1.RestartGameServerResponse]
	streamGameServerStatus  *connect.Client[v1.StreamGameServerStatusRequest, v1.GameServerStatusUpdate]
	getGameServerLogs       *connect.Client[v1.GetGameServerLogsRequest, v1.GetGameServerLogsResponse]
	streamGameServerLogs    *connect.Client[v1.StreamGameServerLogsRequest, v1.GameServerLogLine]
	sendGameServerCommand   *connect.Client[v1.SendGameServerCommandRequest, v1.SendGameServerCommandResponse]
	getGameServerMetrics    *connect.Client[v1.GetGameServerMetricsRequest, v1.GetGameServerMetricsResponse]
	streamGameServerMetrics *connect.Client[v1.StreamGameServerMetricsRequest, v1.GameServerMetric]
	getGameServerUsage      *connect.Client[v1.GetGameServerUsageRequest, v1.GetGameServerUsageResponse]
	listGameServerFiles     *connect.Client[v1.ListGameServerFilesRequest, v1.ListGameServerFilesResponse]
	getGameServerFile       *connect.Client[v1.GetGameServerFileRequest, v1.GetGameServerFileResponse]
	uploadGameServerFiles   *connect.Client[v1.UploadGameServerFilesRequest, v1.UploadGameServerFilesResponse]
	deleteGameServerEntries *connect.Client[v1.DeleteGameServerEntriesRequest, v1.DeleteGameServerEntriesResponse]
	createGameServerEntry   *connect.Client[v1.CreateGameServerEntryRequest, v1.CreateGameServerEntryResponse]
	writeGameServerFile     *connect.Client[v1.WriteGameServerFileRequest, v1.WriteGameServerFileResponse]
	renameGameServerEntry   *connect.Client[v1.RenameGameServerEntryRequest, v1.RenameGameServerEntryResponse]
}

// ListGameServers calls obiente.cloud.gameservers.v1.GameServerService.ListGameServers.
func (c *gameServerServiceClient) ListGameServers(ctx context.Context, req *connect.Request[v1.ListGameServersRequest]) (*connect.Response[v1.ListGameServersResponse], error) {
	return c.listGameServers.CallUnary(ctx, req)
}

// CreateGameServer calls obiente.cloud.gameservers.v1.GameServerService.CreateGameServer.
func (c *gameServerServiceClient) CreateGameServer(ctx context.Context, req *connect.Request[v1.CreateGameServerRequest]) (*connect.Response[v1.CreateGameServerResponse], error) {
	return c.createGameServer.CallUnary(ctx, req)
}

// GetGameServer calls obiente.cloud.gameservers.v1.GameServerService.GetGameServer.
func (c *gameServerServiceClient) GetGameServer(ctx context.Context, req *connect.Request[v1.GetGameServerRequest]) (*connect.Response[v1.GetGameServerResponse], error) {
	return c.getGameServer.CallUnary(ctx, req)
}

// UpdateGameServer calls obiente.cloud.gameservers.v1.GameServerService.UpdateGameServer.
func (c *gameServerServiceClient) UpdateGameServer(ctx context.Context, req *connect.Request[v1.UpdateGameServerRequest]) (*connect.Response[v1.UpdateGameServerResponse], error) {
	return c.updateGameServer.CallUnary(ctx, req)
}

// DeleteGameServer calls obiente.cloud.gameservers.v1.GameServerService.DeleteGameServer.
func (c *gameServerServiceClient) DeleteGameServer(ctx context.Context, req *connect.Request[v1.DeleteGameServerRequest]) (*connect.Response[v1.DeleteGameServerResponse], error) {
	return c.deleteGameServer.CallUnary(ctx, req)
}

// StartGameServer calls obiente.cloud.gameservers.v1.GameServerService.StartGameServer.
func (c *gameServerServiceClient) StartGameServer(ctx context.Context, req *connect.Request[v1.StartGameServerRequest]) (*connect.Response[v1.StartGameServerResponse], error) {
	return c.startGameServer.CallUnary(ctx, req)
}

// StopGameServer calls obiente.cloud.gameservers.v1.GameServerService.StopGameServer.
func (c *gameServerServiceClient) StopGameServer(ctx context.Context, req *connect.Request[v1.StopGameServerRequest]) (*connect.Response[v1.StopGameServerResponse], error) {
	return c.stopGameServer.CallUnary(ctx, req)
}

// RestartGameServer calls obiente.cloud.gameservers.v1.GameServerService.RestartGameServer.
func (c *gameServerServiceClient) RestartGameServer(ctx context.Context, req *connect.Request[v1.RestartGameServerRequest]) (*connect.Response[v1.RestartGameServerResponse], error) {
	return c.restartGameServer.CallUnary(ctx, req)
}

// StreamGameServerStatus calls
// obiente.cloud.gameservers.v1.GameServerService.StreamGameServerStatus.
func (c *gameServerServiceClient) StreamGameServerStatus(ctx context.Context, req *connect.Request[v1.StreamGameServerStatusRequest]) (*connect.ServerStreamForClient[v1.GameServerStatusUpdate], error) {
	return c.streamGameServerStatus.CallServerStream(ctx, req)
}

// GetGameServerLogs calls obiente.cloud.gameservers.v1.GameServerService.GetGameServerLogs.
func (c *gameServerServiceClient) GetGameServerLogs(ctx context.Context, req *connect.Request[v1.GetGameServerLogsRequest]) (*connect.Response[v1.GetGameServerLogsResponse], error) {
	return c.getGameServerLogs.CallUnary(ctx, req)
}

// StreamGameServerLogs calls obiente.cloud.gameservers.v1.GameServerService.StreamGameServerLogs.
func (c *gameServerServiceClient) StreamGameServerLogs(ctx context.Context, req *connect.Request[v1.StreamGameServerLogsRequest]) (*connect.ServerStreamForClient[v1.GameServerLogLine], error) {
	return c.streamGameServerLogs.CallServerStream(ctx, req)
}

// SendGameServerCommand calls obiente.cloud.gameservers.v1.GameServerService.SendGameServerCommand.
func (c *gameServerServiceClient) SendGameServerCommand(ctx context.Context, req *connect.Request[v1.SendGameServerCommandRequest]) (*connect.Response[v1.SendGameServerCommandResponse], error) {
	return c.sendGameServerCommand.CallUnary(ctx, req)
}

// GetGameServerMetrics calls obiente.cloud.gameservers.v1.GameServerService.GetGameServerMetrics.
func (c *gameServerServiceClient) GetGameServerMetrics(ctx context.Context, req *connect.Request[v1.GetGameServerMetricsRequest]) (*connect.Response[v1.GetGameServerMetricsResponse], error) {
	return c.getGameServerMetrics.CallUnary(ctx, req)
}

// StreamGameServerMetrics calls
// obiente.cloud.gameservers.v1.GameServerService.StreamGameServerMetrics.
func (c *gameServerServiceClient) StreamGameServerMetrics(ctx context.Context, req *connect.Request[v1.StreamGameServerMetricsRequest]) (*connect.ServerStreamForClient[v1.GameServerMetric], error) {
	return c.streamGameServerMetrics.CallServerStream(ctx, req)
}

// GetGameServerUsage calls obiente.cloud.gameservers.v1.GameServerService.GetGameServerUsage.
func (c *gameServerServiceClient) GetGameServerUsage(ctx context.Context, req *connect.Request[v1.GetGameServerUsageRequest]) (*connect.Response[v1.GetGameServerUsageResponse], error) {
	return c.getGameServerUsage.CallUnary(ctx, req)
}

// ListGameServerFiles calls obiente.cloud.gameservers.v1.GameServerService.ListGameServerFiles.
func (c *gameServerServiceClient) ListGameServerFiles(ctx context.Context, req *connect.Request[v1.ListGameServerFilesRequest]) (*connect.Response[v1.ListGameServerFilesResponse], error) {
	return c.listGameServerFiles.CallUnary(ctx, req)
}

// GetGameServerFile calls obiente.cloud.gameservers.v1.GameServerService.GetGameServerFile.
func (c *gameServerServiceClient) GetGameServerFile(ctx context.Context, req *connect.Request[v1.GetGameServerFileRequest]) (*connect.Response[v1.GetGameServerFileResponse], error) {
	return c.getGameServerFile.CallUnary(ctx, req)
}

// UploadGameServerFiles calls obiente.cloud.gameservers.v1.GameServerService.UploadGameServerFiles.
func (c *gameServerServiceClient) UploadGameServerFiles(ctx context.Context, req *connect.Request[v1.UploadGameServerFilesRequest]) (*connect.Response[v1.UploadGameServerFilesResponse], error) {
	return c.uploadGameServerFiles.CallUnary(ctx, req)
}

// DeleteGameServerEntries calls
// obiente.cloud.gameservers.v1.GameServerService.DeleteGameServerEntries.
func (c *gameServerServiceClient) DeleteGameServerEntries(ctx context.Context, req *connect.Request[v1.DeleteGameServerEntriesRequest]) (*connect.Response[v1.DeleteGameServerEntriesResponse], error) {
	return c.deleteGameServerEntries.CallUnary(ctx, req)
}

// CreateGameServerEntry calls obiente.cloud.gameservers.v1.GameServerService.CreateGameServerEntry.
func (c *gameServerServiceClient) CreateGameServerEntry(ctx context.Context, req *connect.Request[v1.CreateGameServerEntryRequest]) (*connect.Response[v1.CreateGameServerEntryResponse], error) {
	return c.createGameServerEntry.CallUnary(ctx, req)
}

// WriteGameServerFile calls obiente.cloud.gameservers.v1.GameServerService.WriteGameServerFile.
func (c *gameServerServiceClient) WriteGameServerFile(ctx context.Context, req *connect.Request[v1.WriteGameServerFileRequest]) (*connect.Response[v1.WriteGameServerFileResponse], error) {
	return c.writeGameServerFile.CallUnary(ctx, req)
}

// RenameGameServerEntry calls obiente.cloud.gameservers.v1.GameServerService.RenameGameServerEntry.
func (c *gameServerServiceClient) RenameGameServerEntry(ctx context.Context, req *connect.Request[v1.RenameGameServerEntryRequest]) (*connect.Response[v1.RenameGameServerEntryResponse], error) {
	return c.renameGameServerEntry.CallUnary(ctx, req)
}

// GameServerServiceHandler is an implementation of the
// obiente.cloud.gameservers.v1.GameServerService service.
type GameServerServiceHandler interface {
	// List organization game servers
	ListGameServers(context.Context, *connect.Request[v1.ListGameServersRequest]) (*connect.Response[v1.ListGameServersResponse], error)
	// Create new game server
	CreateGameServer(context.Context, *connect.Request[v1.CreateGameServerRequest]) (*connect.Response[v1.CreateGameServerResponse], error)
	// Get game server details
	GetGameServer(context.Context, *connect.Request[v1.GetGameServerRequest]) (*connect.Response[v1.GetGameServerResponse], error)
	// Update game server configuration
	UpdateGameServer(context.Context, *connect.Request[v1.UpdateGameServerRequest]) (*connect.Response[v1.UpdateGameServerResponse], error)
	// Delete game server
	DeleteGameServer(context.Context, *connect.Request[v1.DeleteGameServerRequest]) (*connect.Response[v1.DeleteGameServerResponse], error)
	// Start a stopped game server
	StartGameServer(context.Context, *connect.Request[v1.StartGameServerRequest]) (*connect.Response[v1.StartGameServerResponse], error)
	// Stop a running game server
	StopGameServer(context.Context, *connect.Request[v1.StopGameServerRequest]) (*connect.Response[v1.StopGameServerResponse], error)
	// Restart a game server
	RestartGameServer(context.Context, *connect.Request[v1.RestartGameServerRequest]) (*connect.Response[v1.RestartGameServerResponse], error)
	// Stream game server status updates
	StreamGameServerStatus(context.Context, *connect.Request[v1.StreamGameServerStatusRequest], *connect.ServerStream[v1.GameServerStatusUpdate]) error
	// Get game server logs
	GetGameServerLogs(context.Context, *connect.Request[v1.GetGameServerLogsRequest]) (*connect.Response[v1.GetGameServerLogsResponse], error)
	// Stream game server logs (tail/follow)
	StreamGameServerLogs(context.Context, *connect.Request[v1.StreamGameServerLogsRequest], *connect.ServerStream[v1.GameServerLogLine]) error
	// Send a command to a running game server
	SendGameServerCommand(context.Context, *connect.Request[v1.SendGameServerCommandRequest]) (*connect.Response[v1.SendGameServerCommandResponse], error)
	// Get game server metrics (real-time or historical)
	GetGameServerMetrics(context.Context, *connect.Request[v1.GetGameServerMetricsRequest]) (*connect.Response[v1.GetGameServerMetricsResponse], error)
	// Stream real-time game server metrics
	StreamGameServerMetrics(context.Context, *connect.Request[v1.StreamGameServerMetricsRequest], *connect.ServerStream[v1.GameServerMetric]) error
	// Get aggregated usage for a game server
	GetGameServerUsage(context.Context, *connect.Request[v1.GetGameServerUsageRequest]) (*connect.Response[v1.GetGameServerUsageResponse], error)
	// File system operations
	// List files in a game server container or volume
	ListGameServerFiles(context.Context, *connect.Request[v1.ListGameServerFilesRequest]) (*connect.Response[v1.ListGameServerFilesResponse], error)
	// Get file contents from a game server container or volume
	GetGameServerFile(context.Context, *connect.Request[v1.GetGameServerFileRequest]) (*connect.Response[v1.GetGameServerFileResponse], error)
	// Upload files to a game server container or volume
	UploadGameServerFiles(context.Context, *connect.Request[v1.UploadGameServerFilesRequest]) (*connect.Response[v1.UploadGameServerFilesResponse], error)
	// Delete files or directories from a game server
	DeleteGameServerEntries(context.Context, *connect.Request[v1.DeleteGameServerEntriesRequest]) (*connect.Response[v1.DeleteGameServerEntriesResponse], error)
	// Create a file, directory, or symlink in a game server
	CreateGameServerEntry(context.Context, *connect.Request[v1.CreateGameServerEntryRequest]) (*connect.Response[v1.CreateGameServerEntryResponse], error)
	// Write or update file contents in a game server
	WriteGameServerFile(context.Context, *connect.Request[v1.WriteGameServerFileRequest]) (*connect.Response[v1.WriteGameServerFileResponse], error)
	// Rename a file or directory in a game server
	RenameGameServerEntry(context.Context, *connect.Request[v1.RenameGameServerEntryRequest]) (*connect.Response[v1.RenameGameServerEntryResponse], error)
}

// NewGameServerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGameServerServiceHandler(svc GameServerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gameServerServiceMethods := v1.File_obiente_cloud_gameservers_v1_game_server_service_proto.Services().ByName("GameServerService").Methods()
	gameServerServiceListGameServersHandler := connect.NewUnaryHandler(
		GameServerServiceListGameServersProcedure,
		svc.ListGameServers,
		connect.WithSchema(gameServerServiceMethods.ByName("ListGameServers")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceCreateGameServerHandler := connect.NewUnaryHandler(
		GameServerServiceCreateGameServerProcedure,
		svc.CreateGameServer,
		connect.WithSchema(gameServerServiceMethods.ByName("CreateGameServer")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceGetGameServerHandler := connect.NewUnaryHandler(
		GameServerServiceGetGameServerProcedure,
		svc.GetGameServer,
		connect.WithSchema(gameServerServiceMethods.ByName("GetGameServer")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceUpdateGameServerHandler := connect.NewUnaryHandler(
		GameServerServiceUpdateGameServerProcedure,
		svc.UpdateGameServer,
		connect.WithSchema(gameServerServiceMethods.ByName("UpdateGameServer")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceDeleteGameServerHandler := connect.NewUnaryHandler(
		GameServerServiceDeleteGameServerProcedure,
		svc.DeleteGameServer,
		connect.WithSchema(gameServerServiceMethods.ByName("DeleteGameServer")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceStartGameServerHandler := connect.NewUnaryHandler(
		GameServerServiceStartGameServerProcedure,
		svc.StartGameServer,
		connect.WithSchema(gameServerServiceMethods.ByName("StartGameServer")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceStopGameServerHandler := connect.NewUnaryHandler(
		GameServerServiceStopGameServerProcedure,
		svc.StopGameServer,
		connect.WithSchema(gameServerServiceMethods.ByName("StopGameServer")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceRestartGameServerHandler := connect.NewUnaryHandler(
		GameServerServiceRestartGameServerProcedure,
		svc.RestartGameServer,
		connect.WithSchema(gameServerServiceMethods.ByName("RestartGameServer")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceStreamGameServerStatusHandler := connect.NewServerStreamHandler(
		GameServerServiceStreamGameServerStatusProcedure,
		svc.StreamGameServerStatus,
		connect.WithSchema(gameServerServiceMethods.ByName("StreamGameServerStatus")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceGetGameServerLogsHandler := connect.NewUnaryHandler(
		GameServerServiceGetGameServerLogsProcedure,
		svc.GetGameServerLogs,
		connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerLogs")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceStreamGameServerLogsHandler := connect.NewServerStreamHandler(
		GameServerServiceStreamGameServerLogsProcedure,
		svc.StreamGameServerLogs,
		connect.WithSchema(gameServerServiceMethods.ByName("StreamGameServerLogs")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceSendGameServerCommandHandler := connect.NewUnaryHandler(
		GameServerServiceSendGameServerCommandProcedure,
		svc.SendGameServerCommand,
		connect.WithSchema(gameServerServiceMethods.ByName("SendGameServerCommand")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceGetGameServerMetricsHandler := connect.NewUnaryHandler(
		GameServerServiceGetGameServerMetricsProcedure,
		svc.GetGameServerMetrics,
		connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceStreamGameServerMetricsHandler := connect.NewServerStreamHandler(
		GameServerServiceStreamGameServerMetricsProcedure,
		svc.StreamGameServerMetrics,
		connect.WithSchema(gameServerServiceMethods.ByName("StreamGameServerMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceGetGameServerUsageHandler := connect.NewUnaryHandler(
		GameServerServiceGetGameServerUsageProcedure,
		svc.GetGameServerUsage,
		connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerUsage")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceListGameServerFilesHandler := connect.NewUnaryHandler(
		GameServerServiceListGameServerFilesProcedure,
		svc.ListGameServerFiles,
		connect.WithSchema(gameServerServiceMethods.ByName("ListGameServerFiles")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceGetGameServerFileHandler := connect.NewUnaryHandler(
		GameServerServiceGetGameServerFileProcedure,
		svc.GetGameServerFile,
		connect.WithSchema(gameServerServiceMethods.ByName("GetGameServerFile")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceUploadGameServerFilesHandler := connect.NewUnaryHandler(
		GameServerServiceUploadGameServerFilesProcedure,
		svc.UploadGameServerFiles,
		connect.WithSchema(gameServerServiceMethods.ByName("UploadGameServerFiles")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceDeleteGameServerEntriesHandler := connect.NewUnaryHandler(
		GameServerServiceDeleteGameServerEntriesProcedure,
		svc.DeleteGameServerEntries,
		connect.WithSchema(gameServerServiceMethods.ByName("DeleteGameServerEntries")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceCreateGameServerEntryHandler := connect.NewUnaryHandler(
		GameServerServiceCreateGameServerEntryProcedure,
		svc.CreateGameServerEntry,
		connect.WithSchema(gameServerServiceMethods.ByName("CreateGameServerEntry")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceWriteGameServerFileHandler := connect.NewUnaryHandler(
		GameServerServiceWriteGameServerFileProcedure,
		svc.WriteGameServerFile,
		connect.WithSchema(gameServerServiceMethods.ByName("WriteGameServerFile")),
		connect.WithHandlerOptions(opts...),
	)
	gameServerServiceRenameGameServerEntryHandler := connect.NewUnaryHandler(
		GameServerServiceRenameGameServerEntryProcedure,
		svc.RenameGameServerEntry,
		connect.WithSchema(gameServerServiceMethods.ByName("RenameGameServerEntry")),
		connect.WithHandlerOptions(opts...),
	)
	return "/obiente.cloud.gameservers.v1.GameServerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GameServerServiceListGameServersProcedure:
			gameServerServiceListGameServersHandler.ServeHTTP(w, r)
		case GameServerServiceCreateGameServerProcedure:
			gameServerServiceCreateGameServerHandler.ServeHTTP(w, r)
		case GameServerServiceGetGameServerProcedure:
			gameServerServiceGetGameServerHandler.ServeHTTP(w, r)
		case GameServerServiceUpdateGameServerProcedure:
			gameServerServiceUpdateGameServerHandler.ServeHTTP(w, r)
		case GameServerServiceDeleteGameServerProcedure:
			gameServerServiceDeleteGameServerHandler.ServeHTTP(w, r)
		case GameServerServiceStartGameServerProcedure:
			gameServerServiceStartGameServerHandler.ServeHTTP(w, r)
		case GameServerServiceStopGameServerProcedure:
			gameServerServiceStopGameServerHandler.ServeHTTP(w, r)
		case GameServerServiceRestartGameServerProcedure:
			gameServerServiceRestartGameServerHandler.ServeHTTP(w, r)
		case GameServerServiceStreamGameServerStatusProcedure:
			gameServerServiceStreamGameServerStatusHandler.ServeHTTP(w, r)
		case GameServerServiceGetGameServerLogsProcedure:
			gameServerServiceGetGameServerLogsHandler.ServeHTTP(w, r)
		case GameServerServiceStreamGameServerLogsProcedure:
			gameServerServiceStreamGameServerLogsHandler.ServeHTTP(w, r)
		case GameServerServiceSendGameServerCommandProcedure:
			gameServerServiceSendGameServerCommandHandler.ServeHTTP(w, r)
		case GameServerServiceGetGameServerMetricsProcedure:
			gameServerServiceGetGameServerMetricsHandler.ServeHTTP(w, r)
		case GameServerServiceStreamGameServerMetricsProcedure:
			gameServerServiceStreamGameServerMetricsHandler.ServeHTTP(w, r)
		case GameServerServiceGetGameServerUsageProcedure:
			gameServerServiceGetGameServerUsageHandler.ServeHTTP(w, r)
		case GameServerServiceListGameServerFilesProcedure:
			gameServerServiceListGameServerFilesHandler.ServeHTTP(w, r)
		case GameServerServiceGetGameServerFileProcedure:
			gameServerServiceGetGameServerFileHandler.ServeHTTP(w, r)
		case GameServerServiceUploadGameServerFilesProcedure:
			gameServerServiceUploadGameServerFilesHandler.ServeHTTP(w, r)
		case GameServerServiceDeleteGameServerEntriesProcedure:
			gameServerServiceDeleteGameServerEntriesHandler.ServeHTTP(w, r)
		case GameServerServiceCreateGameServerEntryProcedure:
			gameServerServiceCreateGameServerEntryHandler.ServeHTTP(w, r)
		case GameServerServiceWriteGameServerFileProcedure:
			gameServerServiceWriteGameServerFileHandler.ServeHTTP(w, r)
		case GameServerServiceRenameGameServerEntryProcedure:
			gameServerServiceRenameGameServerEntryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGameServerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGameServerServiceHandler struct{}

func (UnimplementedGameServerServiceHandler) ListGameServers(context.Context, *connect.Request[v1.ListGameServersRequest]) (*connect.Response[v1.ListGameServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.ListGameServers is not implemented"))
}

func (UnimplementedGameServerServiceHandler) CreateGameServer(context.Context, *connect.Request[v1.CreateGameServerRequest]) (*connect.Response[v1.CreateGameServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.CreateGameServer is not implemented"))
}

func (UnimplementedGameServerServiceHandler) GetGameServer(context.Context, *connect.Request[v1.GetGameServerRequest]) (*connect.Response[v1.GetGameServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.GetGameServer is not implemented"))
}

func (UnimplementedGameServerServiceHandler) UpdateGameServer(context.Context, *connect.Request[v1.UpdateGameServerRequest]) (*connect.Response[v1.UpdateGameServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.UpdateGameServer is not implemented"))
}

func (UnimplementedGameServerServiceHandler) DeleteGameServer(context.Context, *connect.Request[v1.DeleteGameServerRequest]) (*connect.Response[v1.DeleteGameServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.DeleteGameServer is not implemented"))
}

func (UnimplementedGameServerServiceHandler) StartGameServer(context.Context, *connect.Request[v1.StartGameServerRequest]) (*connect.Response[v1.StartGameServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.StartGameServer is not implemented"))
}

func (UnimplementedGameServerServiceHandler) StopGameServer(context.Context, *connect.Request[v1.StopGameServerRequest]) (*connect.Response[v1.StopGameServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.StopGameServer is not implemented"))
}

func (UnimplementedGameServerServiceHandler) RestartGameServer(context.Context, *connect.Request[v1.RestartGameServerRequest]) (*connect.Response[v1.RestartGameServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.RestartGameServer is not implemented"))
}

func (UnimplementedGameServerServiceHandler) StreamGameServerStatus(context.Context, *connect.Request[v1.StreamGameServerStatusRequest], *connect.ServerStream[v1.GameServerStatusUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.StreamGameServerStatus is not implemented"))
}

func (UnimplementedGameServerServiceHandler) GetGameServerLogs(context.Context, *connect.Request[v1.GetGameServerLogsRequest]) (*connect.Response[v1.GetGameServerLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.GetGameServerLogs is not implemented"))
}

func (UnimplementedGameServerServiceHandler) StreamGameServerLogs(context.Context, *connect.Request[v1.StreamGameServerLogsRequest], *connect.ServerStream[v1.GameServerLogLine]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.StreamGameServerLogs is not implemented"))
}

func (UnimplementedGameServerServiceHandler) SendGameServerCommand(context.Context, *connect.Request[v1.SendGameServerCommandRequest]) (*connect.Response[v1.SendGameServerCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.SendGameServerCommand is not implemented"))
}

func (UnimplementedGameServerServiceHandler) GetGameServerMetrics(context.Context, *connect.Request[v1.GetGameServerMetricsRequest]) (*connect.Response[v1.GetGameServerMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.GetGameServerMetrics is not implemented"))
}

func (UnimplementedGameServerServiceHandler) StreamGameServerMetrics(context.Context, *connect.Request[v1.StreamGameServerMetricsRequest], *connect.ServerStream[v1.GameServerMetric]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.StreamGameServerMetrics is not implemented"))
}

func (UnimplementedGameServerServiceHandler) GetGameServerUsage(context.Context, *connect.Request[v1.GetGameServerUsageRequest]) (*connect.Response[v1.GetGameServerUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.GetGameServerUsage is not implemented"))
}

func (UnimplementedGameServerServiceHandler) ListGameServerFiles(context.Context, *connect.Request[v1.ListGameServerFilesRequest]) (*connect.Response[v1.ListGameServerFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.ListGameServerFiles is not implemented"))
}

func (UnimplementedGameServerServiceHandler) GetGameServerFile(context.Context, *connect.Request[v1.GetGameServerFileRequest]) (*connect.Response[v1.GetGameServerFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.GetGameServerFile is not implemented"))
}

func (UnimplementedGameServerServiceHandler) UploadGameServerFiles(context.Context, *connect.Request[v1.UploadGameServerFilesRequest]) (*connect.Response[v1.UploadGameServerFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.UploadGameServerFiles is not implemented"))
}

func (UnimplementedGameServerServiceHandler) DeleteGameServerEntries(context.Context, *connect.Request[v1.DeleteGameServerEntriesRequest]) (*connect.Response[v1.DeleteGameServerEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.DeleteGameServerEntries is not implemented"))
}

func (UnimplementedGameServerServiceHandler) CreateGameServerEntry(context.Context, *connect.Request[v1.CreateGameServerEntryRequest]) (*connect.Response[v1.CreateGameServerEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.CreateGameServerEntry is not implemented"))
}

func (UnimplementedGameServerServiceHandler) WriteGameServerFile(context.Context, *connect.Request[v1.WriteGameServerFileRequest]) (*connect.Response[v1.WriteGameServerFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.WriteGameServerFile is not implemented"))
}

func (UnimplementedGameServerServiceHandler) RenameGameServerEntry(context.Context, *connect.Request[v1.RenameGameServerEntryRequest]) (*connect.Response[v1.RenameGameServerEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("obiente.cloud.gameservers.v1.GameServerService.RenameGameServerEntry is not implemented"))
}
