// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: obiente/cloud/vps/v1/vps_config_service.proto

package vpsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCloudInitConfigRequest requests the cloud-init configuration for a VPS
type GetCloudInitConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCloudInitConfigRequest) Reset() {
	*x = GetCloudInitConfigRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudInitConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudInitConfigRequest) ProtoMessage() {}

func (x *GetCloudInitConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudInitConfigRequest.ProtoReflect.Descriptor instead.
func (*GetCloudInitConfigRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCloudInitConfigRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetCloudInitConfigRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

// GetCloudInitConfigResponse returns the cloud-init configuration
type GetCloudInitConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudInit     *CloudInitConfig       `protobuf:"bytes,1,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudInitConfigResponse) Reset() {
	*x = GetCloudInitConfigResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudInitConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudInitConfigResponse) ProtoMessage() {}

func (x *GetCloudInitConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudInitConfigResponse.ProtoReflect.Descriptor instead.
func (*GetCloudInitConfigResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCloudInitConfigResponse) GetCloudInit() *CloudInitConfig {
	if x != nil {
		return x.CloudInit
	}
	return nil
}

// UpdateCloudInitConfigRequest updates the cloud-init configuration
type UpdateCloudInitConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	CloudInit      *CloudInitConfig       `protobuf:"bytes,3,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCloudInitConfigRequest) Reset() {
	*x = UpdateCloudInitConfigRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCloudInitConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCloudInitConfigRequest) ProtoMessage() {}

func (x *UpdateCloudInitConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCloudInitConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateCloudInitConfigRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCloudInitConfigRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateCloudInitConfigRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *UpdateCloudInitConfigRequest) GetCloudInit() *CloudInitConfig {
	if x != nil {
		return x.CloudInit
	}
	return nil
}

// UpdateCloudInitConfigResponse confirms the update
type UpdateCloudInitConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudInit     *CloudInitConfig       `protobuf:"bytes,1,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Information message about when changes take effect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCloudInitConfigResponse) Reset() {
	*x = UpdateCloudInitConfigResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCloudInitConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCloudInitConfigResponse) ProtoMessage() {}

func (x *UpdateCloudInitConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCloudInitConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateCloudInitConfigResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCloudInitConfigResponse) GetCloudInit() *CloudInitConfig {
	if x != nil {
		return x.CloudInit
	}
	return nil
}

func (x *UpdateCloudInitConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListVPSUsersRequest lists all users configured for a VPS
type ListVPSUsersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListVPSUsersRequest) Reset() {
	*x = ListVPSUsersRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVPSUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVPSUsersRequest) ProtoMessage() {}

func (x *ListVPSUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVPSUsersRequest.ProtoReflect.Descriptor instead.
func (*ListVPSUsersRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListVPSUsersRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListVPSUsersRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

// ListVPSUsersResponse returns the list of users
type ListVPSUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*VPSUser             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVPSUsersResponse) Reset() {
	*x = ListVPSUsersResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVPSUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVPSUsersResponse) ProtoMessage() {}

func (x *ListVPSUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVPSUsersResponse.ProtoReflect.Descriptor instead.
func (*ListVPSUsersResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListVPSUsersResponse) GetUsers() []*VPSUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// VPSUser represents a user configured on a VPS instance
type VPSUser struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HasPassword       bool                   `protobuf:"varint,2,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`                    // Whether user has a password set (password itself is never returned)
	SshAuthorizedKeys []string               `protobuf:"bytes,3,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys,proto3" json:"ssh_authorized_keys,omitempty"` // SSH public keys
	Sudo              bool                   `protobuf:"varint,4,opt,name=sudo,proto3" json:"sudo,omitempty"`
	SudoNopasswd      bool                   `protobuf:"varint,5,opt,name=sudo_nopasswd,json=sudoNopasswd,proto3" json:"sudo_nopasswd,omitempty"`
	Groups            []string               `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	Shell             *string                `protobuf:"bytes,7,opt,name=shell,proto3,oneof" json:"shell,omitempty"`
	LockPasswd        bool                   `protobuf:"varint,8,opt,name=lock_passwd,json=lockPasswd,proto3" json:"lock_passwd,omitempty"`
	Gecos             *string                `protobuf:"bytes,9,opt,name=gecos,proto3,oneof" json:"gecos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VPSUser) Reset() {
	*x = VPSUser{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPSUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPSUser) ProtoMessage() {}

func (x *VPSUser) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPSUser.ProtoReflect.Descriptor instead.
func (*VPSUser) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{6}
}

func (x *VPSUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VPSUser) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *VPSUser) GetSshAuthorizedKeys() []string {
	if x != nil {
		return x.SshAuthorizedKeys
	}
	return nil
}

func (x *VPSUser) GetSudo() bool {
	if x != nil {
		return x.Sudo
	}
	return false
}

func (x *VPSUser) GetSudoNopasswd() bool {
	if x != nil {
		return x.SudoNopasswd
	}
	return false
}

func (x *VPSUser) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *VPSUser) GetShell() string {
	if x != nil && x.Shell != nil {
		return *x.Shell
	}
	return ""
}

func (x *VPSUser) GetLockPasswd() bool {
	if x != nil {
		return x.LockPasswd
	}
	return false
}

func (x *VPSUser) GetGecos() string {
	if x != nil && x.Gecos != nil {
		return *x.Gecos
	}
	return ""
}

// CreateVPSUserRequest creates a new user
type CreateVPSUserRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId             string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password          *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	SshAuthorizedKeys []string               `protobuf:"bytes,5,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys,proto3" json:"ssh_authorized_keys,omitempty"`
	Sudo              *bool                  `protobuf:"varint,6,opt,name=sudo,proto3,oneof" json:"sudo,omitempty"`
	SudoNopasswd      *bool                  `protobuf:"varint,7,opt,name=sudo_nopasswd,json=sudoNopasswd,proto3,oneof" json:"sudo_nopasswd,omitempty"`
	Groups            []string               `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	Shell             *string                `protobuf:"bytes,9,opt,name=shell,proto3,oneof" json:"shell,omitempty"`
	LockPasswd        *bool                  `protobuf:"varint,10,opt,name=lock_passwd,json=lockPasswd,proto3,oneof" json:"lock_passwd,omitempty"`
	Gecos             *string                `protobuf:"bytes,11,opt,name=gecos,proto3,oneof" json:"gecos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateVPSUserRequest) Reset() {
	*x = CreateVPSUserRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVPSUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVPSUserRequest) ProtoMessage() {}

func (x *CreateVPSUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVPSUserRequest.ProtoReflect.Descriptor instead.
func (*CreateVPSUserRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVPSUserRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateVPSUserRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *CreateVPSUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVPSUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CreateVPSUserRequest) GetSshAuthorizedKeys() []string {
	if x != nil {
		return x.SshAuthorizedKeys
	}
	return nil
}

func (x *CreateVPSUserRequest) GetSudo() bool {
	if x != nil && x.Sudo != nil {
		return *x.Sudo
	}
	return false
}

func (x *CreateVPSUserRequest) GetSudoNopasswd() bool {
	if x != nil && x.SudoNopasswd != nil {
		return *x.SudoNopasswd
	}
	return false
}

func (x *CreateVPSUserRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *CreateVPSUserRequest) GetShell() string {
	if x != nil && x.Shell != nil {
		return *x.Shell
	}
	return ""
}

func (x *CreateVPSUserRequest) GetLockPasswd() bool {
	if x != nil && x.LockPasswd != nil {
		return *x.LockPasswd
	}
	return false
}

func (x *CreateVPSUserRequest) GetGecos() string {
	if x != nil && x.Gecos != nil {
		return *x.Gecos
	}
	return ""
}

// CreateVPSUserResponse confirms user creation
type CreateVPSUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *VPSUser               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Information about when user will be created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVPSUserResponse) Reset() {
	*x = CreateVPSUserResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVPSUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVPSUserResponse) ProtoMessage() {}

func (x *CreateVPSUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVPSUserResponse.ProtoReflect.Descriptor instead.
func (*CreateVPSUserResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVPSUserResponse) GetUser() *VPSUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateVPSUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateVPSUserRequest updates an existing user
type UpdateVPSUserRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId             string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                            // User name to update
	NewName           *string                `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3,oneof" json:"new_name,omitempty"` // New name (if renaming)
	SshAuthorizedKeys []string               `protobuf:"bytes,5,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys,proto3" json:"ssh_authorized_keys,omitempty"`
	Sudo              *bool                  `protobuf:"varint,6,opt,name=sudo,proto3,oneof" json:"sudo,omitempty"`
	SudoNopasswd      *bool                  `protobuf:"varint,7,opt,name=sudo_nopasswd,json=sudoNopasswd,proto3,oneof" json:"sudo_nopasswd,omitempty"`
	Groups            []string               `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	Shell             *string                `protobuf:"bytes,9,opt,name=shell,proto3,oneof" json:"shell,omitempty"`
	LockPasswd        *bool                  `protobuf:"varint,10,opt,name=lock_passwd,json=lockPasswd,proto3,oneof" json:"lock_passwd,omitempty"`
	Gecos             *string                `protobuf:"bytes,11,opt,name=gecos,proto3,oneof" json:"gecos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateVPSUserRequest) Reset() {
	*x = UpdateVPSUserRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVPSUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVPSUserRequest) ProtoMessage() {}

func (x *UpdateVPSUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVPSUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateVPSUserRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateVPSUserRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateVPSUserRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *UpdateVPSUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVPSUserRequest) GetNewName() string {
	if x != nil && x.NewName != nil {
		return *x.NewName
	}
	return ""
}

func (x *UpdateVPSUserRequest) GetSshAuthorizedKeys() []string {
	if x != nil {
		return x.SshAuthorizedKeys
	}
	return nil
}

func (x *UpdateVPSUserRequest) GetSudo() bool {
	if x != nil && x.Sudo != nil {
		return *x.Sudo
	}
	return false
}

func (x *UpdateVPSUserRequest) GetSudoNopasswd() bool {
	if x != nil && x.SudoNopasswd != nil {
		return *x.SudoNopasswd
	}
	return false
}

func (x *UpdateVPSUserRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UpdateVPSUserRequest) GetShell() string {
	if x != nil && x.Shell != nil {
		return *x.Shell
	}
	return ""
}

func (x *UpdateVPSUserRequest) GetLockPasswd() bool {
	if x != nil && x.LockPasswd != nil {
		return *x.LockPasswd
	}
	return false
}

func (x *UpdateVPSUserRequest) GetGecos() string {
	if x != nil && x.Gecos != nil {
		return *x.Gecos
	}
	return ""
}

// UpdateVPSUserResponse confirms the update
type UpdateVPSUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *VPSUser               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVPSUserResponse) Reset() {
	*x = UpdateVPSUserResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVPSUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVPSUserResponse) ProtoMessage() {}

func (x *UpdateVPSUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVPSUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateVPSUserResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVPSUserResponse) GetUser() *VPSUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateVPSUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteVPSUserRequest deletes a user
type DeleteVPSUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // User name to delete
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteVPSUserRequest) Reset() {
	*x = DeleteVPSUserRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVPSUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVPSUserRequest) ProtoMessage() {}

func (x *DeleteVPSUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVPSUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteVPSUserRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteVPSUserRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeleteVPSUserRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *DeleteVPSUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteVPSUserResponse confirms deletion
type DeleteVPSUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVPSUserResponse) Reset() {
	*x = DeleteVPSUserResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVPSUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVPSUserResponse) ProtoMessage() {}

func (x *DeleteVPSUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVPSUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteVPSUserResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVPSUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SetUserPasswordRequest sets or resets a user's password
type SetUserPasswordRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	UserName       string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password       string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"` // New password (will be hashed and stored in cloud-init)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetUserPasswordRequest) Reset() {
	*x = SetUserPasswordRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordRequest) ProtoMessage() {}

func (x *SetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserPasswordRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SetUserPasswordRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *SetUserPasswordRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SetUserPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// SetUserPasswordResponse confirms password update
type SetUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Information about when password will take effect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPasswordResponse) Reset() {
	*x = SetUserPasswordResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordResponse) ProtoMessage() {}

func (x *SetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{14}
}

func (x *SetUserPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateUserSSHKeysRequest updates SSH keys for a user
type UpdateUserSSHKeysRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	UserName       string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	SshKeyIds      []string               `protobuf:"bytes,4,rep,name=ssh_key_ids,json=sshKeyIds,proto3" json:"ssh_key_ids,omitempty"` // SSH key IDs from organization/VPS SSH keys
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserSSHKeysRequest) Reset() {
	*x = UpdateUserSSHKeysRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSSHKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSSHKeysRequest) ProtoMessage() {}

func (x *UpdateUserSSHKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSSHKeysRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserSSHKeysRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserSSHKeysRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateUserSSHKeysRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *UpdateUserSSHKeysRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateUserSSHKeysRequest) GetSshKeyIds() []string {
	if x != nil {
		return x.SshKeyIds
	}
	return nil
}

// UpdateUserSSHKeysResponse confirms the update
type UpdateUserSSHKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *VPSUser               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSSHKeysResponse) Reset() {
	*x = UpdateUserSSHKeysResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSSHKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSSHKeysResponse) ProtoMessage() {}

func (x *UpdateUserSSHKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSSHKeysResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserSSHKeysResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserSSHKeysResponse) GetUser() *VPSUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserSSHKeysResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RotateTerminalKeyRequest rotates the web terminal SSH key
type RotateTerminalKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RotateTerminalKeyRequest) Reset() {
	*x = RotateTerminalKeyRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTerminalKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTerminalKeyRequest) ProtoMessage() {}

func (x *RotateTerminalKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTerminalKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateTerminalKeyRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{17}
}

func (x *RotateTerminalKeyRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RotateTerminalKeyRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

// RotateTerminalKeyResponse confirms the key rotation
type RotateTerminalKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"` // Fingerprint of the new key
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`         // Information about when the new key will take effect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateTerminalKeyResponse) Reset() {
	*x = RotateTerminalKeyResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTerminalKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTerminalKeyResponse) ProtoMessage() {}

func (x *RotateTerminalKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTerminalKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateTerminalKeyResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{18}
}

func (x *RotateTerminalKeyResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RotateTerminalKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RemoveTerminalKeyRequest removes the web terminal SSH key
type RemoveTerminalKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveTerminalKeyRequest) Reset() {
	*x = RemoveTerminalKeyRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTerminalKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTerminalKeyRequest) ProtoMessage() {}

func (x *RemoveTerminalKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTerminalKeyRequest.ProtoReflect.Descriptor instead.
func (*RemoveTerminalKeyRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveTerminalKeyRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RemoveTerminalKeyRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

// RemoveTerminalKeyResponse confirms the key removal
type RemoveTerminalKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Information about when the key will be removed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTerminalKeyResponse) Reset() {
	*x = RemoveTerminalKeyResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTerminalKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTerminalKeyResponse) ProtoMessage() {}

func (x *RemoveTerminalKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTerminalKeyResponse.ProtoReflect.Descriptor instead.
func (*RemoveTerminalKeyResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveTerminalKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetTerminalKeyRequest gets the web terminal SSH key status
type GetTerminalKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTerminalKeyRequest) Reset() {
	*x = GetTerminalKeyRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalKeyRequest) ProtoMessage() {}

func (x *GetTerminalKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalKeyRequest.ProtoReflect.Descriptor instead.
func (*GetTerminalKeyRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetTerminalKeyRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetTerminalKeyRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

// GetTerminalKeyResponse returns the terminal key status
type GetTerminalKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`              // Fingerprint of the key
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Timestamp when the key was created
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Timestamp when the key was last updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalKeyResponse) Reset() {
	*x = GetTerminalKeyResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalKeyResponse) ProtoMessage() {}

func (x *GetTerminalKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalKeyResponse.ProtoReflect.Descriptor instead.
func (*GetTerminalKeyResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetTerminalKeyResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *GetTerminalKeyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetTerminalKeyResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RotateBastionKeyRequest rotates the bastion SSH key
type RotateBastionKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RotateBastionKeyRequest) Reset() {
	*x = RotateBastionKeyRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateBastionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateBastionKeyRequest) ProtoMessage() {}

func (x *RotateBastionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateBastionKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateBastionKeyRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{23}
}

func (x *RotateBastionKeyRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RotateBastionKeyRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

// RotateBastionKeyResponse confirms the key rotation
type RotateBastionKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"` // Fingerprint of the new key
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`         // Information about when the new key will take effect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateBastionKeyResponse) Reset() {
	*x = RotateBastionKeyResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateBastionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateBastionKeyResponse) ProtoMessage() {}

func (x *RotateBastionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateBastionKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateBastionKeyResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{24}
}

func (x *RotateBastionKeyResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RotateBastionKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetBastionKeyRequest gets the bastion SSH key status
type GetBastionKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBastionKeyRequest) Reset() {
	*x = GetBastionKeyRequest{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBastionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBastionKeyRequest) ProtoMessage() {}

func (x *GetBastionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBastionKeyRequest.ProtoReflect.Descriptor instead.
func (*GetBastionKeyRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetBastionKeyRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetBastionKeyRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

// GetBastionKeyResponse returns the bastion key status
type GetBastionKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`              // Fingerprint of the key
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Timestamp when the key was created
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Timestamp when the key was last updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBastionKeyResponse) Reset() {
	*x = GetBastionKeyResponse{}
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBastionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBastionKeyResponse) ProtoMessage() {}

func (x *GetBastionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBastionKeyResponse.ProtoReflect.Descriptor instead.
func (*GetBastionKeyResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetBastionKeyResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *GetBastionKeyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetBastionKeyResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_obiente_cloud_vps_v1_vps_config_service_proto protoreflect.FileDescriptor

const file_obiente_cloud_vps_v1_vps_config_service_proto_rawDesc = "" +
	"\n" +
	"-obiente/cloud/vps/v1/vps_config_service.proto\x12\x14obiente.cloud.vps.v1\x1a&obiente/cloud/vps/v1/vps_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\x19GetCloudInitConfigRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\"b\n" +
	"\x1aGetCloudInitConfigResponse\x12D\n" +
	"\n" +
	"cloud_init\x18\x01 \x01(\v2%.obiente.cloud.vps.v1.CloudInitConfigR\tcloudInit\"\xa4\x01\n" +
	"\x1cUpdateCloudInitConfigRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\x12D\n" +
	"\n" +
	"cloud_init\x18\x03 \x01(\v2%.obiente.cloud.vps.v1.CloudInitConfigR\tcloudInit\"\x7f\n" +
	"\x1dUpdateCloudInitConfigResponse\x12D\n" +
	"\n" +
	"cloud_init\x18\x01 \x01(\v2%.obiente.cloud.vps.v1.CloudInitConfigR\tcloudInit\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x13ListVPSUsersRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\"K\n" +
	"\x14ListVPSUsersResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.obiente.cloud.vps.v1.VPSUserR\x05users\"\xac\x02\n" +
	"\aVPSUser\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fhas_password\x18\x02 \x01(\bR\vhasPassword\x12.\n" +
	"\x13ssh_authorized_keys\x18\x03 \x03(\tR\x11sshAuthorizedKeys\x12\x12\n" +
	"\x04sudo\x18\x04 \x01(\bR\x04sudo\x12#\n" +
	"\rsudo_nopasswd\x18\x05 \x01(\bR\fsudoNopasswd\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\tR\x06groups\x12\x19\n" +
	"\x05shell\x18\a \x01(\tH\x00R\x05shell\x88\x01\x01\x12\x1f\n" +
	"\vlock_passwd\x18\b \x01(\bR\n" +
	"lockPasswd\x12\x19\n" +
	"\x05gecos\x18\t \x01(\tH\x01R\x05gecos\x88\x01\x01B\b\n" +
	"\x06_shellB\b\n" +
	"\x06_gecos\"\xbe\x03\n" +
	"\x14CreateVPSUserRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x00R\bpassword\x88\x01\x01\x12.\n" +
	"\x13ssh_authorized_keys\x18\x05 \x03(\tR\x11sshAuthorizedKeys\x12\x17\n" +
	"\x04sudo\x18\x06 \x01(\bH\x01R\x04sudo\x88\x01\x01\x12(\n" +
	"\rsudo_nopasswd\x18\a \x01(\bH\x02R\fsudoNopasswd\x88\x01\x01\x12\x16\n" +
	"\x06groups\x18\b \x03(\tR\x06groups\x12\x19\n" +
	"\x05shell\x18\t \x01(\tH\x03R\x05shell\x88\x01\x01\x12$\n" +
	"\vlock_passwd\x18\n" +
	" \x01(\bH\x04R\n" +
	"lockPasswd\x88\x01\x01\x12\x19\n" +
	"\x05gecos\x18\v \x01(\tH\x05R\x05gecos\x88\x01\x01B\v\n" +
	"\t_passwordB\a\n" +
	"\x05_sudoB\x10\n" +
	"\x0e_sudo_nopasswdB\b\n" +
	"\x06_shellB\x0e\n" +
	"\f_lock_passwdB\b\n" +
	"\x06_gecos\"d\n" +
	"\x15CreateVPSUserResponse\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.obiente.cloud.vps.v1.VPSUserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbd\x03\n" +
	"\x14UpdateVPSUserRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1e\n" +
	"\bnew_name\x18\x04 \x01(\tH\x00R\anewName\x88\x01\x01\x12.\n" +
	"\x13ssh_authorized_keys\x18\x05 \x03(\tR\x11sshAuthorizedKeys\x12\x17\n" +
	"\x04sudo\x18\x06 \x01(\bH\x01R\x04sudo\x88\x01\x01\x12(\n" +
	"\rsudo_nopasswd\x18\a \x01(\bH\x02R\fsudoNopasswd\x88\x01\x01\x12\x16\n" +
	"\x06groups\x18\b \x03(\tR\x06groups\x12\x19\n" +
	"\x05shell\x18\t \x01(\tH\x03R\x05shell\x88\x01\x01\x12$\n" +
	"\vlock_passwd\x18\n" +
	" \x01(\bH\x04R\n" +
	"lockPasswd\x88\x01\x01\x12\x19\n" +
	"\x05gecos\x18\v \x01(\tH\x05R\x05gecos\x88\x01\x01B\v\n" +
	"\t_new_nameB\a\n" +
	"\x05_sudoB\x10\n" +
	"\x0e_sudo_nopasswdB\b\n" +
	"\x06_shellB\x0e\n" +
	"\f_lock_passwdB\b\n" +
	"\x06_gecos\"d\n" +
	"\x15UpdateVPSUserResponse\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.obiente.cloud.vps.v1.VPSUserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x14DeleteVPSUserRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"1\n" +
	"\x15DeleteVPSUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x91\x01\n" +
	"\x16SetUserPasswordRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"3\n" +
	"\x17SetUserPasswordResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x97\x01\n" +
	"\x18UpdateUserSSHKeysRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1e\n" +
	"\vssh_key_ids\x18\x04 \x03(\tR\tsshKeyIds\"h\n" +
	"\x19UpdateUserSSHKeysResponse\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.obiente.cloud.vps.v1.VPSUserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x18RotateTerminalKeyRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\"W\n" +
	"\x19RotateTerminalKeyResponse\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x18RemoveTerminalKeyRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\"5\n" +
	"\x19RemoveTerminalKeyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x15GetTerminalKeyRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\"\xb0\x01\n" +
	"\x16GetTerminalKeyResponse\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Y\n" +
	"\x17RotateBastionKeyRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\"V\n" +
	"\x18RotateBastionKeyResponse\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x14GetBastionKeyRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\"\xaf\x01\n" +
	"\x15GetBastionKeyResponse\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xcf\v\n" +
	"\x10VPSConfigService\x12w\n" +
	"\x12GetCloudInitConfig\x12/.obiente.cloud.vps.v1.GetCloudInitConfigRequest\x1a0.obiente.cloud.vps.v1.GetCloudInitConfigResponse\x12\x80\x01\n" +
	"\x15UpdateCloudInitConfig\x122.obiente.cloud.vps.v1.UpdateCloudInitConfigRequest\x1a3.obiente.cloud.vps.v1.UpdateCloudInitConfigResponse\x12e\n" +
	"\fListVPSUsers\x12).obiente.cloud.vps.v1.ListVPSUsersRequest\x1a*.obiente.cloud.vps.v1.ListVPSUsersResponse\x12h\n" +
	"\rCreateVPSUser\x12*.obiente.cloud.vps.v1.CreateVPSUserRequest\x1a+.obiente.cloud.vps.v1.CreateVPSUserResponse\x12h\n" +
	"\rUpdateVPSUser\x12*.obiente.cloud.vps.v1.UpdateVPSUserRequest\x1a+.obiente.cloud.vps.v1.UpdateVPSUserResponse\x12h\n" +
	"\rDeleteVPSUser\x12*.obiente.cloud.vps.v1.DeleteVPSUserRequest\x1a+.obiente.cloud.vps.v1.DeleteVPSUserResponse\x12n\n" +
	"\x0fSetUserPassword\x12,.obiente.cloud.vps.v1.SetUserPasswordRequest\x1a-.obiente.cloud.vps.v1.SetUserPasswordResponse\x12t\n" +
	"\x11UpdateUserSSHKeys\x12..obiente.cloud.vps.v1.UpdateUserSSHKeysRequest\x1a/.obiente.cloud.vps.v1.UpdateUserSSHKeysResponse\x12t\n" +
	"\x11RotateTerminalKey\x12..obiente.cloud.vps.v1.RotateTerminalKeyRequest\x1a/.obiente.cloud.vps.v1.RotateTerminalKeyResponse\x12t\n" +
	"\x11RemoveTerminalKey\x12..obiente.cloud.vps.v1.RemoveTerminalKeyRequest\x1a/.obiente.cloud.vps.v1.RemoveTerminalKeyResponse\x12k\n" +
	"\x0eGetTerminalKey\x12+.obiente.cloud.vps.v1.GetTerminalKeyRequest\x1a,.obiente.cloud.vps.v1.GetTerminalKeyResponse\x12q\n" +
	"\x10RotateBastionKey\x12-.obiente.cloud.vps.v1.RotateBastionKeyRequest\x1a..obiente.cloud.vps.v1.RotateBastionKeyResponse\x12h\n" +
	"\rGetBastionKey\x12*.obiente.cloud.vps.v1.GetBastionKeyRequest\x1a+.obiente.cloud.vps.v1.GetBastionKeyResponseBGZEgithub.com/obiente/cloud/apps/shared/proto/obiente/cloud/vps/v1;vpsv1b\x06proto3"

var (
	file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescOnce sync.Once
	file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescData []byte
)

func file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescGZIP() []byte {
	file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescOnce.Do(func() {
		file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_obiente_cloud_vps_v1_vps_config_service_proto_rawDesc), len(file_obiente_cloud_vps_v1_vps_config_service_proto_rawDesc)))
	})
	return file_obiente_cloud_vps_v1_vps_config_service_proto_rawDescData
}

var file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_obiente_cloud_vps_v1_vps_config_service_proto_goTypes = []any{
	(*GetCloudInitConfigRequest)(nil),     // 0: obiente.cloud.vps.v1.GetCloudInitConfigRequest
	(*GetCloudInitConfigResponse)(nil),    // 1: obiente.cloud.vps.v1.GetCloudInitConfigResponse
	(*UpdateCloudInitConfigRequest)(nil),  // 2: obiente.cloud.vps.v1.UpdateCloudInitConfigRequest
	(*UpdateCloudInitConfigResponse)(nil), // 3: obiente.cloud.vps.v1.UpdateCloudInitConfigResponse
	(*ListVPSUsersRequest)(nil),           // 4: obiente.cloud.vps.v1.ListVPSUsersRequest
	(*ListVPSUsersResponse)(nil),          // 5: obiente.cloud.vps.v1.ListVPSUsersResponse
	(*VPSUser)(nil),                       // 6: obiente.cloud.vps.v1.VPSUser
	(*CreateVPSUserRequest)(nil),          // 7: obiente.cloud.vps.v1.CreateVPSUserRequest
	(*CreateVPSUserResponse)(nil),         // 8: obiente.cloud.vps.v1.CreateVPSUserResponse
	(*UpdateVPSUserRequest)(nil),          // 9: obiente.cloud.vps.v1.UpdateVPSUserRequest
	(*UpdateVPSUserResponse)(nil),         // 10: obiente.cloud.vps.v1.UpdateVPSUserResponse
	(*DeleteVPSUserRequest)(nil),          // 11: obiente.cloud.vps.v1.DeleteVPSUserRequest
	(*DeleteVPSUserResponse)(nil),         // 12: obiente.cloud.vps.v1.DeleteVPSUserResponse
	(*SetUserPasswordRequest)(nil),        // 13: obiente.cloud.vps.v1.SetUserPasswordRequest
	(*SetUserPasswordResponse)(nil),       // 14: obiente.cloud.vps.v1.SetUserPasswordResponse
	(*UpdateUserSSHKeysRequest)(nil),      // 15: obiente.cloud.vps.v1.UpdateUserSSHKeysRequest
	(*UpdateUserSSHKeysResponse)(nil),     // 16: obiente.cloud.vps.v1.UpdateUserSSHKeysResponse
	(*RotateTerminalKeyRequest)(nil),      // 17: obiente.cloud.vps.v1.RotateTerminalKeyRequest
	(*RotateTerminalKeyResponse)(nil),     // 18: obiente.cloud.vps.v1.RotateTerminalKeyResponse
	(*RemoveTerminalKeyRequest)(nil),      // 19: obiente.cloud.vps.v1.RemoveTerminalKeyRequest
	(*RemoveTerminalKeyResponse)(nil),     // 20: obiente.cloud.vps.v1.RemoveTerminalKeyResponse
	(*GetTerminalKeyRequest)(nil),         // 21: obiente.cloud.vps.v1.GetTerminalKeyRequest
	(*GetTerminalKeyResponse)(nil),        // 22: obiente.cloud.vps.v1.GetTerminalKeyResponse
	(*RotateBastionKeyRequest)(nil),       // 23: obiente.cloud.vps.v1.RotateBastionKeyRequest
	(*RotateBastionKeyResponse)(nil),      // 24: obiente.cloud.vps.v1.RotateBastionKeyResponse
	(*GetBastionKeyRequest)(nil),          // 25: obiente.cloud.vps.v1.GetBastionKeyRequest
	(*GetBastionKeyResponse)(nil),         // 26: obiente.cloud.vps.v1.GetBastionKeyResponse
	(*CloudInitConfig)(nil),               // 27: obiente.cloud.vps.v1.CloudInitConfig
	(*timestamppb.Timestamp)(nil),         // 28: google.protobuf.Timestamp
}
var file_obiente_cloud_vps_v1_vps_config_service_proto_depIdxs = []int32{
	27, // 0: obiente.cloud.vps.v1.GetCloudInitConfigResponse.cloud_init:type_name -> obiente.cloud.vps.v1.CloudInitConfig
	27, // 1: obiente.cloud.vps.v1.UpdateCloudInitConfigRequest.cloud_init:type_name -> obiente.cloud.vps.v1.CloudInitConfig
	27, // 2: obiente.cloud.vps.v1.UpdateCloudInitConfigResponse.cloud_init:type_name -> obiente.cloud.vps.v1.CloudInitConfig
	6,  // 3: obiente.cloud.vps.v1.ListVPSUsersResponse.users:type_name -> obiente.cloud.vps.v1.VPSUser
	6,  // 4: obiente.cloud.vps.v1.CreateVPSUserResponse.user:type_name -> obiente.cloud.vps.v1.VPSUser
	6,  // 5: obiente.cloud.vps.v1.UpdateVPSUserResponse.user:type_name -> obiente.cloud.vps.v1.VPSUser
	6,  // 6: obiente.cloud.vps.v1.UpdateUserSSHKeysResponse.user:type_name -> obiente.cloud.vps.v1.VPSUser
	28, // 7: obiente.cloud.vps.v1.GetTerminalKeyResponse.created_at:type_name -> google.protobuf.Timestamp
	28, // 8: obiente.cloud.vps.v1.GetTerminalKeyResponse.updated_at:type_name -> google.protobuf.Timestamp
	28, // 9: obiente.cloud.vps.v1.GetBastionKeyResponse.created_at:type_name -> google.protobuf.Timestamp
	28, // 10: obiente.cloud.vps.v1.GetBastionKeyResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: obiente.cloud.vps.v1.VPSConfigService.GetCloudInitConfig:input_type -> obiente.cloud.vps.v1.GetCloudInitConfigRequest
	2,  // 12: obiente.cloud.vps.v1.VPSConfigService.UpdateCloudInitConfig:input_type -> obiente.cloud.vps.v1.UpdateCloudInitConfigRequest
	4,  // 13: obiente.cloud.vps.v1.VPSConfigService.ListVPSUsers:input_type -> obiente.cloud.vps.v1.ListVPSUsersRequest
	7,  // 14: obiente.cloud.vps.v1.VPSConfigService.CreateVPSUser:input_type -> obiente.cloud.vps.v1.CreateVPSUserRequest
	9,  // 15: obiente.cloud.vps.v1.VPSConfigService.UpdateVPSUser:input_type -> obiente.cloud.vps.v1.UpdateVPSUserRequest
	11, // 16: obiente.cloud.vps.v1.VPSConfigService.DeleteVPSUser:input_type -> obiente.cloud.vps.v1.DeleteVPSUserRequest
	13, // 17: obiente.cloud.vps.v1.VPSConfigService.SetUserPassword:input_type -> obiente.cloud.vps.v1.SetUserPasswordRequest
	15, // 18: obiente.cloud.vps.v1.VPSConfigService.UpdateUserSSHKeys:input_type -> obiente.cloud.vps.v1.UpdateUserSSHKeysRequest
	17, // 19: obiente.cloud.vps.v1.VPSConfigService.RotateTerminalKey:input_type -> obiente.cloud.vps.v1.RotateTerminalKeyRequest
	19, // 20: obiente.cloud.vps.v1.VPSConfigService.RemoveTerminalKey:input_type -> obiente.cloud.vps.v1.RemoveTerminalKeyRequest
	21, // 21: obiente.cloud.vps.v1.VPSConfigService.GetTerminalKey:input_type -> obiente.cloud.vps.v1.GetTerminalKeyRequest
	23, // 22: obiente.cloud.vps.v1.VPSConfigService.RotateBastionKey:input_type -> obiente.cloud.vps.v1.RotateBastionKeyRequest
	25, // 23: obiente.cloud.vps.v1.VPSConfigService.GetBastionKey:input_type -> obiente.cloud.vps.v1.GetBastionKeyRequest
	1,  // 24: obiente.cloud.vps.v1.VPSConfigService.GetCloudInitConfig:output_type -> obiente.cloud.vps.v1.GetCloudInitConfigResponse
	3,  // 25: obiente.cloud.vps.v1.VPSConfigService.UpdateCloudInitConfig:output_type -> obiente.cloud.vps.v1.UpdateCloudInitConfigResponse
	5,  // 26: obiente.cloud.vps.v1.VPSConfigService.ListVPSUsers:output_type -> obiente.cloud.vps.v1.ListVPSUsersResponse
	8,  // 27: obiente.cloud.vps.v1.VPSConfigService.CreateVPSUser:output_type -> obiente.cloud.vps.v1.CreateVPSUserResponse
	10, // 28: obiente.cloud.vps.v1.VPSConfigService.UpdateVPSUser:output_type -> obiente.cloud.vps.v1.UpdateVPSUserResponse
	12, // 29: obiente.cloud.vps.v1.VPSConfigService.DeleteVPSUser:output_type -> obiente.cloud.vps.v1.DeleteVPSUserResponse
	14, // 30: obiente.cloud.vps.v1.VPSConfigService.SetUserPassword:output_type -> obiente.cloud.vps.v1.SetUserPasswordResponse
	16, // 31: obiente.cloud.vps.v1.VPSConfigService.UpdateUserSSHKeys:output_type -> obiente.cloud.vps.v1.UpdateUserSSHKeysResponse
	18, // 32: obiente.cloud.vps.v1.VPSConfigService.RotateTerminalKey:output_type -> obiente.cloud.vps.v1.RotateTerminalKeyResponse
	20, // 33: obiente.cloud.vps.v1.VPSConfigService.RemoveTerminalKey:output_type -> obiente.cloud.vps.v1.RemoveTerminalKeyResponse
	22, // 34: obiente.cloud.vps.v1.VPSConfigService.GetTerminalKey:output_type -> obiente.cloud.vps.v1.GetTerminalKeyResponse
	24, // 35: obiente.cloud.vps.v1.VPSConfigService.RotateBastionKey:output_type -> obiente.cloud.vps.v1.RotateBastionKeyResponse
	26, // 36: obiente.cloud.vps.v1.VPSConfigService.GetBastionKey:output_type -> obiente.cloud.vps.v1.GetBastionKeyResponse
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_obiente_cloud_vps_v1_vps_config_service_proto_init() }
func file_obiente_cloud_vps_v1_vps_config_service_proto_init() {
	if File_obiente_cloud_vps_v1_vps_config_service_proto != nil {
		return
	}
	file_obiente_cloud_vps_v1_vps_service_proto_init()
	file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obiente_cloud_vps_v1_vps_config_service_proto_rawDesc), len(file_obiente_cloud_vps_v1_vps_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_obiente_cloud_vps_v1_vps_config_service_proto_goTypes,
		DependencyIndexes: file_obiente_cloud_vps_v1_vps_config_service_proto_depIdxs,
		MessageInfos:      file_obiente_cloud_vps_v1_vps_config_service_proto_msgTypes,
	}.Build()
	File_obiente_cloud_vps_v1_vps_config_service_proto = out.File
	file_obiente_cloud_vps_v1_vps_config_service_proto_goTypes = nil
	file_obiente_cloud_vps_v1_vps_config_service_proto_depIdxs = nil
}
