// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: obiente/cloud/notifications/v1/notification_service.proto

package notificationsv1

import (
	v1 "github.com/obiente/cloud/apps/shared/proto/obiente/cloud/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_INFO        NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SUCCESS     NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_WARNING     NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_ERROR       NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_DEPLOYMENT  NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_BILLING     NotificationType = 6
	NotificationType_NOTIFICATION_TYPE_QUOTA       NotificationType = 7
	NotificationType_NOTIFICATION_TYPE_INVITE      NotificationType = 8
	NotificationType_NOTIFICATION_TYPE_SYSTEM      NotificationType = 9
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_INFO",
		2: "NOTIFICATION_TYPE_SUCCESS",
		3: "NOTIFICATION_TYPE_WARNING",
		4: "NOTIFICATION_TYPE_ERROR",
		5: "NOTIFICATION_TYPE_DEPLOYMENT",
		6: "NOTIFICATION_TYPE_BILLING",
		7: "NOTIFICATION_TYPE_QUOTA",
		8: "NOTIFICATION_TYPE_INVITE",
		9: "NOTIFICATION_TYPE_SYSTEM",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_INFO":        1,
		"NOTIFICATION_TYPE_SUCCESS":     2,
		"NOTIFICATION_TYPE_WARNING":     3,
		"NOTIFICATION_TYPE_ERROR":       4,
		"NOTIFICATION_TYPE_DEPLOYMENT":  5,
		"NOTIFICATION_TYPE_BILLING":     6,
		"NOTIFICATION_TYPE_QUOTA":       7,
		"NOTIFICATION_TYPE_INVITE":      8,
		"NOTIFICATION_TYPE_SYSTEM":      9,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{0}
}

type NotificationSeverity int32

const (
	NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED NotificationSeverity = 0
	NotificationSeverity_NOTIFICATION_SEVERITY_LOW         NotificationSeverity = 1
	NotificationSeverity_NOTIFICATION_SEVERITY_MEDIUM      NotificationSeverity = 2
	NotificationSeverity_NOTIFICATION_SEVERITY_HIGH        NotificationSeverity = 3
	NotificationSeverity_NOTIFICATION_SEVERITY_CRITICAL    NotificationSeverity = 4
)

// Enum value maps for NotificationSeverity.
var (
	NotificationSeverity_name = map[int32]string{
		0: "NOTIFICATION_SEVERITY_UNSPECIFIED",
		1: "NOTIFICATION_SEVERITY_LOW",
		2: "NOTIFICATION_SEVERITY_MEDIUM",
		3: "NOTIFICATION_SEVERITY_HIGH",
		4: "NOTIFICATION_SEVERITY_CRITICAL",
	}
	NotificationSeverity_value = map[string]int32{
		"NOTIFICATION_SEVERITY_UNSPECIFIED": 0,
		"NOTIFICATION_SEVERITY_LOW":         1,
		"NOTIFICATION_SEVERITY_MEDIUM":      2,
		"NOTIFICATION_SEVERITY_HIGH":        3,
		"NOTIFICATION_SEVERITY_CRITICAL":    4,
	}
)

func (x NotificationSeverity) Enum() *NotificationSeverity {
	p := new(NotificationSeverity)
	*p = x
	return p
}

func (x NotificationSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes[1].Descriptor()
}

func (NotificationSeverity) Type() protoreflect.EnumType {
	return &file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes[1]
}

func (x NotificationSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationSeverity.Descriptor instead.
func (NotificationSeverity) EnumDescriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{1}
}

type NotificationFrequency int32

const (
	NotificationFrequency_NOTIFICATION_FREQUENCY_UNSPECIFIED NotificationFrequency = 0
	NotificationFrequency_NOTIFICATION_FREQUENCY_IMMEDIATE   NotificationFrequency = 1
	NotificationFrequency_NOTIFICATION_FREQUENCY_DAILY       NotificationFrequency = 2
	NotificationFrequency_NOTIFICATION_FREQUENCY_WEEKLY      NotificationFrequency = 3
	NotificationFrequency_NOTIFICATION_FREQUENCY_NEVER       NotificationFrequency = 4
)

// Enum value maps for NotificationFrequency.
var (
	NotificationFrequency_name = map[int32]string{
		0: "NOTIFICATION_FREQUENCY_UNSPECIFIED",
		1: "NOTIFICATION_FREQUENCY_IMMEDIATE",
		2: "NOTIFICATION_FREQUENCY_DAILY",
		3: "NOTIFICATION_FREQUENCY_WEEKLY",
		4: "NOTIFICATION_FREQUENCY_NEVER",
	}
	NotificationFrequency_value = map[string]int32{
		"NOTIFICATION_FREQUENCY_UNSPECIFIED": 0,
		"NOTIFICATION_FREQUENCY_IMMEDIATE":   1,
		"NOTIFICATION_FREQUENCY_DAILY":       2,
		"NOTIFICATION_FREQUENCY_WEEKLY":      3,
		"NOTIFICATION_FREQUENCY_NEVER":       4,
	}
)

func (x NotificationFrequency) Enum() *NotificationFrequency {
	p := new(NotificationFrequency)
	*p = x
	return p
}

func (x NotificationFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes[2].Descriptor()
}

func (NotificationFrequency) Type() protoreflect.EnumType {
	return &file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes[2]
}

func (x NotificationFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationFrequency.Descriptor instead.
func (NotificationFrequency) EnumDescriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{2}
}

type ListNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	UnreadOnly *bool                 `protobuf:"varint,1,opt,name=unread_only,json=unreadOnly,proto3,oneof" json:"unread_only,omitempty"`
	Type       *NotificationType     `protobuf:"varint,2,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType,oneof" json:"type,omitempty"`
	Severity   *NotificationSeverity `protobuf:"varint,3,opt,name=severity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity,oneof" json:"severity,omitempty"`
	// Pagination
	Page          int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32 `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil && x.UnreadOnly != nil {
		return *x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetType() NotificationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetSeverity() NotificationSeverity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type MarkAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{4}
}

func (x *MarkAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAsReadResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type MarkAllAsReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	Type          *NotificationType     `protobuf:"varint,1,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType,oneof" json:"type,omitempty"`
	Severity      *NotificationSeverity `protobuf:"varint,2,opt,name=severity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity,oneof" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{6}
}

func (x *MarkAllAsReadRequest) GetType() NotificationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *MarkAllAsReadRequest) GetSeverity() NotificationSeverity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

type MarkAllAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarkedCount   int32                  `protobuf:"varint,1,opt,name=marked_count,json=markedCount,proto3" json:"marked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadResponse) Reset() {
	*x = MarkAllAsReadResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadResponse) ProtoMessage() {}

func (x *MarkAllAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAllAsReadResponse) GetMarkedCount() int32 {
	if x != nil {
		return x.MarkedCount
	}
	return 0
}

type DeleteNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type DeleteNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationResponse) Reset() {
	*x = DeleteNotificationResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationResponse) ProtoMessage() {}

func (x *DeleteNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteAllNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	ReadOnly      *bool             `protobuf:"varint,1,opt,name=read_only,json=readOnly,proto3,oneof" json:"read_only,omitempty"`
	Type          *NotificationType `protobuf:"varint,2,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllNotificationsRequest) Reset() {
	*x = DeleteAllNotificationsRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllNotificationsRequest) ProtoMessage() {}

func (x *DeleteAllNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllNotificationsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAllNotificationsRequest) GetReadOnly() bool {
	if x != nil && x.ReadOnly != nil {
		return *x.ReadOnly
	}
	return false
}

func (x *DeleteAllNotificationsRequest) GetType() NotificationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

type DeleteAllNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllNotificationsResponse) Reset() {
	*x = DeleteAllNotificationsResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllNotificationsResponse) ProtoMessage() {}

func (x *DeleteAllNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllNotificationsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAllNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAllNotificationsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type GetUnreadCountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	Type          *NotificationType     `protobuf:"varint,1,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType,oneof" json:"type,omitempty"`
	MinSeverity   *NotificationSeverity `protobuf:"varint,2,opt,name=min_severity,json=minSeverity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity,oneof" json:"min_severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetUnreadCountRequest) GetType() NotificationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *GetUnreadCountRequest) GetMinSeverity() NotificationSeverity {
	if x != nil && x.MinSeverity != nil {
		return *x.MinSeverity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId *string                `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	Type           NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType" json:"type,omitempty"`
	Severity       NotificationSeverity   `protobuf:"varint,4,opt,name=severity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity" json:"severity,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ActionUrl      *string                `protobuf:"bytes,7,opt,name=action_url,json=actionUrl,proto3,oneof" json:"action_url,omitempty"`
	ActionLabel    *string                `protobuf:"bytes,8,opt,name=action_label,json=actionLabel,proto3,oneof" json:"action_label,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNotificationRequest) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *CreateNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *CreateNotificationRequest) GetSeverity() NotificationSeverity {
	if x != nil {
		return x.Severity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

func (x *CreateNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNotificationRequest) GetActionUrl() string {
	if x != nil && x.ActionUrl != nil {
		return *x.ActionUrl
	}
	return ""
}

func (x *CreateNotificationRequest) GetActionLabel() string {
	if x != nil && x.ActionLabel != nil {
		return *x.ActionLabel
	}
	return ""
}

func (x *CreateNotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type CreateOrganizationNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Type           NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType" json:"type,omitempty"`
	Severity       NotificationSeverity   `protobuf:"varint,3,opt,name=severity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity" json:"severity,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	ActionUrl      *string                `protobuf:"bytes,6,opt,name=action_url,json=actionUrl,proto3,oneof" json:"action_url,omitempty"`
	ActionLabel    *string                `protobuf:"bytes,7,opt,name=action_label,json=actionLabel,proto3,oneof" json:"action_label,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional: only notify specific roles (empty = all members)
	Roles         []string `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationNotificationRequest) Reset() {
	*x = CreateOrganizationNotificationRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationNotificationRequest) ProtoMessage() {}

func (x *CreateOrganizationNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationNotificationRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateOrganizationNotificationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateOrganizationNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *CreateOrganizationNotificationRequest) GetSeverity() NotificationSeverity {
	if x != nil {
		return x.Severity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

func (x *CreateOrganizationNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateOrganizationNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOrganizationNotificationRequest) GetActionUrl() string {
	if x != nil && x.ActionUrl != nil {
		return *x.ActionUrl
	}
	return ""
}

func (x *CreateOrganizationNotificationRequest) GetActionLabel() string {
	if x != nil && x.ActionLabel != nil {
		return *x.ActionLabel
	}
	return ""
}

func (x *CreateOrganizationNotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateOrganizationNotificationRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateOrganizationNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedCount  int32                  `protobuf:"varint,1,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	Notifications []*Notification        `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationNotificationResponse) Reset() {
	*x = CreateOrganizationNotificationResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationNotificationResponse) ProtoMessage() {}

func (x *CreateOrganizationNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationNotificationResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateOrganizationNotificationResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

func (x *CreateOrganizationNotificationResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId *string                `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	Type           NotificationType       `protobuf:"varint,4,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType" json:"type,omitempty"`
	Severity       NotificationSeverity   `protobuf:"varint,5,opt,name=severity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity" json:"severity,omitempty"`
	Title          string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Read           bool                   `protobuf:"varint,8,opt,name=read,proto3" json:"read,omitempty"`
	ReadAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=read_at,json=readAt,proto3,oneof" json:"read_at,omitempty"`
	ActionUrl      *string                `protobuf:"bytes,10,opt,name=action_url,json=actionUrl,proto3,oneof" json:"action_url,omitempty"`
	ActionLabel    *string                `protobuf:"bytes,11,opt,name=action_label,json=actionLabel,proto3,oneof" json:"action_label,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientOnly     bool                   `protobuf:"varint,13,opt,name=client_only,json=clientOnly,proto3" json:"client_only,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{18}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetSeverity() NotificationSeverity {
	if x != nil {
		return x.Severity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *Notification) GetActionUrl() string {
	if x != nil && x.ActionUrl != nil {
		return *x.ActionUrl
	}
	return ""
}

func (x *Notification) GetActionLabel() string {
	if x != nil && x.ActionLabel != nil {
		return *x.ActionLabel
	}
	return ""
}

func (x *Notification) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Notification) GetClientOnly() bool {
	if x != nil {
		return x.ClientOnly
	}
	return false
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetNotificationTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationTypesRequest) Reset() {
	*x = GetNotificationTypesRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationTypesRequest) ProtoMessage() {}

func (x *GetNotificationTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationTypesRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationTypesRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{19}
}

type GetNotificationTypesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Types         []*NotificationTypeInfo `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationTypesResponse) Reset() {
	*x = GetNotificationTypesResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationTypesResponse) ProtoMessage() {}

func (x *GetNotificationTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationTypesResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationTypesResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetNotificationTypesResponse) GetTypes() []*NotificationTypeInfo {
	if x != nil {
		return x.Types
	}
	return nil
}

type NotificationTypeInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                NotificationType       `protobuf:"varint,1,opt,name=type,proto3,enum=obiente.cloud.notifications.v1.NotificationType" json:"type,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultEmailEnabled bool                   `protobuf:"varint,4,opt,name=default_email_enabled,json=defaultEmailEnabled,proto3" json:"default_email_enabled,omitempty"`
	DefaultInAppEnabled bool                   `protobuf:"varint,5,opt,name=default_in_app_enabled,json=defaultInAppEnabled,proto3" json:"default_in_app_enabled,omitempty"`
	DefaultMinSeverity  NotificationSeverity   `protobuf:"varint,6,opt,name=default_min_severity,json=defaultMinSeverity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity" json:"default_min_severity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NotificationTypeInfo) Reset() {
	*x = NotificationTypeInfo{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTypeInfo) ProtoMessage() {}

func (x *NotificationTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTypeInfo.ProtoReflect.Descriptor instead.
func (*NotificationTypeInfo) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{21}
}

func (x *NotificationTypeInfo) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotificationTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NotificationTypeInfo) GetDefaultEmailEnabled() bool {
	if x != nil {
		return x.DefaultEmailEnabled
	}
	return false
}

func (x *NotificationTypeInfo) GetDefaultInAppEnabled() bool {
	if x != nil {
		return x.DefaultInAppEnabled
	}
	return false
}

func (x *NotificationTypeInfo) GetDefaultMinSeverity() NotificationSeverity {
	if x != nil {
		return x.DefaultMinSeverity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

type GetNotificationPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationPreferencesRequest) Reset() {
	*x = GetNotificationPreferencesRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationPreferencesRequest) ProtoMessage() {}

func (x *GetNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{22}
}

type GetNotificationPreferencesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Preferences   []*NotificationPreference `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationPreferencesResponse) Reset() {
	*x = GetNotificationPreferencesResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationPreferencesResponse) ProtoMessage() {}

func (x *GetNotificationPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetNotificationPreferencesResponse) GetPreferences() []*NotificationPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdateNotificationPreferencesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Preferences   []*NotificationPreference `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationPreferencesRequest) Reset() {
	*x = UpdateNotificationPreferencesRequest{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationPreferencesRequest) ProtoMessage() {}

func (x *UpdateNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateNotificationPreferencesRequest) GetPreferences() []*NotificationPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdateNotificationPreferencesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Preferences   []*NotificationPreference `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationPreferencesResponse) Reset() {
	*x = UpdateNotificationPreferencesResponse{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationPreferencesResponse) ProtoMessage() {}

func (x *UpdateNotificationPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateNotificationPreferencesResponse) GetPreferences() []*NotificationPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type NotificationPreference struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationType NotificationType       `protobuf:"varint,1,opt,name=notification_type,json=notificationType,proto3,enum=obiente.cloud.notifications.v1.NotificationType" json:"notification_type,omitempty"`
	EmailEnabled     bool                   `protobuf:"varint,2,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	InAppEnabled     bool                   `protobuf:"varint,3,opt,name=in_app_enabled,json=inAppEnabled,proto3" json:"in_app_enabled,omitempty"`
	Frequency        NotificationFrequency  `protobuf:"varint,4,opt,name=frequency,proto3,enum=obiente.cloud.notifications.v1.NotificationFrequency" json:"frequency,omitempty"`
	MinSeverity      NotificationSeverity   `protobuf:"varint,5,opt,name=min_severity,json=minSeverity,proto3,enum=obiente.cloud.notifications.v1.NotificationSeverity" json:"min_severity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationPreference) Reset() {
	*x = NotificationPreference{}
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreference) ProtoMessage() {}

func (x *NotificationPreference) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreference.ProtoReflect.Descriptor instead.
func (*NotificationPreference) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP(), []int{26}
}

func (x *NotificationPreference) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationPreference) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *NotificationPreference) GetInAppEnabled() bool {
	if x != nil {
		return x.InAppEnabled
	}
	return false
}

func (x *NotificationPreference) GetFrequency() NotificationFrequency {
	if x != nil {
		return x.Frequency
	}
	return NotificationFrequency_NOTIFICATION_FREQUENCY_UNSPECIFIED
}

func (x *NotificationPreference) GetMinSeverity() NotificationSeverity {
	if x != nil {
		return x.MinSeverity
	}
	return NotificationSeverity_NOTIFICATION_SEVERITY_UNSPECIFIED
}

var File_obiente_cloud_notifications_v1_notification_service_proto protoreflect.FileDescriptor

const file_obiente_cloud_notifications_v1_notification_service_proto_rawDesc = "" +
	"\n" +
	"9obiente/cloud/notifications/v1/notification_service.proto\x12\x1eobiente.cloud.notifications.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$obiente/cloud/common/v1/common.proto\"\xb7\x02\n" +
	"\x18ListNotificationsRequest\x12$\n" +
	"\vunread_only\x18\x01 \x01(\bH\x00R\n" +
	"unreadOnly\x88\x01\x01\x12I\n" +
	"\x04type\x18\x02 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeH\x01R\x04type\x88\x01\x01\x12U\n" +
	"\bseverity\x18\x03 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityH\x02R\bseverity\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x05 \x01(\x05R\aperPageB\x0e\n" +
	"\f_unread_onlyB\a\n" +
	"\x05_typeB\v\n" +
	"\t_severity\"\xb4\x01\n" +
	"\x19ListNotificationsResponse\x12R\n" +
	"\rnotifications\x18\x01 \x03(\v2,.obiente.cloud.notifications.v1.NotificationR\rnotifications\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.obiente.cloud.common.v1.PaginationR\n" +
	"pagination\"A\n" +
	"\x16GetNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"k\n" +
	"\x17GetNotificationResponse\x12P\n" +
	"\fnotification\x18\x01 \x01(\v2,.obiente.cloud.notifications.v1.NotificationR\fnotification\"<\n" +
	"\x11MarkAsReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"f\n" +
	"\x12MarkAsReadResponse\x12P\n" +
	"\fnotification\x18\x01 \x01(\v2,.obiente.cloud.notifications.v1.NotificationR\fnotification\"\xce\x01\n" +
	"\x14MarkAllAsReadRequest\x12I\n" +
	"\x04type\x18\x01 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeH\x00R\x04type\x88\x01\x01\x12U\n" +
	"\bseverity\x18\x02 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityH\x01R\bseverity\x88\x01\x01B\a\n" +
	"\x05_typeB\v\n" +
	"\t_severity\":\n" +
	"\x15MarkAllAsReadResponse\x12!\n" +
	"\fmarked_count\x18\x01 \x01(\x05R\vmarkedCount\"D\n" +
	"\x19DeleteNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"6\n" +
	"\x1aDeleteNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa3\x01\n" +
	"\x1dDeleteAllNotificationsRequest\x12 \n" +
	"\tread_only\x18\x01 \x01(\bH\x00R\breadOnly\x88\x01\x01\x12I\n" +
	"\x04type\x18\x02 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeH\x01R\x04type\x88\x01\x01B\f\n" +
	"\n" +
	"_read_onlyB\a\n" +
	"\x05_type\"E\n" +
	"\x1eDeleteAllNotificationsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"\xda\x01\n" +
	"\x15GetUnreadCountRequest\x12I\n" +
	"\x04type\x18\x01 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeH\x00R\x04type\x88\x01\x01\x12\\\n" +
	"\fmin_severity\x18\x02 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityH\x01R\vminSeverity\x88\x01\x01B\a\n" +
	"\x05_typeB\x0f\n" +
	"\r_min_severity\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\xcc\x04\n" +
	"\x19CreateNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x0forganization_id\x18\x02 \x01(\tH\x00R\x0eorganizationId\x88\x01\x01\x12D\n" +
	"\x04type\x18\x03 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeR\x04type\x12P\n" +
	"\bseverity\x18\x04 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\"\n" +
	"\n" +
	"action_url\x18\a \x01(\tH\x01R\tactionUrl\x88\x01\x01\x12&\n" +
	"\faction_label\x18\b \x01(\tH\x02R\vactionLabel\x88\x01\x01\x12c\n" +
	"\bmetadata\x18\t \x03(\v2G.obiente.cloud.notifications.v1.CreateNotificationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_organization_idB\r\n" +
	"\v_action_urlB\x0f\n" +
	"\r_action_label\"n\n" +
	"\x1aCreateNotificationResponse\x12P\n" +
	"\fnotification\x18\x01 \x01(\v2,.obiente.cloud.notifications.v1.NotificationR\fnotification\"\xc8\x04\n" +
	"%CreateOrganizationNotificationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12D\n" +
	"\x04type\x18\x02 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeR\x04type\x12P\n" +
	"\bseverity\x18\x03 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\"\n" +
	"\n" +
	"action_url\x18\x06 \x01(\tH\x00R\tactionUrl\x88\x01\x01\x12&\n" +
	"\faction_label\x18\a \x01(\tH\x01R\vactionLabel\x88\x01\x01\x12o\n" +
	"\bmetadata\x18\b \x03(\v2S.obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05roles\x18\t \x03(\tR\x05roles\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_action_urlB\x0f\n" +
	"\r_action_label\"\xa1\x01\n" +
	"&CreateOrganizationNotificationResponse\x12#\n" +
	"\rcreated_count\x18\x01 \x01(\x05R\fcreatedCount\x12R\n" +
	"\rnotifications\x18\x02 \x03(\v2,.obiente.cloud.notifications.v1.NotificationR\rnotifications\"\xb3\x06\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x0forganization_id\x18\x03 \x01(\tH\x00R\x0eorganizationId\x88\x01\x01\x12D\n" +
	"\x04type\x18\x04 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeR\x04type\x12P\n" +
	"\bseverity\x18\x05 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x12\n" +
	"\x04read\x18\b \x01(\bR\x04read\x128\n" +
	"\aread_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06readAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"action_url\x18\n" +
	" \x01(\tH\x02R\tactionUrl\x88\x01\x01\x12&\n" +
	"\faction_label\x18\v \x01(\tH\x03R\vactionLabel\x88\x01\x01\x12V\n" +
	"\bmetadata\x18\f \x03(\v2:.obiente.cloud.notifications.v1.Notification.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vclient_only\x18\r \x01(\bR\n" +
	"clientOnly\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_organization_idB\n" +
	"\n" +
	"\b_read_atB\r\n" +
	"\v_action_urlB\x0f\n" +
	"\r_action_label\"\x1d\n" +
	"\x1bGetNotificationTypesRequest\"j\n" +
	"\x1cGetNotificationTypesResponse\x12J\n" +
	"\x05types\x18\x01 \x03(\v24.obiente.cloud.notifications.v1.NotificationTypeInfoR\x05types\"\xe3\x02\n" +
	"\x14NotificationTypeInfo\x12D\n" +
	"\x04type\x18\x01 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x15default_email_enabled\x18\x04 \x01(\bR\x13defaultEmailEnabled\x123\n" +
	"\x16default_in_app_enabled\x18\x05 \x01(\bR\x13defaultInAppEnabled\x12f\n" +
	"\x14default_min_severity\x18\x06 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityR\x12defaultMinSeverity\"#\n" +
	"!GetNotificationPreferencesRequest\"~\n" +
	"\"GetNotificationPreferencesResponse\x12X\n" +
	"\vpreferences\x18\x01 \x03(\v26.obiente.cloud.notifications.v1.NotificationPreferenceR\vpreferences\"\x80\x01\n" +
	"$UpdateNotificationPreferencesRequest\x12X\n" +
	"\vpreferences\x18\x01 \x03(\v26.obiente.cloud.notifications.v1.NotificationPreferenceR\vpreferences\"\x81\x01\n" +
	"%UpdateNotificationPreferencesResponse\x12X\n" +
	"\vpreferences\x18\x01 \x03(\v26.obiente.cloud.notifications.v1.NotificationPreferenceR\vpreferences\"\xf0\x02\n" +
	"\x16NotificationPreference\x12]\n" +
	"\x11notification_type\x18\x01 \x01(\x0e20.obiente.cloud.notifications.v1.NotificationTypeR\x10notificationType\x12#\n" +
	"\remail_enabled\x18\x02 \x01(\bR\femailEnabled\x12$\n" +
	"\x0ein_app_enabled\x18\x03 \x01(\bR\finAppEnabled\x12S\n" +
	"\tfrequency\x18\x04 \x01(\x0e25.obiente.cloud.notifications.v1.NotificationFrequencyR\tfrequency\x12W\n" +
	"\fmin_severity\x18\x05 \x01(\x0e24.obiente.cloud.notifications.v1.NotificationSeverityR\vminSeverity*\xc6\x02\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_INFO\x10\x01\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_WARNING\x10\x03\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_ERROR\x10\x04\x12 \n" +
	"\x1cNOTIFICATION_TYPE_DEPLOYMENT\x10\x05\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_BILLING\x10\x06\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_QUOTA\x10\a\x12\x1c\n" +
	"\x18NOTIFICATION_TYPE_INVITE\x10\b\x12\x1c\n" +
	"\x18NOTIFICATION_TYPE_SYSTEM\x10\t*\xc2\x01\n" +
	"\x14NotificationSeverity\x12%\n" +
	"!NOTIFICATION_SEVERITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NOTIFICATION_SEVERITY_LOW\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_SEVERITY_MEDIUM\x10\x02\x12\x1e\n" +
	"\x1aNOTIFICATION_SEVERITY_HIGH\x10\x03\x12\"\n" +
	"\x1eNOTIFICATION_SEVERITY_CRITICAL\x10\x04*\xcc\x01\n" +
	"\x15NotificationFrequency\x12&\n" +
	"\"NOTIFICATION_FREQUENCY_UNSPECIFIED\x10\x00\x12$\n" +
	" NOTIFICATION_FREQUENCY_IMMEDIATE\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_FREQUENCY_DAILY\x10\x02\x12!\n" +
	"\x1dNOTIFICATION_FREQUENCY_WEEKLY\x10\x03\x12 \n" +
	"\x1cNOTIFICATION_FREQUENCY_NEVER\x10\x042\xea\r\n" +
	"\x13NotificationService\x12\x88\x01\n" +
	"\x11ListNotifications\x128.obiente.cloud.notifications.v1.ListNotificationsRequest\x1a9.obiente.cloud.notifications.v1.ListNotificationsResponse\x12\x82\x01\n" +
	"\x0fGetNotification\x126.obiente.cloud.notifications.v1.GetNotificationRequest\x1a7.obiente.cloud.notifications.v1.GetNotificationResponse\x12s\n" +
	"\n" +
	"MarkAsRead\x121.obiente.cloud.notifications.v1.MarkAsReadRequest\x1a2.obiente.cloud.notifications.v1.MarkAsReadResponse\x12|\n" +
	"\rMarkAllAsRead\x124.obiente.cloud.notifications.v1.MarkAllAsReadRequest\x1a5.obiente.cloud.notifications.v1.MarkAllAsReadResponse\x12\x8b\x01\n" +
	"\x12DeleteNotification\x129.obiente.cloud.notifications.v1.DeleteNotificationRequest\x1a:.obiente.cloud.notifications.v1.DeleteNotificationResponse\x12\x97\x01\n" +
	"\x16DeleteAllNotifications\x12=.obiente.cloud.notifications.v1.DeleteAllNotificationsRequest\x1a>.obiente.cloud.notifications.v1.DeleteAllNotificationsResponse\x12\x7f\n" +
	"\x0eGetUnreadCount\x125.obiente.cloud.notifications.v1.GetUnreadCountRequest\x1a6.obiente.cloud.notifications.v1.GetUnreadCountResponse\x12\x8b\x01\n" +
	"\x12CreateNotification\x129.obiente.cloud.notifications.v1.CreateNotificationRequest\x1a:.obiente.cloud.notifications.v1.CreateNotificationResponse\x12\xaf\x01\n" +
	"\x1eCreateOrganizationNotification\x12E.obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest\x1aF.obiente.cloud.notifications.v1.CreateOrganizationNotificationResponse\x12\x91\x01\n" +
	"\x14GetNotificationTypes\x12;.obiente.cloud.notifications.v1.GetNotificationTypesRequest\x1a<.obiente.cloud.notifications.v1.GetNotificationTypesResponse\x12\xa3\x01\n" +
	"\x1aGetNotificationPreferences\x12A.obiente.cloud.notifications.v1.GetNotificationPreferencesRequest\x1aB.obiente.cloud.notifications.v1.GetNotificationPreferencesResponse\x12\xac\x01\n" +
	"\x1dUpdateNotificationPreferences\x12D.obiente.cloud.notifications.v1.UpdateNotificationPreferencesRequest\x1aE.obiente.cloud.notifications.v1.UpdateNotificationPreferencesResponseB[ZYgithub.com/obiente/cloud/apps/shared/proto/obiente/cloud/notifications/v1;notificationsv1b\x06proto3"

var (
	file_obiente_cloud_notifications_v1_notification_service_proto_rawDescOnce sync.Once
	file_obiente_cloud_notifications_v1_notification_service_proto_rawDescData []byte
)

func file_obiente_cloud_notifications_v1_notification_service_proto_rawDescGZIP() []byte {
	file_obiente_cloud_notifications_v1_notification_service_proto_rawDescOnce.Do(func() {
		file_obiente_cloud_notifications_v1_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_obiente_cloud_notifications_v1_notification_service_proto_rawDesc), len(file_obiente_cloud_notifications_v1_notification_service_proto_rawDesc)))
	})
	return file_obiente_cloud_notifications_v1_notification_service_proto_rawDescData
}

var file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_obiente_cloud_notifications_v1_notification_service_proto_goTypes = []any{
	(NotificationType)(0),                          // 0: obiente.cloud.notifications.v1.NotificationType
	(NotificationSeverity)(0),                      // 1: obiente.cloud.notifications.v1.NotificationSeverity
	(NotificationFrequency)(0),                     // 2: obiente.cloud.notifications.v1.NotificationFrequency
	(*ListNotificationsRequest)(nil),               // 3: obiente.cloud.notifications.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),              // 4: obiente.cloud.notifications.v1.ListNotificationsResponse
	(*GetNotificationRequest)(nil),                 // 5: obiente.cloud.notifications.v1.GetNotificationRequest
	(*GetNotificationResponse)(nil),                // 6: obiente.cloud.notifications.v1.GetNotificationResponse
	(*MarkAsReadRequest)(nil),                      // 7: obiente.cloud.notifications.v1.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),                     // 8: obiente.cloud.notifications.v1.MarkAsReadResponse
	(*MarkAllAsReadRequest)(nil),                   // 9: obiente.cloud.notifications.v1.MarkAllAsReadRequest
	(*MarkAllAsReadResponse)(nil),                  // 10: obiente.cloud.notifications.v1.MarkAllAsReadResponse
	(*DeleteNotificationRequest)(nil),              // 11: obiente.cloud.notifications.v1.DeleteNotificationRequest
	(*DeleteNotificationResponse)(nil),             // 12: obiente.cloud.notifications.v1.DeleteNotificationResponse
	(*DeleteAllNotificationsRequest)(nil),          // 13: obiente.cloud.notifications.v1.DeleteAllNotificationsRequest
	(*DeleteAllNotificationsResponse)(nil),         // 14: obiente.cloud.notifications.v1.DeleteAllNotificationsResponse
	(*GetUnreadCountRequest)(nil),                  // 15: obiente.cloud.notifications.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),                 // 16: obiente.cloud.notifications.v1.GetUnreadCountResponse
	(*CreateNotificationRequest)(nil),              // 17: obiente.cloud.notifications.v1.CreateNotificationRequest
	(*CreateNotificationResponse)(nil),             // 18: obiente.cloud.notifications.v1.CreateNotificationResponse
	(*CreateOrganizationNotificationRequest)(nil),  // 19: obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest
	(*CreateOrganizationNotificationResponse)(nil), // 20: obiente.cloud.notifications.v1.CreateOrganizationNotificationResponse
	(*Notification)(nil),                           // 21: obiente.cloud.notifications.v1.Notification
	(*GetNotificationTypesRequest)(nil),            // 22: obiente.cloud.notifications.v1.GetNotificationTypesRequest
	(*GetNotificationTypesResponse)(nil),           // 23: obiente.cloud.notifications.v1.GetNotificationTypesResponse
	(*NotificationTypeInfo)(nil),                   // 24: obiente.cloud.notifications.v1.NotificationTypeInfo
	(*GetNotificationPreferencesRequest)(nil),      // 25: obiente.cloud.notifications.v1.GetNotificationPreferencesRequest
	(*GetNotificationPreferencesResponse)(nil),     // 26: obiente.cloud.notifications.v1.GetNotificationPreferencesResponse
	(*UpdateNotificationPreferencesRequest)(nil),   // 27: obiente.cloud.notifications.v1.UpdateNotificationPreferencesRequest
	(*UpdateNotificationPreferencesResponse)(nil),  // 28: obiente.cloud.notifications.v1.UpdateNotificationPreferencesResponse
	(*NotificationPreference)(nil),                 // 29: obiente.cloud.notifications.v1.NotificationPreference
	nil,                                            // 30: obiente.cloud.notifications.v1.CreateNotificationRequest.MetadataEntry
	nil,                                            // 31: obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest.MetadataEntry
	nil,                                            // 32: obiente.cloud.notifications.v1.Notification.MetadataEntry
	(*v1.Pagination)(nil),                          // 33: obiente.cloud.common.v1.Pagination
	(*timestamppb.Timestamp)(nil),                  // 34: google.protobuf.Timestamp
}
var file_obiente_cloud_notifications_v1_notification_service_proto_depIdxs = []int32{
	0,  // 0: obiente.cloud.notifications.v1.ListNotificationsRequest.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	1,  // 1: obiente.cloud.notifications.v1.ListNotificationsRequest.severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	21, // 2: obiente.cloud.notifications.v1.ListNotificationsResponse.notifications:type_name -> obiente.cloud.notifications.v1.Notification
	33, // 3: obiente.cloud.notifications.v1.ListNotificationsResponse.pagination:type_name -> obiente.cloud.common.v1.Pagination
	21, // 4: obiente.cloud.notifications.v1.GetNotificationResponse.notification:type_name -> obiente.cloud.notifications.v1.Notification
	21, // 5: obiente.cloud.notifications.v1.MarkAsReadResponse.notification:type_name -> obiente.cloud.notifications.v1.Notification
	0,  // 6: obiente.cloud.notifications.v1.MarkAllAsReadRequest.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	1,  // 7: obiente.cloud.notifications.v1.MarkAllAsReadRequest.severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	0,  // 8: obiente.cloud.notifications.v1.DeleteAllNotificationsRequest.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	0,  // 9: obiente.cloud.notifications.v1.GetUnreadCountRequest.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	1,  // 10: obiente.cloud.notifications.v1.GetUnreadCountRequest.min_severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	0,  // 11: obiente.cloud.notifications.v1.CreateNotificationRequest.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	1,  // 12: obiente.cloud.notifications.v1.CreateNotificationRequest.severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	30, // 13: obiente.cloud.notifications.v1.CreateNotificationRequest.metadata:type_name -> obiente.cloud.notifications.v1.CreateNotificationRequest.MetadataEntry
	21, // 14: obiente.cloud.notifications.v1.CreateNotificationResponse.notification:type_name -> obiente.cloud.notifications.v1.Notification
	0,  // 15: obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	1,  // 16: obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest.severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	31, // 17: obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest.metadata:type_name -> obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest.MetadataEntry
	21, // 18: obiente.cloud.notifications.v1.CreateOrganizationNotificationResponse.notifications:type_name -> obiente.cloud.notifications.v1.Notification
	0,  // 19: obiente.cloud.notifications.v1.Notification.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	1,  // 20: obiente.cloud.notifications.v1.Notification.severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	34, // 21: obiente.cloud.notifications.v1.Notification.read_at:type_name -> google.protobuf.Timestamp
	32, // 22: obiente.cloud.notifications.v1.Notification.metadata:type_name -> obiente.cloud.notifications.v1.Notification.MetadataEntry
	34, // 23: obiente.cloud.notifications.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	34, // 24: obiente.cloud.notifications.v1.Notification.updated_at:type_name -> google.protobuf.Timestamp
	24, // 25: obiente.cloud.notifications.v1.GetNotificationTypesResponse.types:type_name -> obiente.cloud.notifications.v1.NotificationTypeInfo
	0,  // 26: obiente.cloud.notifications.v1.NotificationTypeInfo.type:type_name -> obiente.cloud.notifications.v1.NotificationType
	1,  // 27: obiente.cloud.notifications.v1.NotificationTypeInfo.default_min_severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	29, // 28: obiente.cloud.notifications.v1.GetNotificationPreferencesResponse.preferences:type_name -> obiente.cloud.notifications.v1.NotificationPreference
	29, // 29: obiente.cloud.notifications.v1.UpdateNotificationPreferencesRequest.preferences:type_name -> obiente.cloud.notifications.v1.NotificationPreference
	29, // 30: obiente.cloud.notifications.v1.UpdateNotificationPreferencesResponse.preferences:type_name -> obiente.cloud.notifications.v1.NotificationPreference
	0,  // 31: obiente.cloud.notifications.v1.NotificationPreference.notification_type:type_name -> obiente.cloud.notifications.v1.NotificationType
	2,  // 32: obiente.cloud.notifications.v1.NotificationPreference.frequency:type_name -> obiente.cloud.notifications.v1.NotificationFrequency
	1,  // 33: obiente.cloud.notifications.v1.NotificationPreference.min_severity:type_name -> obiente.cloud.notifications.v1.NotificationSeverity
	3,  // 34: obiente.cloud.notifications.v1.NotificationService.ListNotifications:input_type -> obiente.cloud.notifications.v1.ListNotificationsRequest
	5,  // 35: obiente.cloud.notifications.v1.NotificationService.GetNotification:input_type -> obiente.cloud.notifications.v1.GetNotificationRequest
	7,  // 36: obiente.cloud.notifications.v1.NotificationService.MarkAsRead:input_type -> obiente.cloud.notifications.v1.MarkAsReadRequest
	9,  // 37: obiente.cloud.notifications.v1.NotificationService.MarkAllAsRead:input_type -> obiente.cloud.notifications.v1.MarkAllAsReadRequest
	11, // 38: obiente.cloud.notifications.v1.NotificationService.DeleteNotification:input_type -> obiente.cloud.notifications.v1.DeleteNotificationRequest
	13, // 39: obiente.cloud.notifications.v1.NotificationService.DeleteAllNotifications:input_type -> obiente.cloud.notifications.v1.DeleteAllNotificationsRequest
	15, // 40: obiente.cloud.notifications.v1.NotificationService.GetUnreadCount:input_type -> obiente.cloud.notifications.v1.GetUnreadCountRequest
	17, // 41: obiente.cloud.notifications.v1.NotificationService.CreateNotification:input_type -> obiente.cloud.notifications.v1.CreateNotificationRequest
	19, // 42: obiente.cloud.notifications.v1.NotificationService.CreateOrganizationNotification:input_type -> obiente.cloud.notifications.v1.CreateOrganizationNotificationRequest
	22, // 43: obiente.cloud.notifications.v1.NotificationService.GetNotificationTypes:input_type -> obiente.cloud.notifications.v1.GetNotificationTypesRequest
	25, // 44: obiente.cloud.notifications.v1.NotificationService.GetNotificationPreferences:input_type -> obiente.cloud.notifications.v1.GetNotificationPreferencesRequest
	27, // 45: obiente.cloud.notifications.v1.NotificationService.UpdateNotificationPreferences:input_type -> obiente.cloud.notifications.v1.UpdateNotificationPreferencesRequest
	4,  // 46: obiente.cloud.notifications.v1.NotificationService.ListNotifications:output_type -> obiente.cloud.notifications.v1.ListNotificationsResponse
	6,  // 47: obiente.cloud.notifications.v1.NotificationService.GetNotification:output_type -> obiente.cloud.notifications.v1.GetNotificationResponse
	8,  // 48: obiente.cloud.notifications.v1.NotificationService.MarkAsRead:output_type -> obiente.cloud.notifications.v1.MarkAsReadResponse
	10, // 49: obiente.cloud.notifications.v1.NotificationService.MarkAllAsRead:output_type -> obiente.cloud.notifications.v1.MarkAllAsReadResponse
	12, // 50: obiente.cloud.notifications.v1.NotificationService.DeleteNotification:output_type -> obiente.cloud.notifications.v1.DeleteNotificationResponse
	14, // 51: obiente.cloud.notifications.v1.NotificationService.DeleteAllNotifications:output_type -> obiente.cloud.notifications.v1.DeleteAllNotificationsResponse
	16, // 52: obiente.cloud.notifications.v1.NotificationService.GetUnreadCount:output_type -> obiente.cloud.notifications.v1.GetUnreadCountResponse
	18, // 53: obiente.cloud.notifications.v1.NotificationService.CreateNotification:output_type -> obiente.cloud.notifications.v1.CreateNotificationResponse
	20, // 54: obiente.cloud.notifications.v1.NotificationService.CreateOrganizationNotification:output_type -> obiente.cloud.notifications.v1.CreateOrganizationNotificationResponse
	23, // 55: obiente.cloud.notifications.v1.NotificationService.GetNotificationTypes:output_type -> obiente.cloud.notifications.v1.GetNotificationTypesResponse
	26, // 56: obiente.cloud.notifications.v1.NotificationService.GetNotificationPreferences:output_type -> obiente.cloud.notifications.v1.GetNotificationPreferencesResponse
	28, // 57: obiente.cloud.notifications.v1.NotificationService.UpdateNotificationPreferences:output_type -> obiente.cloud.notifications.v1.UpdateNotificationPreferencesResponse
	46, // [46:58] is the sub-list for method output_type
	34, // [34:46] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_obiente_cloud_notifications_v1_notification_service_proto_init() }
func file_obiente_cloud_notifications_v1_notification_service_proto_init() {
	if File_obiente_cloud_notifications_v1_notification_service_proto != nil {
		return
	}
	file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[14].OneofWrappers = []any{}
	file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[16].OneofWrappers = []any{}
	file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obiente_cloud_notifications_v1_notification_service_proto_rawDesc), len(file_obiente_cloud_notifications_v1_notification_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_obiente_cloud_notifications_v1_notification_service_proto_goTypes,
		DependencyIndexes: file_obiente_cloud_notifications_v1_notification_service_proto_depIdxs,
		EnumInfos:         file_obiente_cloud_notifications_v1_notification_service_proto_enumTypes,
		MessageInfos:      file_obiente_cloud_notifications_v1_notification_service_proto_msgTypes,
	}.Build()
	File_obiente_cloud_notifications_v1_notification_service_proto = out.File
	file_obiente_cloud_notifications_v1_notification_service_proto_goTypes = nil
	file_obiente_cloud_notifications_v1_notification_service_proto_depIdxs = nil
}
