// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: obiente/cloud/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogLevel represents the severity/type of a log line
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_TRACE       LogLevel = 1 // Trace-level debugging
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 2 // Debug information
	LogLevel_LOG_LEVEL_INFO        LogLevel = 3 // Informational messages (default)
	LogLevel_LOG_LEVEL_WARN        LogLevel = 4 // Warning messages
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 5 // Error messages
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_TRACE",
		2: "LOG_LEVEL_DEBUG",
		3: "LOG_LEVEL_INFO",
		4: "LOG_LEVEL_WARN",
		5: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_TRACE":       1,
		"LOG_LEVEL_DEBUG":       2,
		"LOG_LEVEL_INFO":        3,
		"LOG_LEVEL_WARN":        4,
		"LOG_LEVEL_ERROR":       5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_obiente_cloud_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_obiente_cloud_common_v1_common_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// Pagination represents pagination information for list responses
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                               // Current page number (1-indexed)
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`          // Number of items per page
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                             // Total number of items
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // Total number of pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// VPSSize represents a VPS instance size configuration
// This is a shared type used across multiple services
type VPSSize struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                 // Size ID (e.g., "small", "medium", "cx11")
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                             // Human-readable name
	Description         *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`                                         // Optional description
	CpuCores            int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                                    // Number of CPU cores
	MemoryBytes         int64                  `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`                           // Memory in bytes
	DiskBytes           int64                  `protobuf:"varint,6,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`                                 // Disk space in bytes
	BandwidthBytesMonth int64                  `protobuf:"varint,7,opt,name=bandwidth_bytes_month,json=bandwidthBytesMonth,proto3" json:"bandwidth_bytes_month,omitempty"` // Monthly bandwidth limit (0 = unlimited)
	MinimumPaymentCents int64                  `protobuf:"varint,8,opt,name=minimum_payment_cents,json=minimumPaymentCents,proto3" json:"minimum_payment_cents,omitempty"` // Minimum payment in cents required to create this VPS size (0 = no requirement)
	Available           bool                   `protobuf:"varint,9,opt,name=available,proto3" json:"available,omitempty"`                                                  // Whether this size is available
	Region              string                 `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`                                                        // Region (empty = all regions)
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VPSSize) Reset() {
	*x = VPSSize{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPSSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPSSize) ProtoMessage() {}

func (x *VPSSize) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPSSize.ProtoReflect.Descriptor instead.
func (*VPSSize) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *VPSSize) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VPSSize) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VPSSize) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *VPSSize) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *VPSSize) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VPSSize) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *VPSSize) GetBandwidthBytesMonth() int64 {
	if x != nil {
		return x.BandwidthBytesMonth
	}
	return 0
}

func (x *VPSSize) GetMinimumPaymentCents() int64 {
	if x != nil {
		return x.MinimumPaymentCents
	}
	return 0
}

func (x *VPSSize) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *VPSSize) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *VPSSize) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VPSSize) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ExtractServerFileRequest is a shared request message for extracting zip files
// Resource-specific services should embed or reference this in their own request types
type ExtractServerFileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ZipPath         string                 `protobuf:"bytes,1,opt,name=zip_path,json=zipPath,proto3" json:"zip_path,omitempty"`                         // Path to the zip file to extract
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"` // Directory path where files should be extracted
	VolumeName      *string                `protobuf:"bytes,3,opt,name=volume_name,json=volumeName,proto3,oneof" json:"volume_name,omitempty"`          // If specified, extract to this volume instead of container filesystem
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtractServerFileRequest) Reset() {
	*x = ExtractServerFileRequest{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractServerFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractServerFileRequest) ProtoMessage() {}

func (x *ExtractServerFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractServerFileRequest.ProtoReflect.Descriptor instead.
func (*ExtractServerFileRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractServerFileRequest) GetZipPath() string {
	if x != nil {
		return x.ZipPath
	}
	return ""
}

func (x *ExtractServerFileRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *ExtractServerFileRequest) GetVolumeName() string {
	if x != nil && x.VolumeName != nil {
		return *x.VolumeName
	}
	return ""
}

// ExtractServerFileResponse is a shared response message for extracting zip files
type ExtractServerFileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error          *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	FilesExtracted int32                  `protobuf:"varint,3,opt,name=files_extracted,json=filesExtracted,proto3" json:"files_extracted,omitempty"` // Number of files successfully extracted
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtractServerFileResponse) Reset() {
	*x = ExtractServerFileResponse{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractServerFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractServerFileResponse) ProtoMessage() {}

func (x *ExtractServerFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractServerFileResponse.ProtoReflect.Descriptor instead.
func (*ExtractServerFileResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractServerFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExtractServerFileResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ExtractServerFileResponse) GetFilesExtracted() int32 {
	if x != nil {
		return x.FilesExtracted
	}
	return 0
}

// CreateServerFileArchiveRequest is a shared request message for creating zip archives
// Resource-specific services should embed or reference this in their own request types
type CreateServerFileArchiveRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourcePaths         []string               `protobuf:"bytes,1,rep,name=source_paths,json=sourcePaths,proto3" json:"source_paths,omitempty"`                            // Paths to files/folders to zip
	DestinationPath     string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`                // Path where the zip file should be created
	IncludeParentFolder bool                   `protobuf:"varint,3,opt,name=include_parent_folder,json=includeParentFolder,proto3" json:"include_parent_folder,omitempty"` // If true, zip includes the parent folder; if false, zip contains files directly
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateServerFileArchiveRequest) Reset() {
	*x = CreateServerFileArchiveRequest{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerFileArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerFileArchiveRequest) ProtoMessage() {}

func (x *CreateServerFileArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerFileArchiveRequest.ProtoReflect.Descriptor instead.
func (*CreateServerFileArchiveRequest) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *CreateServerFileArchiveRequest) GetSourcePaths() []string {
	if x != nil {
		return x.SourcePaths
	}
	return nil
}

func (x *CreateServerFileArchiveRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *CreateServerFileArchiveRequest) GetIncludeParentFolder() bool {
	if x != nil {
		return x.IncludeParentFolder
	}
	return false
}

// CreateServerFileArchiveResponse is a shared response message for creating zip archives
type CreateServerFileArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	ArchivePath   string                 `protobuf:"bytes,3,opt,name=archive_path,json=archivePath,proto3" json:"archive_path,omitempty"`        // Path to the created zip file
	FilesArchived int32                  `protobuf:"varint,4,opt,name=files_archived,json=filesArchived,proto3" json:"files_archived,omitempty"` // Number of files archived
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerFileArchiveResponse) Reset() {
	*x = CreateServerFileArchiveResponse{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerFileArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerFileArchiveResponse) ProtoMessage() {}

func (x *CreateServerFileArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerFileArchiveResponse.ProtoReflect.Descriptor instead.
func (*CreateServerFileArchiveResponse) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *CreateServerFileArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateServerFileArchiveResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *CreateServerFileArchiveResponse) GetArchivePath() string {
	if x != nil {
		return x.ArchivePath
	}
	return ""
}

func (x *CreateServerFileArchiveResponse) GetFilesArchived() int32 {
	if x != nil {
		return x.FilesArchived
	}
	return 0
}

// ChunkedUploadPayload standardizes chunked file uploads across resources (gameservers, deployments, etc.)
// Resource-specific services should wrap this in their own requests alongside resource identifiers.
type ChunkedUploadPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DestinationPath string                 `protobuf:"bytes,1,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"` // Directory path where files should be extracted (default: "/")
	VolumeName      *string                `protobuf:"bytes,2,opt,name=volume_name,json=volumeName,proto3,oneof" json:"volume_name,omitempty"`          // Optional target volume instead of container filesystem
	FileName        string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                      // Name of the file being uploaded
	FileSize        int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                     // Total size of the complete file (for validation)
	ChunkIndex      int32                  `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`               // 0-based index of this chunk
	TotalChunks     int32                  `protobuf:"varint,6,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`            // Total number of chunks for this file
	ChunkData       []byte                 `protobuf:"bytes,7,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`                   // Raw file data for this chunk
	FileMode        *string                `protobuf:"bytes,8,opt,name=file_mode,json=fileMode,proto3,oneof" json:"file_mode,omitempty"`                // File permissions (e.g., "0644"), optional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkedUploadPayload) Reset() {
	*x = ChunkedUploadPayload{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkedUploadPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkedUploadPayload) ProtoMessage() {}

func (x *ChunkedUploadPayload) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkedUploadPayload.ProtoReflect.Descriptor instead.
func (*ChunkedUploadPayload) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkedUploadPayload) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *ChunkedUploadPayload) GetVolumeName() string {
	if x != nil && x.VolumeName != nil {
		return *x.VolumeName
	}
	return ""
}

func (x *ChunkedUploadPayload) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ChunkedUploadPayload) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ChunkedUploadPayload) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkedUploadPayload) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ChunkedUploadPayload) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *ChunkedUploadPayload) GetFileMode() string {
	if x != nil && x.FileMode != nil {
		return *x.FileMode
	}
	return ""
}

// ChunkedUploadResponsePayload represents the result of processing a single chunk.
type ChunkedUploadResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                 // Name of the uploaded file
	BytesReceived int64                  `protobuf:"varint,4,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"` // Total bytes received for this file so far
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkedUploadResponsePayload) Reset() {
	*x = ChunkedUploadResponsePayload{}
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkedUploadResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkedUploadResponsePayload) ProtoMessage() {}

func (x *ChunkedUploadResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_obiente_cloud_common_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkedUploadResponsePayload.ProtoReflect.Descriptor instead.
func (*ChunkedUploadResponsePayload) Descriptor() ([]byte, []int) {
	return file_obiente_cloud_common_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkedUploadResponsePayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChunkedUploadResponsePayload) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ChunkedUploadResponsePayload) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ChunkedUploadResponsePayload) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

var File_obiente_cloud_common_v1_common_proto protoreflect.FileDescriptor

const file_obiente_cloud_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"$obiente/cloud/common/v1/common.proto\x12\x17obiente.cloud.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"r\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xff\x03\n" +
	"\aVPSSize\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x06 \x01(\x03R\tdiskBytes\x122\n" +
	"\x15bandwidth_bytes_month\x18\a \x01(\x03R\x13bandwidthBytesMonth\x122\n" +
	"\x15minimum_payment_cents\x18\b \x01(\x03R\x13minimumPaymentCents\x12\x1c\n" +
	"\tavailable\x18\t \x01(\bR\tavailable\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12>\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tcreatedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tupdatedAt\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"\x96\x01\n" +
	"\x18ExtractServerFileRequest\x12\x19\n" +
	"\bzip_path\x18\x01 \x01(\tR\azipPath\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\x12$\n" +
	"\vvolume_name\x18\x03 \x01(\tH\x00R\n" +
	"volumeName\x88\x01\x01B\x0e\n" +
	"\f_volume_name\"\x83\x01\n" +
	"\x19ExtractServerFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12'\n" +
	"\x0ffiles_extracted\x18\x03 \x01(\x05R\x0efilesExtractedB\b\n" +
	"\x06_error\"\xa2\x01\n" +
	"\x1eCreateServerFileArchiveRequest\x12!\n" +
	"\fsource_paths\x18\x01 \x03(\tR\vsourcePaths\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\x122\n" +
	"\x15include_parent_folder\x18\x03 \x01(\bR\x13includeParentFolder\"\xaa\x01\n" +
	"\x1fCreateServerFileArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12!\n" +
	"\farchive_path\x18\x03 \x01(\tR\varchivePath\x12%\n" +
	"\x0efiles_archived\x18\x04 \x01(\x05R\rfilesArchivedB\b\n" +
	"\x06_error\"\xc4\x02\n" +
	"\x14ChunkedUploadPayload\x12)\n" +
	"\x10destination_path\x18\x01 \x01(\tR\x0fdestinationPath\x12$\n" +
	"\vvolume_name\x18\x02 \x01(\tH\x00R\n" +
	"volumeName\x88\x01\x01\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1f\n" +
	"\vchunk_index\x18\x05 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x06 \x01(\x05R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\a \x01(\fR\tchunkData\x12 \n" +
	"\tfile_mode\x18\b \x01(\tH\x01R\bfileMode\x88\x01\x01B\x0e\n" +
	"\f_volume_nameB\f\n" +
	"\n" +
	"_file_mode\"\xa1\x01\n" +
	"\x1cChunkedUploadResponsePayload\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12%\n" +
	"\x0ebytes_received\x18\x04 \x01(\x03R\rbytesReceivedB\b\n" +
	"\x06_error*\x8c\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_TRACE\x10\x01\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x03\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x05BMZKgithub.com/obiente/cloud/apps/shared/proto/obiente/cloud/common/v1;commonv1b\x06proto3"

var (
	file_obiente_cloud_common_v1_common_proto_rawDescOnce sync.Once
	file_obiente_cloud_common_v1_common_proto_rawDescData []byte
)

func file_obiente_cloud_common_v1_common_proto_rawDescGZIP() []byte {
	file_obiente_cloud_common_v1_common_proto_rawDescOnce.Do(func() {
		file_obiente_cloud_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_obiente_cloud_common_v1_common_proto_rawDesc), len(file_obiente_cloud_common_v1_common_proto_rawDesc)))
	})
	return file_obiente_cloud_common_v1_common_proto_rawDescData
}

var file_obiente_cloud_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_obiente_cloud_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_obiente_cloud_common_v1_common_proto_goTypes = []any{
	(LogLevel)(0),                           // 0: obiente.cloud.common.v1.LogLevel
	(*Pagination)(nil),                      // 1: obiente.cloud.common.v1.Pagination
	(*VPSSize)(nil),                         // 2: obiente.cloud.common.v1.VPSSize
	(*ExtractServerFileRequest)(nil),        // 3: obiente.cloud.common.v1.ExtractServerFileRequest
	(*ExtractServerFileResponse)(nil),       // 4: obiente.cloud.common.v1.ExtractServerFileResponse
	(*CreateServerFileArchiveRequest)(nil),  // 5: obiente.cloud.common.v1.CreateServerFileArchiveRequest
	(*CreateServerFileArchiveResponse)(nil), // 6: obiente.cloud.common.v1.CreateServerFileArchiveResponse
	(*ChunkedUploadPayload)(nil),            // 7: obiente.cloud.common.v1.ChunkedUploadPayload
	(*ChunkedUploadResponsePayload)(nil),    // 8: obiente.cloud.common.v1.ChunkedUploadResponsePayload
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
}
var file_obiente_cloud_common_v1_common_proto_depIdxs = []int32{
	9, // 0: obiente.cloud.common.v1.VPSSize.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: obiente.cloud.common.v1.VPSSize.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_obiente_cloud_common_v1_common_proto_init() }
func file_obiente_cloud_common_v1_common_proto_init() {
	if File_obiente_cloud_common_v1_common_proto != nil {
		return
	}
	file_obiente_cloud_common_v1_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_obiente_cloud_common_v1_common_proto_msgTypes[2].OneofWrappers = []any{}
	file_obiente_cloud_common_v1_common_proto_msgTypes[3].OneofWrappers = []any{}
	file_obiente_cloud_common_v1_common_proto_msgTypes[5].OneofWrappers = []any{}
	file_obiente_cloud_common_v1_common_proto_msgTypes[6].OneofWrappers = []any{}
	file_obiente_cloud_common_v1_common_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obiente_cloud_common_v1_common_proto_rawDesc), len(file_obiente_cloud_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_obiente_cloud_common_v1_common_proto_goTypes,
		DependencyIndexes: file_obiente_cloud_common_v1_common_proto_depIdxs,
		EnumInfos:         file_obiente_cloud_common_v1_common_proto_enumTypes,
		MessageInfos:      file_obiente_cloud_common_v1_common_proto_msgTypes,
	}.Build()
	File_obiente_cloud_common_v1_common_proto = out.File
	file_obiente_cloud_common_v1_common_proto_goTypes = nil
	file_obiente_cloud_common_v1_common_proto_depIdxs = nil
}
